/** User-facing FCL vocabulary. Persisted keys and API contracts stay in English. */
export const FCL_FIELDS:Record<string,{zh:string;en:string}>=Object.fromEntries(Object.entries({
  cargo:['货物','Cargo'],ready_terms:['备货日期 / 贸易条款','Ready / Incoterm'],charge_name:['费用名称','Charge Name'],group:['费用分组','Charge Group'],customer_note:['客户备注','Customer Note'],internal_note:['内部备注','Internal Note'],public_note:['客户可见说明','Customer Note'],scope_note:['说明','Note'],evidence_ref:['费用依据','Cost Evidence'],evidence_version:['依据版本','Evidence Version'],issuer_name:['出具人名称','Issuer'],issuer_address:['出具人地址','Issuer Address'],issuer_email:['出具人邮箱','Issuer Email'],issuer_phone:['出具人电话','Issuer Phone'],status:['状态','Status'],
  sort:['排序字段','Sort By'],direction:['排序顺序','Order'],catalog:['常用费用','Charge Catalog'],margin_mode:['利润规则','Margin Rule'],USD:['美元兑人民币','USD / CNY'],CAD:['加元兑人民币','CAD / CNY'],rate_id:['海运来源','Ocean Rate'],selected_rate:['船公司 / 海运费','Ocean Rate'],
  carrier:['船公司','Carrier'],supplier_label:['供应商','Supplier'],pol:['起运港','POL'],pod:['目的港','POD'],destination:['最终目的地','Destination'],final_destination:['最终目的地','Destination'],origin:['起点','Origin'],origin_city:['起运城市','Origin City'],
  container_type:['柜型','Container Type'],containers:['柜型与柜数','Containers'],quantity:['数量','Quantity'],vessel:['船名','Vessel'],voyage:['航次','Voyage'],etd:['开船日期','ETD'],eta:['预计到港','ETA'],transit_days:['航程（天）','Transit Time'],routing:['运输路线','Routing'],
  shipping_date:['预计出运日期','Estimated Shipping Date'],cargo_ready_date:['备货日期','Cargo Ready Date'],cargo_name:['货物品名','Commodity'],cargo_type:['货物属性','Cargo Type'],estimated_weight:['预计毛重','Gross Weight'],weight_kg:['重量（kg）','Weight'],volume_cbm:['体积（m³）','CBM'],incoterm:['贸易条款','Incoterm'],incoterm_other:['其他条款说明','Other Terms'],
  ocean_freight:['海运费','Ocean Freight'],origin_charges:['起运港费用','Origin Charges'],destination_charges:['目的港费用','Destination Charges'],inland_delivery:['内陆运输','Inland Delivery'],customs:['清关费用','Customs / Brokerage'],risk:['风险预留','Risk Reserve'],other:['其他附加费','Other Surcharges'],
  total_cost:['总成本','Total Cost'],cost_total:['总成本','Total Cost'],sell_price:['销售价','Sell Price'],sell_total:['销售总额','Sell Total'],gross_profit:['毛利','Gross Profit'],gross_margin:['毛利率','Gross Margin'],cost_price:['成本单价','Cost Price'],validity:['有效期','Validity'],valid_from:['生效日期','Valid From'],valid_until:['失效日期','Valid To'],quote_status:['报价状态','Quote Status'],
  name_zh:['费用名称（中文）','Charge Name'],name_en:['费用名称（英文）','English Name'],code:['费用代码','Charge Code'],amount:['成本金额','Cost Amount'],sell_amount:['销售价（选填）','Fixed Sell Price'],currency:['币种','Currency'],unit:['计费单位','Charge Unit'],category:['费用分类','Category'],editable:['允许人工调整售价','Editable'],remark:['备注','Remark'],reason:['修改原因','Adjustment Reason'],
  country:['国家','Country'],postal_code:['邮编','ZIP / Postal Code'],postal_codes:['适用邮编','Postal Codes'],zone:['区域','Zone'],zones:['适用区域','Zones'],service_mode:['运输模式','Service Mode'],customs_mode:['清关模式','Customs Mode'],base_rate:['基础价格','Base Rate'],tiers:['阶梯价格','Tier Rate'],surcharge_ids:['附加费','Surcharges'],
  weight_min_kg:['最低重量（kg）','Min Weight'],weight_max_kg:['最高重量（kg）','Weight Limit'],volume_min_cbm:['最低体积（m³）','Min CBM'],volume_max_cbm:['最高体积（m³）','CBM Limit'],margin_rule:['利润规则','Margin Rule'],margin_value:['利润规则比例','Margin Ratio'],cost_markup:['成本加成','Cost Markup'],target_margin:['目标毛利率','Target Gross Margin'],exchange_rates:['汇率','Exchange Rate'],fx_source:['汇率来源','FX Source'],
  source_ref:['价格来源','Source'],source_version:['来源版本','Source Version'],version:['版本','Version'],label:['名称','Name'],template:['目的地模板','Destination Template'],charge_ids:['固定费用项目','Charge Items'],delivery_rate_id:['内陆运价','Delivery Rate'],container_types:['支持柜型','Container Types'],
  'contact.name':['联系人','Contact'],'contact.email':['电子邮箱','Email'],'contact.company':['公司名称','Company'],'contact.phone':['联系电话','Phone'],notes:['补充说明','Notes'],selected_services:['服务范围','Services'],pickup:['中国提货','Pickup'],export_customs:['中国出口报关','Export Customs'],canada_customs:['加拿大清关','Customs Clearance'],devanning_storage:['拆柜与仓储','Devanning / Storage'],delivery:['内陆运输','Inland Delivery'],
  recipient:['收件人','Recipient'],cc:['抄送','CC'],subject:['邮件主题','Subject'],body:['邮件正文','Email Body'],attachments:['附件','Attachments'],
  quote_version:['报价版本','Quote Version'],quote_no:['报价单编号','Quote Number'],quote_date:['报价日期','Quote Date'],customer:['客户','Customer'],inquiry:['询价','Inquiry'],case_ref:['关联客户询价','Inquiry'],generated_at:['生成时间','Generated At'],send_status:['发送状态','Send Status'],review_status:['审核状态','Review Status'],price_breakdown:['报价组成','Price Breakdown'],price_history:['历史价格','Price History'],price_trend:['价格趋势','Price Trend'],
}).map(([key,[zh,en]])=>[key,{zh:zh!,en:en!}]));
const mailFields=new Set(['recipient','cc','subject','body','attachments','send_status']);
export const fclField=(key:string)=>mailFields.has(key)?FCL_FIELDS[key]!.zh:FCL_FIELDS[key]?`${FCL_FIELDS[key].zh} ${FCL_FIELDS[key].en}`:key;
export const fclFieldHtml=(key:string)=>mailFields.has(key)?`<span class="fcl-field-zh">${FCL_FIELDS[key]!.zh}</span>`:FCL_FIELDS[key]?`<span class="fcl-field-zh">${FCL_FIELDS[key].zh}</span><small class="fcl-field-en">${FCL_FIELDS[key].en}</small>`:key;

export const FCL_CHARGE_CATALOG=[
  ['ocean_freight','海运费','Ocean Freight','ocean'],['origin_surcharge','起运港附加费','Origin Surcharge','origin'],['pss','旺季附加费','PSS','ocean'],['gri','综合费率上涨附加费','GRI','ocean'],['lss','低硫附加费','LSS / LSF','ocean'],['baf','燃油附加费','BAF','ocean'],['caf','汇率附加费','CAF','ocean'],['ebs','紧急燃油附加费','EBS','ocean'],['ams','AMS申报费','AMS Fee','origin'],['isf','ISF申报费','ISF Fee','customs'],['aci','ACI申报费','ACI Fee','customs'],['documentation','文件费','Documentation Fee','destination'],['seal','封条费','Seal Fee','origin'],['equipment','设备费','Equipment Fee','ocean'],['other_surcharge','其他附加费','Other Surcharge','other'],
  ['thc','码头操作费','THC','destination'],['do','换单费','D/O Fee','destination'],['clearance','清关费','Customs Clearance','customs'],['brokerage','报关代理费','Brokerage Fee','customs'],['bond','保证金费用','Bond Fee','customs'],['exam','查验预留','Exam Reserve','risk'],['port','港口费','Port Fee','destination'],['chassis','车架费','Chassis Fee','destination'],['pre_pull','预提费','Pre-pull Fee','destination'],['storage','仓储费','Storage','destination'],['demurrage','滞箱费','Demurrage','destination'],['detention','滞柜费','Detention','destination'],['devanning','拆柜费','Devanning','destination'],['warehouse_handling','仓库操作费','Warehouse Handling','destination'],['palletizing','打托费','Palletizing','destination'],['appointment','预约费','Appointment Fee','destination'],['residential','住宅附加费','Residential Surcharge','inland'],['limited_access','受限地点费','Limited Access Fee','inland'],['liftgate','尾板费','Liftgate Fee','inland'],['remote_area','偏远地区费','Remote Area Surcharge','inland'],['overweight','超重费','Overweight Fee','inland'],['fuel','燃油附加费','Fuel Surcharge','inland'],['other_destination','其他目的港费用','Other Destination Charge','destination'],['risk_reserve','风险预留','Risk Reserve','risk'],
] as const;

export const FCL_SERVICE_MODE_LABELS={FTL:'整车运输 FTL',LTL:'零担运输 LTL',container_drayage:'集装箱拖车 Container Drayage',bonded_truck:'保税卡车 Bonded Truck',rail_truck:'铁路＋卡车 Rail + Truck',warehouse_transfer:'仓库转运 Warehouse Transfer'};

/** Legacy forms resolve to the same vocabulary while preserving their DOM names. */
const aliases:Record<string,string>={
  '中国起运城市':'origin_city','来源/供应商':'supplier_label','起运港（POL）':'pol','目的港（POD）':'pod','有效起':'valid_from','有效止':'valid_until','海运费 / 柜':'ocean_freight','客户售价':'sell_price','售价':'sell_price','成本':'cost_price','成本价':'cost_price','运价依据（文件或邮件编号）':'source_ref','附费名称':'charge_name','人工费用名称':'charge_name','单位':'unit','分组':'group','公司':'contact.company','联系人':'contact.name','邮箱':'contact.email','电话':'contact.phone','服务':'selected_services','报价单备注':'remark','报价备注':'remark','来源备注':'remark','说明':'scope_note',
};
export function fclFieldLabel(label:string):string{
  const key=aliases[label]??Object.keys(FCL_FIELDS).find(key=>FCL_FIELDS[key]?.zh===label);
  return key?fclField(key):label;
}
