import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { PortalError, type Grant, type PortalContext, type PortalIdentity } from "../../services/access-gateway/portal/contracts";
import { PortalService } from "../../services/access-gateway/portal/service";
import { SqliteSyntheticPortalStore } from "../../services/access-gateway/portal/store";

const roots:string[]=[]; const now="2026-09-05T12:00:00.000Z"; let seq=0;
const identity=(userId:string,email:string,platformRole:null|"reviewer"|"operator"=null):PortalIdentity=>({userId,displayName:userId,email,emailVerified:true,platformRole});
const ctx=(id:PortalIdentity,organizationId:string|null):PortalContext=>({identity:id,organizationId});
function setup(){const root=mkdtempSync(join(tmpdir(),"portal-domain-"));roots.push(root);const store=new SqliteSyntheticPortalStore({databasePath:join(root,"portal.sqlite")});const service=new PortalService({repository:store,now:()=>now,id:p=>`${p}_${String(++seq).padStart(8,"0")}`});return {store,service};}
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});

describe("portal domain",()=>{
  it("persists invitation, membership, application, approval and separately activated grant",()=>{
    const {store,service}=setup();const owner=identity("user_owner","owner@example.com","operator");
    service.bootstrapOrganization(ctx(owner,null),{idempotencyKey:"bootstrap-key-0001",input:{organizationId:"org_acme",tenantId:"tenant_acme",displayName:"Acme"}});
    const ownerCtx=ctx(owner,"org_acme"); const invited=service.inviteMember(ownerCtx,{idempotencyKey:"invite-key-0000001",input:{email:"dev@example.com",role:"developer",expiresAt:"2026-10-05T00:00:00.000Z"}}).data as {invitationId:string};
    const dev=identity("user_developer","dev@example.com");const onboarding=service.getState(ctx(dev,null)).data!;expect(onboarding.current_organization).toBeNull();expect(onboarding.invitations).toHaveLength(1);expect(onboarding.organizations).toEqual([{organizationId:"org_acme",displayName:"Acme",status:"active"}]);service.claimInvitation(ctx(dev,null),invited.invitationId,"claim-key-00000001");
    const devCtx=ctx(dev,"org_acme");service.createApplication(devCtx,{idempotencyKey:"application-key-01",input:{applicationId:"app_quote",clientId:"client_quote",name:"Quote agent",purpose:"integration",environment:"test",ownerUserId:dev.userId}});
    service.createRequest(devCtx,{idempotencyKey:"request-create-001",input:{requestId:"request_quote",applicationId:"app_quote",capabilities:["cargo.calculate"],justification:"calculate cargo"}});
    service.submitRequest(devCtx,"request_quote",1,"request-submit-001");
    const reviewer=identity("user_reviewer","reviewer@example.com","reviewer");service.markRequestInReview(ctx(reviewer,"org_acme"),"request_quote",2,"review-start-0001");
    const decision=service.decideRequest(ctx(reviewer,"org_acme"),"request_quote",{idempotencyKey:"review-decide-001",expectedVersion:3,input:{decision:"approve",reason:"approved scope"}}).data as {grant:{grantId:string;version:number;state:string}};
    expect(decision.grant.state).toBe("provisioning");const provisioning=service.getProvisioningQueue(ctx(owner,null)).data!;expect(provisioning.grants[0]).toMatchObject({grantId:decision.grant.grantId,version:1,applicationId:"app_quote"});expect(provisioning).not.toHaveProperty("tenantId");expect(()=>service.requireMachineGrants("client_quote",["cargo.calculate"])).toThrowError("machine_authorization_denied");
    service.markGrantActive(ctx(owner,"org_acme"),decision.grant.grantId,{idempotencyKey:"grant-active-0001",expectedVersion:1,input:{provisionedRef:"credential_ref_001"}});
    expect(service.requireMachineGrants("client_quote",["cargo.calculate"])).toMatchObject({organizationId:"org_acme",tenantId:"tenant_acme",applicationId:"app_quote"});
    store.close();const reopened=new SqliteSyntheticPortalStore({databasePath:join(roots[0]!,"portal.sqlite")});const read=new PortalService({repository:reopened,now:()=>now}).getState(devCtx).data!;expect(read.data_mode).toBe("fixtures");expect(read.grants[0]?.state).toBe("active");reopened.close();
  });
  it("rejects self review, cross-tenant access and removal of the last owner",()=>{
    const {store,service}=setup();const owner=identity("user_owner","owner@example.com","operator");service.bootstrapOrganization(ctx(owner,null),{idempotencyKey:"bootstrap-key-0002",input:{organizationId:"org_one",tenantId:"tenant_one",displayName:"One"}});const c=ctx(owner,"org_one");
    service.createApplication(c,{idempotencyKey:"application-key-02",input:{applicationId:"app_one",clientId:"client_one",name:"One",purpose:"test",environment:"test",ownerUserId:owner.userId}});service.createRequest(c,{idempotencyKey:"request-create-002",input:{requestId:"request_one",applicationId:"app_one",capabilities:["cargo.calculate"],justification:"test"}});service.submitRequest(c,"request_one",1,"request-submit-002");
    expect(()=>service.decideRequest(c,"request_one",{idempotencyKey:"review-decide-002",expectedVersion:2,input:{decision:"approve",reason:"self"}})).toThrowError(PortalError);
    expect(()=>service.changeMembership(c,owner.userId,{idempotencyKey:"member-change-001",input:{role:"admin"}})).toThrowError("last_owner_protected");
    expect(()=>service.getState(ctx(identity("other_user","other@example.com"),"org_one"))).toThrowError("active_organization_membership_required");store.close();
  });
  it("scopes state to one active organization and scopes idempotency to actor",()=>{const {store,service}=setup();const op=identity("operator_scope","scope@example.com","operator");service.bootstrapOrganization(ctx(op,null),{idempotencyKey:"scope-bootstrap-01",input:{organizationId:"org_scope_a",tenantId:"tenant_scope_a",displayName:"A"}});service.bootstrapOrganization(ctx(op,null),{idempotencyKey:"scope-bootstrap-02",input:{organizationId:"org_scope_b",tenantId:"tenant_scope_b",displayName:"B"}});const state=service.getState(ctx(op,"org_scope_a")).data!;expect(state.memberships.every(x=>x.organizationId==="org_scope_a")).toBe(true);expect(state.operations.every(x=>x.organizationId==="org_scope_a")).toBe(true);expect(()=>service.bootstrapOrganization(ctx(identity("operator_other","otherop@example.com","operator"),null),{idempotencyKey:"scope-bootstrap-01",input:{organizationId:"org_scope_a",tenantId:"tenant_scope_a",displayName:"A"}})).toThrowError("idempotency_conflict");const queue=service.getReviewQueue(ctx(identity("review_queue","reviewq@example.com","reviewer"),null)).data!;expect(queue).toEqual({requests:[],organizations:[],applications:[]});store.close();});
  it("replays identical idempotency and rejects changed input",()=>{const {store,service}=setup();const operator=identity("user_operator","op@example.com","operator");const mutation={idempotencyKey:"bootstrap-key-0003",input:{organizationId:"org_idem",tenantId:"tenant_idem",displayName:"Idem"}};expect(service.bootstrapOrganization(ctx(operator,null),mutation)).toEqual(service.bootstrapOrganization(ctx(operator,null),mutation));expect(()=>service.bootstrapOrganization(ctx(operator,null),{...mutation,input:{...mutation.input,displayName:"Changed"}})).toThrowError("idempotency_conflict");store.close();});
  it("supports needs-input revision and partial approval without granting unavailable scope",()=>{const {store,service}=setup();const owner=identity("user_owner2","owner2@example.com","operator");service.bootstrapOrganization(ctx(owner,null),{idempotencyKey:"bootstrap-key-0004",input:{organizationId:"org_partial",tenantId:"tenant_partial",displayName:"Partial"}});const c=ctx(owner,"org_partial");service.createApplication(c,{idempotencyKey:"application-key-04",input:{applicationId:"app_partial",clientId:"client_partial",name:"Partial",purpose:"test",environment:"test",ownerUserId:owner.userId}});service.createRequest(c,{idempotencyKey:"request-create-004",input:{requestId:"request_partial",applicationId:"app_partial",capabilities:["cargo.calculate","container.plan_summary"],justification:"first"}});service.submitRequest(c,"request_partial",1,"request-submit-004");const reviewer=identity("reviewer_other","review2@example.com","reviewer");service.decideRequest(ctx(reviewer,"org_partial"),"request_partial",{idempotencyKey:"review-needs-0001",expectedVersion:2,input:{decision:"needs_input",reason:"narrow scope"}});service.updateRequest(c,"request_partial",{idempotencyKey:"request-update-004",expectedVersion:3,input:{capabilities:["cargo.calculate","container.plan_summary"],justification:"revised"}});service.submitRequest(c,"request_partial",4,"request-resubmit-04");const result=service.decideRequest(ctx(reviewer,"org_partial"),"request_partial",{idempotencyKey:"review-partial-001",expectedVersion:5,input:{decision:"approve",reason:"cargo only",approvedCapabilities:["cargo.calculate"]}}).data as {grant:Grant};expect(result.grant.capabilities).toEqual(["cargo.calculate"]);expect(()=>service.requireMachineGrants("client_partial",["container.plan_summary"])).toThrowError("machine_authorization_denied");store.close();});
});
