import { lstatSync, mkdtempSync, rmSync,symlinkSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";

import { afterEach,describe,expect,it } from "vitest";

import { SqliteProductionBusinessAccessStore } from "../../services/access-gateway/portal/business-access/store";
import { SqlitePersistentPortalSessionStore,PortalSessionManager,type PortalSession } from "../../services/access-gateway/portal/session";
import { SqliteProductionPortalStore } from "../../services/access-gateway/portal/store";

const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const root=()=>{const value=mkdtempSync(join(tmpdir(),"portal-production-"));roots.push(value);return value;};
const session=(id:string,expiresAt:number):PortalSession=>({sessionId:id,csrfToken:"c".repeat(43),identity:null,organizationId:null,oidcTransaction:{state:"state",nonce:"nonce",codeVerifier:"verifier",authorizationUrl:"https://id.example/authorize"},createdAt:1,expiresAt});

describe("single-node production persistence",()=>{
  it("persists Portal state and idempotency across restart and rolls back failed mutations",()=>{const path=join(root(),"portal.sqlite");let store=new SqliteProductionPortalStore({databasePath:path});expect(store.kind).toBe("production");const result=store.transact("organization.create","idempotency-key-0001","hash-a",data=>{data.users.push({userId:"user-1",displayName:"User",email:"user@example.test",emailVerified:true,createdAt:"2026-09-05T00:00:00Z"});return{id:"user-1"};});expect(result).toEqual({id:"user-1"});expect(()=>store.transact("organization.fail","idempotency-key-0002","hash-b",data=>{data.users.push({...data.users[0]!,userId:"bad"});throw new Error("rollback");})).toThrow("rollback");store.close();store=new SqliteProductionPortalStore({databasePath:path});expect(store.read().users.map(x=>x.userId)).toEqual(["user-1"]);expect(store.transact("organization.create","idempotency-key-0001","hash-a",()=>({id:"other"}))).toEqual({id:"user-1"});expect(()=>store.transact("organization.create","idempotency-key-0001","different",()=>null)).toThrow("idempotency_conflict");expect(lstatSync(path).mode&0o077).toBe(0);store.close();});

  it("persists Business Access state and replay identity across restart",()=>{const path=join(root(),"business.sqlite");let store=new SqliteProductionBusinessAccessStore({databasePath:path});const first=store.transact("scope","business-idempotency-01","hash",data=>{data.audit.push({auditId:"audit-1",organizationId:null,actorRef:"operator",action:"test",objectRef:"object",status:"success",requestId:"request",createdAt:"2026-09-05T00:00:00Z"});return{auditId:"audit-1"};});expect(first.replayed).toBe(false);store.close();store=new SqliteProductionBusinessAccessStore({databasePath:path});const replay=store.transact("scope","business-idempotency-01","hash",()=>({auditId:"wrong"}));expect(replay).toEqual({value:{auditId:"audit-1"},replayed:true});expect(store.read().audit).toHaveLength(1);store.close();});

  it("persists OIDC pending state, session revocation, CSRF and expiry",()=>{const path=join(root(),"sessions.sqlite");let store=new SqlitePersistentPortalSessionStore({databasePath:path});store.put(session("s".repeat(43),2_000));store.close();store=new SqlitePersistentPortalSessionStore({databasePath:path});const manager=new PortalSessionManager({store,now:()=>1_000,ttlMs:60_000,secureCookie:true});const restored=manager.get("s".repeat(43));expect(restored?.oidcTransaction?.state).toBe("state");expect(manager.verifyCsrf(restored!,"c".repeat(43))).toBe(true);store.delete("s".repeat(43));expect(manager.get("s".repeat(43))).toBeNull();store.put(session("e".repeat(43),999));expect(manager.get("e".repeat(43))).toBeNull();expect(store.get("e".repeat(43))).toBeNull();store.close();});

  it("consumes OIDC state once across store instances and rejects expired pending state",()=>{const path=join(root(),"oidc.sqlite"),first=new SqlitePersistentPortalSessionStore({databasePath:path}),second=new SqlitePersistentPortalSessionStore({databasePath:path});let now=1_000;const managerA=new PortalSessionManager({store:first,now:()=>now,ttlMs:600_000}),managerB=new PortalSessionManager({store:second,now:()=>now,ttlMs:600_000});const created=managerA.ensure(null).session;const pending=managerA.beginOidc(created.sessionId,{state:"once",nonce:"nonce",codeVerifier:"verifier",authorizationUrl:"https://id.example/authorize"});expect(managerB.consumeOidc(pending.sessionId,"once").state).toBe("once");expect(()=>managerA.consumeOidc(pending.sessionId,"once")).toThrow("oidc_state_invalid");const next=managerA.ensure(null).session;managerA.beginOidc(next.sessionId,{state:"expires",nonce:"nonce",codeVerifier:"verifier",authorizationUrl:"https://id.example/authorize"});now+=300_001;expect(()=>managerB.consumeOidc(next.sessionId,"expires")).toThrow("oidc_state_invalid");first.close();second.close();});

  it("does not let an in-flight compare-and-swap revive a logged-out session",()=>{const path=join(root(),"logout.sqlite"),first=new SqlitePersistentPortalSessionStore({databasePath:path}),second=new SqlitePersistentPortalSessionStore({databasePath:path}),manager=new PortalSessionManager({store:first,now:()=>1_000,ttlMs:600_000});const current=manager.ensure(null).session,stale={...current,csrfToken:"n".repeat(43)};second.delete(current.sessionId);expect(first.replace(current.sessionId,current.csrfToken,stale)).toBe(false);expect(first.get(current.sessionId)).toBeNull();first.close();second.close();});

  it("rejects relative paths, database identity reuse and future schema versions",()=>{expect(()=>new SqliteProductionPortalStore({databasePath:"relative.sqlite"})).toThrow("portal_database_path_invalid");const linkRoot=root(),target=join(linkRoot,"target");writeFileSync(target,"not-a-database");symlinkSync(target,join(linkRoot,"linked.sqlite"));expect(()=>new SqliteProductionPortalStore({databasePath:join(linkRoot,"linked.sqlite")})).toThrow("portal_database_path_invalid");const directory=root(),path=join(directory,"state.sqlite");new SqliteProductionPortalStore({databasePath:path}).close();expect(()=>new SqliteProductionBusinessAccessStore({databasePath:path})).toThrow("portal_database_identity_mismatch");const future=join(directory,"future.sqlite"),database=new DatabaseSync(future);database.exec("PRAGMA user_version=99");database.close();expect(()=>new SqliteProductionPortalStore({databasePath:resolve(future)})).toThrow("portal_database_version_unsupported");});
});
