import { it, expect } from 'vitest';
import { mkdtempSync, readFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { NativeAdminStore, NativeAdminService } from '../../services/access-gateway/portal/native-admin';
import { NativeFreightcomService } from '../../services/access-gateway/portal/native-freightcom';
import type { PortalService } from '../../services/access-gateway/portal/service';
import type { PortalContext } from '../../services/access-gateway/portal/contracts';
import { config } from '../quote-native/fixture';
const ctx:PortalContext={organizationId:'org1',identity:{userId:'owner',displayName:'Owner',email:'owner@example.test',emailVerified:true,platformRole:null}};
const portal={getState:(c:PortalContext)=>({data:{current_organization:{status:'active'},memberships:[{organizationId:c.organizationId,userId:c.identity.userId,role:c.identity.userId==='viewer'?'viewer':'owner',status:'active'}]}})} as unknown as PortalService;
it('starts blank, enforces owner scope, preview, idempotency, version, publish, disable and rollback across restart',()=>{const path=join(mkdtempSync(join(tmpdir(),'native-admin-')),'native.sqlite');let store=new NativeAdminStore(path);let service=new NativeAdminService(store,portal);expect(service.get(ctx,'residential').draft).toBeNull();const viewer={...ctx,identity:{...ctx.identity,userId:'viewer'}};expect(()=>service.save(viewer,'residential',{expected_version:0,input:config},'key-create-00001')).toThrow('native_management_denied');service.save(ctx,'residential',{expected_version:0,input:config},'key-create-00001');expect(service.save(ctx,'residential',{expected_version:0,input:config},'key-create-00001').version).toBe(1);expect(()=>service.save(ctx,'residential',{expected_version:0,input:{...config,label:'changed'}},'key-create-00001')).toThrow('idempotency_conflict');const preview=service.preview(ctx,'residential');expect(preview.can_publish).toBe(true);expect(()=>service.publish(ctx,'residential',{expected_version:1,preview_hash:'0'.repeat(64),confirmation:'reviewed_sources_and_conditions'},'key-publish-bad1')).toThrow('native_preview_mismatch');const published=service.publish(ctx,'residential',{expected_version:1,preview_hash:preview.preview_hash,confirmation:'reviewed_sources_and_conditions'},'key-publish-0001');const id=published.active_release!.release_id;expect(store.current('org2','residential')).toBeNull();service.disable(ctx,'residential',{expected_version:2},'key-disable-0001');expect(store.current('org1','residential')).toBeNull();const back=service.preview(ctx,'residential',id);service.rollback(ctx,'residential',{expected_version:3,release_id:id,preview_hash:back.preview_hash,confirmation:'reviewed_sources_and_conditions'},'key-rollback-001');store.close();store=new NativeAdminStore(path);service=new NativeAdminService(store,portal);expect(service.get(ctx,'residential').active_release?.release_id).toBe(id);expect(()=>service.preview({...ctx,organizationId:'org2'},'residential',id)).toThrow('native_draft_missing');store.close();});
it('stores carrier credentials encrypted, scopes decryption, returns only presence and supports disable',()=>{const path=join(mkdtempSync(join(tmpdir(),'native-secret-')),'native.sqlite'),store=new NativeAdminStore(path),service=new NativeFreightcomService(store,portal);const credential='isolated-synthetic-credential-1234567890';const saved=service.change(ctx,{expected_version:0,label:'Synthetic account',credential,confirmation:'use_for_current_organization'},'key-secret-00001');expect(saved.credential_present).toBe(true);expect(JSON.stringify(saved)).not.toContain(credential);expect(service.credential('org1')).toBe(credential);expect(()=>service.credential('org2')).toThrow();expect(readFileSync(path).includes(Buffer.from(credential))).toBe(false);service.change(ctx,{expected_version:1},'key-disable-0001',true);expect(()=>service.credential('org1')).toThrow();service.close();store.close();});

it('refuses a missing encryption key when saved credentials already exist',()=>{const path=join(mkdtempSync(join(tmpdir(),'native-lost-key-')),'native.sqlite'),store=new NativeAdminStore(path),service=new NativeFreightcomService(store,portal);service.change(ctx,{expected_version:0,label:'Synthetic',credential:'isolated-test-credential-123456789',confirmation:'use_for_current_organization'},'lost-key-test-001');service.close();unlinkSync(path+'.encryption-key');expect(()=>new NativeFreightcomService(store,portal)).toThrow('native_encryption_key_missing');store.close();});
