export interface ReviewedRuntimePackDescriptor {
  readonly format: "serializeAgentStandardPack:utf8-json-pretty-lf:v1";
  readonly registry_id: "logistics-mcp.agent-standards";
  readonly pack_schema_version: "2026-08-21.v1";
  readonly standard_count: 11;
  readonly serialized_bytes: 116_998;
  readonly serialized_sha256: "sha256:18df36011c286380431594c89da1fe67e3e0560e777bc1837e93ad040fb5bc67";
}

/**
 * Code-reviewed identity for the only Agent Standard Pack accepted by the
 * runtime. Updating this descriptor requires reviewing the generated bytes.
 */
export const REVIEWED_RUNTIME_PACK_DESCRIPTOR: ReviewedRuntimePackDescriptor =
  Object.freeze({
    format: "serializeAgentStandardPack:utf8-json-pretty-lf:v1",
    registry_id: "logistics-mcp.agent-standards",
    pack_schema_version: "2026-08-21.v1",
    standard_count: 11,
    serialized_bytes: 116_998,
    serialized_sha256:
      "sha256:18df36011c286380431594c89da1fe67e3e0560e777bc1837e93ad040fb5bc67",
  });
