export interface ReviewedRuntimePackDescriptor {
  readonly format: "serializeAgentStandardPack:utf8-json-pretty-lf:v1";
  readonly registry_id: "logistics-mcp.agent-standards";
  readonly pack_schema_version: "2026-08-21.v1";
  readonly standard_count: 10;
  readonly serialized_bytes: 84_319;
  readonly serialized_sha256: "sha256:9aa0b0d2213872326853e4077990ac31cbdf2ea77041e06ddbd5a24abfd803d7";
}

/**
 * Code-reviewed identity for the only Agent Standard Pack accepted by the
 * runtime. Updating this descriptor requires reviewing the generated bytes.
 */
export const REVIEWED_RUNTIME_PACK_DESCRIPTOR: ReviewedRuntimePackDescriptor =
  Object.freeze({
    format: "serializeAgentStandardPack:utf8-json-pretty-lf:v1",
    registry_id: "logistics-mcp.agent-standards",
    pack_schema_version: "2026-08-21.v1",
    standard_count: 10,
    serialized_bytes: 84_319,
    serialized_sha256:
      "sha256:9aa0b0d2213872326853e4077990ac31cbdf2ea77041e06ddbd5a24abfd803d7",
  });
