import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {calculate,renderHtml,type FclRenderMetadata} from '../../services/quote-documents/engine';
import {sample,template} from './fixtures';
import {documentSchema} from '../../services/quote-documents/contracts';
const fclMeta=(overrides:Partial<FclRenderMetadata>={}):FclRenderMetadata=>({inquiry_no:'FCL-1',case_ref:'00000000-0000-4000-8000-000000000001',quote_ref:'00000000-0000-4000-8000-000000000002',rate_id:'00000000-0000-4000-8000-000000000003',release_id:'00000000-0000-4000-8000-000000000004',case_version:1,quote_version:1,document_version:1,pol:'Yantian',pod:'Vancouver',final_destination:null,containers:[{type:'40HQ',quantity:'2'}],incoterm:'EXW',incoterm_other:null,scope:[],...overrides});
describe('native quote documents',()=>{
 it('uses compact Chinese FCL units and removes insignificant price zeros without changing stored values',()=>{
  const d=sample();d.fee_items=[{...d.fee_items[0]!,unit:'SHIPMENT',unit_price:'495.000000',quantity:'1'},{...d.fee_items[0]!,id:randomUUID(),unit:'CNTR',unit_price:'0.123456',quantity:'1'}];
  const before=structuredClone(d),html=renderHtml(d,template,true,fclMeta());
  expect(html).toContain('<td>票</td>');expect(html).toContain('<td>柜</td>');expect(html).toContain('>495</td>');expect(html).toContain('>0.12</td>');expect(html).not.toContain('495.000000');expect(d).toEqual(before);
 });
 it('uses exact decimal totals and does not invent exchange rates',()=>{const d=sample(),v=calculate(d);expect(v.by_currency.USD).toBe('0.30');expect(v.total_cny).toBeNull();expect(v.total_usd).toBe('0.30');});
 it('honors hidden/merged visibility without leaking internal descriptions',()=>{const d=sample();d.fee_items.push({...d.fee_items[0]!,id:randomUUID(),name:'INTERNAL_SECRET',note:'PRIVATE_NOTE',display:'hiddenIncluded'},{...d.fee_items[0]!,id:randomUUID(),display:'hiddenExcluded'},{...d.fee_items[0]!,id:randomUUID(),name:'PRIVATE_MERGED',display:'merged',merge_name:'综合费用'});const v=calculate(d);expect(v.by_currency.USD).toBe('0.90');const html=renderHtml(d,template,false);expect(html).not.toContain('INTERNAL_SECRET');expect(html).not.toContain('PRIVATE_NOTE');expect(html).not.toContain('PRIVATE_MERGED');expect(html).toContain('综合费用');expect(html).toContain('DRAFT');});
 it('escapes text and rejects float money, missing merge names, duplicate IDs and invalid dates',()=>{const d=sample();d.customer_name='<script>alert(1)</script>';expect(renderHtml(d,template,false)).toContain('&lt;script&gt;');expect(documentSchema.safeParse({...d,valid_until:'2026-02-30'}).success).toBe(false);expect(documentSchema.safeParse({...d,fee_items:[{...d.fee_items[0],unit_price:0.1}]}).success).toBe(false);expect(documentSchema.safeParse({...d,fee_items:[d.fee_items[0],d.fee_items[0]]}).success).toBe(false);});
 it('keeps pure-CNY FCL totals in the original currency without an FX card',()=>{const d=sample();d.quote_no='FCL-CNY';d.fee_items=[{...d.fee_items[0]!,currency:'CNY',unit_price:'100',quantity:'1'}];d.exchange_rates={USD:null,CAD:null};const html=renderHtml(d,template,true,fclMeta());expect(html).toContain('CNY');expect(html).not.toContain('折算人民币');expect(html).not.toContain('填写汇率');});
 it('keeps pure-USD FCL totals without a duplicate USD conversion or empty FX line',()=>{const d=sample();d.quote_no='FCL-USD';d.fee_items=[{...d.fee_items[0]!,currency:'USD',unit_price:'100',quantity:'1'}];d.exchange_rates={USD:null,CAD:null};const html=renderHtml(d,template,true,fclMeta());expect(html).not.toContain('折算美元');expect(html).not.toContain('填写汇率');});
 it('shows only participating explicit FX rates in mixed-currency FCL totals',()=>{const d=sample();d.quote_no='FCL-MIXED';d.fee_items=[{...d.fee_items[0]!,currency:'USD',unit_price:'10',quantity:'1'},{...d.fee_items[0]!,id:randomUUID(),currency:'CAD',unit_price:'20',quantity:'1'}];d.exchange_rates={USD:'7',CAD:'5'};const html=renderHtml(d,template,true,fclMeta());expect(html).toContain('1 USD = 7 CNY');expect(html).toContain('1 CAD = 5 CNY');expect(html).not.toContain('未填写');});
 it('does not display a stored but unused FX rate',()=>{const d=sample();d.quote_no='FCL-USD-UNUSED-FX';d.fee_items=[{...d.fee_items[0]!,currency:'USD',unit_price:'10',quantity:'1'}];d.exchange_rates={USD:'7',CAD:'5'};const html=renderHtml(d,template,true,fclMeta());expect(html).toContain('1 USD = 7 CNY');expect(html).not.toContain('1 CAD = 5 CNY');});
 it('shows the USD denominator FX when only CAD amounts are present',()=>{const d=sample();d.quote_no='FCL-CAD-USD-DENOMINATOR';d.fee_items=[{...d.fee_items[0]!,currency:'CAD',unit_price:'20',quantity:'1'}];d.exchange_rates={USD:'7',CAD:'5'};const html=renderHtml(d,template,true,fclMeta());expect(html).toContain('1 USD = 7 CNY');expect(html).toContain('1 CAD = 5 CNY');expect(html).toContain('折算美元');});
 it('shows the USD denominator FX for CNY-only amounts and hides unused CAD FX',()=>{const d=sample();d.quote_no='FCL-CNY-USD-DENOMINATOR';d.fee_items=[{...d.fee_items[0]!,currency:'CNY',unit_price:'100',quantity:'1'}];d.exchange_rates={USD:'7',CAD:'5'};const html=renderHtml(d,template,true,fclMeta());expect(html).toContain('1 USD = 7 CNY');expect(html).toContain('折算美元');expect(html).not.toContain('1 CAD = 5 CNY');});
});
