import {afterEach,expect,it} from 'vitest';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createFclInquiryDraft} from '../../apps/inquiry/fcl-model';
import {CaseService,CaseStore} from '../../services/access-gateway/portal/cases';
import {NativeAdminService,NativeAdminStore} from '../../services/access-gateway/portal/native-admin';
import type {PortalContext} from '../../services/access-gateway/portal/contracts';
import type {PortalService} from '../../services/access-gateway/portal/service';
import {DocumentService,DocumentStore} from '../../services/quote-documents/service';
import {DocumentWorkflowService,DocumentWorkflowStore} from '../../services/quote-documents/workflow';
import {FCL_DOCUMENT_WORKFLOW_VERSION} from '../../services/quote-documents/fcl-contracts';
import {FclQuoteService} from '../../services/quote-native/fcl';
import {FCL_RATE_DATASET_VERSION,type FclRateDataset} from '../../services/quote-native/fcl-contracts';

const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
const receiverId='fcl-pdf-receiver',receiver:PortalContext={organizationId:null,identity:{userId:receiverId,displayName:'Receiver',email:'receiver@example.test',emailVerified:true,platformRole:null}};
const portal={getState:()=>({data:{current_organization:null,memberships:[]}})} as unknown as Pick<PortalService,'getState'>;const fcl={fcl:{mode:'fresh_fixture',authorized:true,oldWritersStopped:true}} as const;
function rates():FclRateDataset{return {contract_version:FCL_RATE_DATASET_VERSION,label:'PDF rates',rates:[{rate_id:'00000000-0000-4000-8000-000000000201',supplier_label:'INTERNAL-SUPPLIER',pol:'Yantian',pod:'Vancouver',valid_from:'2026-10-01',valid_until:'2026-10-15',source_ref:'internal:rate:secret',source_version:'v1',note:'INTERNAL-SOURCE-NOTE',items:[{container_type:'40HQ',ocean_freight:'3200',currency:'USD'}],additional_fees:[]}]};}
function inquiry(){return {...createFclInquiryDraft(),pol:'Yantian',pod:'Vancouver',cargo_name:'Synthetic cargo',containers:[{type:'40HQ' as const,quantity:2}],cargo_type:'general' as const,estimated_weight:{value:'18000',unit:'kg' as const},cargo_ready_date:'2026-10-08',incoterm:'EXW' as const,selected_services:['ocean_freight'] as const,contact:{name:'Synthetic Shipper',company:null,email:'shipper@example.test',phone:null},consent:true};}
function quoteInput(){return {source_sell_prices:[{row_key:'ocean_freight:40HQ',sell_price:'3500',customer_note:'Customer ocean note'}],manual_fees:[],service_scopes:[],exchange_rates:{USD:null,CAD:null},remark:null};}
it('exports only sell-side approved PDFs, reuses historical bytes and rejects cache or gate tampering',async()=>{
  const root=mkdtempSync(join(tmpdir(),'fcl-pdf-')),caseStore=new CaseStore(join(root,'cases.sqlite'),fcl),rateStore=new NativeAdminStore(join(root,'rates.sqlite'),fcl),documentStore=new DocumentStore(join(root,'documents.sqlite'),fcl);roots.push(root);let html='';
  const caseService=new CaseService(caseStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,credentialSecret:'synthetic-pdf-secret-32-bytes-long',credentialTtlDays:30,now:()=> '2026-10-08T12:00:00.000Z',mail:{enabled:false}}),rateService=new NativeAdminService(rateStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'});const submitted=await caseService.submitFclInquiry('fcl-pdf-session','fcl-pdf-submit-0001',inquiry()),confirmed=caseService.confirmFclCase(receiver,submitted.case_id,{expected_version:1,expected_customer_supplement_ref:null,confirmed_fields:{changes:[]},reason:'Confirmed'},'fcl-pdf-confirm-0001');rateService.save(receiver,'fcl',{expected_version:0,input:rates()},'fcl-pdf-rate-save-0001');const preview=rateService.preview(receiver,'fcl'),published=rateService.publish(receiver,'fcl',{expected_version:1,preview_hash:preview.preview_hash,confirmation:'reviewed_sources_and_conditions'},'fcl-pdf-rate-publish-0001'),quoteService=new FclQuoteService({caseReader:caseService,rateReader:rateService,now:()=> '2026-10-08T12:00:00.000Z'}),workflowStore=new DocumentWorkflowStore(documentStore,fcl);
  const pdf=Buffer.from('%PDF-1.7\n'+'.'.repeat(120));const service=new DocumentWorkflowService(workflowStore,new DocumentService(documentStore,portal),portal,value=>{html=value;return Promise.resolve(pdf);},{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'},{quoteService,caseReader:caseService,caseLock:caseService,rateLock:rateService,rateReader:rateService});
  service.saveFclConfig(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,expected_version:0,input:{issuer_name:'Issuer',issuer_address:'Address',issuer_phone:'',issuer_email:'',terms:'Terms',standard_fee_template_v1:null},confirmed:true},'fcl-pdf-config-0001');const quote=service.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',case_ref:confirmed.case_id,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,selected_rate_id:(published.active_release!.input as FclRateDataset).rates[0]!.rate_id,expected_release_id:published.active_release!.release_id,expected_release_version:published.active_release!.version,expected_dataset_digest:published.active_release!.digest,input:quoteInput()},'fcl-pdf-quote-0001');const doc=service.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',quote_ref:quote.quote_ref,expected_quote_version:1,expected_quote_digest:quote.content_digest,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-PDF-001',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-pdf-doc-0001');const review=service.reviewFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:doc.document_id,expected_version:1});service.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:doc.document_id,expected_version:1,review_hash:review.review_hash,confirmed:true},'fcl-pdf-approve-0001');
  const formal=await service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-export-0001');expect(formal).toMatchObject({mode:'formal',valid_now:true,sha256:createHash('sha256').update(pdf).digest('hex'),customer_totals:{by_currency:{USD:'7000.00'}}});expect(html).toContain('3500');expect(html).toContain('Yantian');expect(html).toContain('Vancouver');expect(html).not.toContain('3200');expect(html).not.toContain('INTERNAL-SUPPLIER');expect(html).not.toContain('INTERNAL-SOURCE-NOTE');expect(html).not.toContain('internal_note');expect(html).not.toContain('SO 号');expect(html).not.toContain('柜号');expect(html).not.toContain('未填写完整汇率');expect(html).not.toContain('ocean_freight');expect(html).not.toContain(': priced');
  const history=await service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'history',document_id:doc.document_id,target_version:2,expected_current_version:2},'fcl-pdf-history-0001');expect(history).toMatchObject({mode:'history',historical:true,valid_now:false,sha256:formal.sha256});expect(Buffer.from(history.content_base64,'base64')).toEqual(pdf);
  const cachedFormal=await service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-export-cache-0002');expect(cachedFormal).toMatchObject({sha256:formal.sha256,replay:{replayed:false,submitted_version:null,current:true}});expect(await service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-export-cache-0002')).toMatchObject({sha256:formal.sha256,replay:{replayed:true,submitted_version:2,current:true}});
  const tampered=Buffer.from('%PDF-1.7\nB'.repeat(80)),sha=createHash('sha256').update(tampered).digest('hex'),originalSha=createHash('sha256').update(pdf).digest('hex');documentStore.db.prepare('UPDATE document_pdfs SET sha256=?,bytes=? WHERE id=? AND version=2').run(sha,tampered,doc.document_id);await expect(service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'history',document_id:doc.document_id,target_version:2,expected_current_version:2},'fcl-pdf-history-tamper-01')).rejects.toThrow('document_readback_failed');await expect(service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-formal-tamper-01')).rejects.toThrow('document_readback_failed');documentStore.db.prepare('UPDATE document_pdfs SET sha256=?,bytes=? WHERE id=? AND version=2').run(originalSha,pdf,doc.document_id);
  const caseView=caseService.getFclCase(receiver,confirmed.case_id);caseService.updateFclCaseStatus(receiver,confirmed.case_id,{expected_version:caseView.case_version,status:'needs_input',public_note:'Changed',internal_note:''},'fcl-pdf-case-change-01');await expect(service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-formal-stale-01')).rejects.toThrow('fcl_document_not_current');expect((await service.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'history',document_id:doc.document_id,target_version:2,expected_current_version:2},'fcl-pdf-history-after-case-01')).sha256).toBe(formal.sha256);
  const readOnlyStore=DocumentWorkflowStore.openReadOnly(documentStore),readOnlyService=new DocumentWorkflowService(readOnlyStore,new DocumentService(documentStore,portal),portal,undefined,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'},{quoteService,caseReader:caseService,caseLock:caseService,rateLock:rateService,rateReader:rateService});expect((await readOnlyService.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'history',document_id:doc.document_id,target_version:2,expected_current_version:2},'fcl-pdf-history-readonly-01')).sha256).toBe(formal.sha256);await expect(readOnlyService.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:doc.document_id,expected_version:2},'fcl-pdf-formal-readonly-01')).rejects.toThrow('document_v3_rollback_read_only');
  documentStore.close();rateStore.close();caseStore.close();
});

async function probeFixture(renderer:(html:string)=>Promise<Buffer>){
  const root=mkdtempSync(join(tmpdir(),'fcl-pdf-probe-')),caseStore=new CaseStore(join(root,'cases.sqlite'),fcl),rateStore=new NativeAdminStore(join(root,'rates.sqlite'),fcl),documentStore=new DocumentStore(join(root,'documents.sqlite'),fcl);roots.push(root);let clock='2026-10-08T12:00:00.000Z';
  const caseService=new CaseService(caseStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,credentialSecret:'synthetic-pdf-secret-32-bytes-long',credentialTtlDays:30,now:()=>clock,mail:{enabled:false}}),rateService=new NativeAdminService(rateStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=>clock});const submitted=await caseService.submitFclInquiry('fcl-pdf-probe-session','fcl-pdf-probe-submit-01',inquiry()),confirmed=caseService.confirmFclCase(receiver,submitted.case_id,{expected_version:1,expected_customer_supplement_ref:null,confirmed_fields:{changes:[]},reason:'Confirmed'},'fcl-pdf-probe-confirm-01');rateService.save(receiver,'fcl',{expected_version:0,input:rates()},'fcl-pdf-probe-rate-save-01');const preview=rateService.preview(receiver,'fcl'),published=rateService.publish(receiver,'fcl',{expected_version:1,preview_hash:preview.preview_hash,confirmation:'reviewed_sources_and_conditions'},'fcl-pdf-probe-rate-publish-01'),quoteService=new FclQuoteService({caseReader:caseService,rateReader:rateService,now:()=>clock}),workflow=new DocumentWorkflowService(new DocumentWorkflowStore(documentStore,fcl),new DocumentService(documentStore,portal),portal,renderer,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=>clock},{quoteService,caseReader:caseService,caseLock:caseService,rateLock:rateService,rateReader:rateService});
  workflow.saveFclConfig(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,expected_version:0,input:{issuer_name:'Issuer',issuer_address:'Address',issuer_phone:'',issuer_email:'',terms:'Terms',standard_fee_template_v1:null},confirmed:true},'fcl-pdf-probe-config-01');const quote=workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',case_ref:confirmed.case_id,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,selected_rate_id:(published.active_release!.input as FclRateDataset).rates[0]!.rate_id,expected_release_id:published.active_release!.release_id,expected_release_version:published.active_release!.version,expected_dataset_digest:published.active_release!.digest,input:quoteInput()},'fcl-pdf-probe-quote-01');const doc=workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',quote_ref:quote.quote_ref,expected_quote_version:quote.version,expected_quote_digest:quote.content_digest,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-PDF-PROBE',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-pdf-probe-doc-01');const review=workflow.reviewFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:doc.document_id,expected_version:1});workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:doc.document_id,expected_version:1,review_hash:review.review_hash,confirmed:true},'fcl-pdf-probe-approve-01');return {root,caseStore,rateStore,documentStore,workflow,doc,setClock:(value:string)=>{clock=value;}};
}
function closeProbe(f:Awaited<ReturnType<typeof probeFixture>>){f.documentStore.close();f.rateStore.close();f.caseStore.close();}

it('allows a cached formal PDF after the review credential window has expired',async()=>{
  const f=await probeFixture(()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));try{f.setClock('2026-10-08T12:11:00.000Z');const output=await f.workflow.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:f.doc.document_id,expected_version:2},'fcl-pdf-probe-expired-review-01');expect(output.valid_now).toBe(true);}finally{closeProbe(f);}
});

it('fails closed on an orphan PDF without a binding and never calls the renderer',async()=>{
  let renders=0;const f=await probeFixture(()=>{renders++;return Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120)));});try{const bytes=Buffer.from('%PDF-1.7\n'+'.'.repeat(120));f.documentStore.db.prepare('INSERT INTO document_pdfs VALUES(?,?,?,?)').run(f.doc.document_id,2,createHash('sha256').update(bytes).digest('hex'),bytes);await expect(f.workflow.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:f.doc.document_id,expected_version:2},'fcl-pdf-probe-orphan-01')).rejects.toThrow('document_readback_failed');expect(renders).toBe(0);}finally{closeProbe(f);}
});

it('rolls back the PDF artifact when its binding audit actor is altered',async()=>{
  const f=await probeFixture(()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));try{f.documentStore.db.exec("CREATE TRIGGER fcl_pdf_audit_tamper AFTER INSERT ON document_audit WHEN NEW.action='fcl-document-export' BEGIN UPDATE document_audit SET actor='tampered' WHERE id=NEW.id; END;");await expect(f.workflow.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:f.doc.document_id,expected_version:2},'fcl-pdf-probe-audit-01')).rejects.toThrow('document_readback_failed');expect(f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_pdfs').get()).toEqual({n:0});}finally{closeProbe(f);}
});

it('reuses the first committed bytes when two renderers race',async()=>{
  const resolvers:Array<(bytes:Buffer)=>void>=[],f=await probeFixture(()=>new Promise(resolve=>resolvers.push(resolve)));try{const request={contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal' as const,document_id:f.doc.document_id,expected_version:2};const first=f.workflow.exportFclDocument(receiver,request,'fcl-pdf-probe-race-first'),second=f.workflow.exportFclDocument(receiver,request,'fcl-pdf-probe-race-second');expect(resolvers).toHaveLength(2);const bytesA=Buffer.from('%PDF-1.7\nA'+'.'.repeat(120)),bytesB=Buffer.from('%PDF-1.7\nB'+'.'.repeat(120));resolvers[1]!(bytesB);const resultB=await second;resolvers[0]!(bytesA);const resultA=await first;expect(resultA.sha256).toBe(resultB.sha256);expect(Buffer.from(resultA.content_base64,'base64')).toEqual(bytesB);expect(f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_pdfs').get()).toEqual({n:1});}finally{closeProbe(f);}
});

it('rejects a modified signed PDF binding digest',async()=>{
  const f=await probeFixture(()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));try{await f.workflow.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal',document_id:f.doc.document_id,expected_version:2},'fcl-pdf-probe-binding-export');f.documentStore.db.prepare("UPDATE document_idempotency SET digest=? WHERE scope LIKE '%fcl-document-pdf-binding%'").run('a'.repeat(64));await expect(f.workflow.exportFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'history',document_id:f.doc.document_id,target_version:2,expected_current_version:2},'fcl-pdf-probe-binding-history')).rejects.toThrow('document_readback_failed');}finally{closeProbe(f);}
});

it('recovers a post-COMMIT transport failure without duplicating the PDF or audit',async()=>{
  const f=await probeFixture(()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));try{const db=f.caseStore.db as unknown as {exec:(sql:string)=>unknown},original=db.exec.bind(db);let commits=0;db.exec=(sql:string)=>{if(sql==='COMMIT'&&++commits===2)throw new Error('post_commit_transport');return original(sql);};const request={contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,mode:'formal' as const,document_id:f.doc.document_id,expected_version:2};await expect(f.workflow.exportFclDocument(receiver,request,'fcl-pdf-probe-postcommit-01')).rejects.toThrow('post_commit_transport');db.exec=original;const replay=await f.workflow.exportFclDocument(receiver,request,'fcl-pdf-probe-postcommit-01');expect(replay.replay.replayed).toBe(true);expect(f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_pdfs').get()).toEqual({n:1});expect(f.documentStore.db.prepare("SELECT COUNT(*) AS n FROM document_audit WHERE action='fcl-document-export'").get()).toEqual({n:1});}finally{closeProbe(f);}
});
