import {afterEach,describe,expect,it} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createFclInquiryDraft} from '../../apps/inquiry/fcl-model';
import {CaseService,CaseStore} from '../../services/access-gateway/portal/cases';
import {NativeAdminService,NativeAdminStore} from '../../services/access-gateway/portal/native-admin';
import type {PortalContext} from '../../services/access-gateway/portal/contracts';
import type {PortalService} from '../../services/access-gateway/portal/service';
import {DocumentService,DocumentStore} from '../../services/quote-documents/service';
import {DocumentWorkflowService,DocumentWorkflowStore} from '../../services/quote-documents/workflow';
import {FCL_DOCUMENT_WORKFLOW_VERSION} from '../../services/quote-documents/fcl-contracts';
import {FclQuoteService} from '../../services/quote-native/fcl';
import {FCL_RATE_DATASET_VERSION,type FclRateDataset} from '../../services/quote-native/fcl-contracts';

const roots:string[]=[];
afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
const receiverId='fcl-review-receiver';
const receiver:PortalContext={organizationId:null,identity:{userId:receiverId,displayName:'Reviewer',email:'reviewer@example.test',emailVerified:true,platformRole:null}};
const enterprise:PortalContext={organizationId:'org-review',identity:{...receiver.identity,userId:'enterprise-review'}};
const operator:PortalContext={organizationId:null,identity:{...receiver.identity,userId:'operator-review',platformRole:'operator'}};
const portal={getState:()=>({data:{current_organization:null,memberships:[]}})} as unknown as Pick<PortalService,'getState'>;
const fcl={fcl:{mode:'fresh_fixture',authorized:true,oldWritersStopped:true}} as const;

function rates(){return {contract_version:FCL_RATE_DATASET_VERSION,label:'FCL review rates',rates:[{rate_id:'00000000-0000-4000-8000-000000000201',supplier_label:'Carrier',pol:'Yantian',pod:'Vancouver',valid_from:'2026-10-01',valid_until:'2026-10-15',source_ref:'synthetic:review-rate',source_version:'v1',note:null,items:[{container_type:'40HQ' as const,ocean_freight:'3200',currency:'USD' as const}],additional_fees:[]}]};}
function inquiry(){return {...createFclInquiryDraft(),pol:'Yantian',pod:'Vancouver',cargo_name:'Synthetic cargo',containers:[{type:'40HQ' as const,quantity:2}],cargo_type:'general' as const,estimated_weight:{value:'18000',unit:'kg' as const},cargo_ready_date:'2026-10-08',incoterm:'EXW' as const,selected_services:['ocean_freight'] as const,contact:{name:'Synthetic Shipper',company:null,email:'shipper@example.test',phone:null},consent:true};}
function quoteInput(sell='3500'){return {source_sell_prices:[{row_key:'ocean_freight:40HQ',sell_price:sell,customer_note:'Ocean freight'}],manual_fees:[],service_scopes:[],exchange_rates:{USD:null,CAD:null},remark:null};}

async function setup(){
  const root=mkdtempSync(join(tmpdir(),'fcl-review-'));roots.push(root);
  const caseStore=new CaseStore(join(root,'cases.sqlite'),fcl),rateStore=new NativeAdminStore(join(root,'rates.sqlite'),fcl),documentStore=new DocumentStore(join(root,'documents.sqlite'),fcl);let clock='2026-10-08T12:00:00.000Z';
  const caseService=new CaseService(caseStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,credentialSecret:'synthetic-review-secret-32-bytes',credentialTtlDays:30,now:()=>clock,mail:{enabled:false}});
  const rateService=new NativeAdminService(rateStore,portal,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=>clock});
  const submitted=await caseService.submitFclInquiry('fcl-review-session-1','fcl-review-submit-0001',inquiry());const confirmed=caseService.confirmFclCase(receiver,submitted.case_id,{expected_version:1,expected_customer_supplement_ref:null,confirmed_fields:{changes:[]},reason:'Confirmed'},'fcl-review-confirm-0001');rateService.save(receiver,'fcl',{expected_version:0,input:rates()},'fcl-review-rate-save-0001');const preview=rateService.preview(receiver,'fcl');const published=rateService.publish(receiver,'fcl',{expected_version:1,preview_hash:preview.preview_hash,confirmation:'reviewed_sources_and_conditions'},'fcl-review-rate-publish-0001');
  const quoteService=new FclQuoteService({caseReader:caseService,rateReader:rateService,now:()=>clock});const documentWorkflowStore=new DocumentWorkflowStore(documentStore,fcl);
  const workflow=new DocumentWorkflowService(documentWorkflowStore,new DocumentService(documentStore,portal),portal,undefined,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=>clock},{quoteService,caseReader:caseService,caseLock:caseService,rateLock:rateService,rateReader:rateService});
  workflow.saveFclConfig(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,expected_version:0,input:{issuer_name:'Issuer',issuer_address:'Address',issuer_phone:'',issuer_email:'',terms:'Terms',standard_fee_template_v1:null},confirmed:true},'fcl-review-config-0001');
  const quote=workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',case_ref:confirmed.case_id,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,selected_rate_id:(published.active_release!.input as FclRateDataset).rates[0]!.rate_id,expected_release_id:published.active_release!.release_id,expected_release_version:published.active_release!.version,expected_dataset_digest:published.active_release!.digest,input:quoteInput()},'fcl-review-quote-0001');
  const doc=workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'create',quote_ref:quote.quote_ref,expected_quote_version:quote.version,expected_quote_digest:quote.content_digest,expected_case_version:confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-001',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-doc-0001');
  return {root,caseStore,rateStore,documentStore,workflow,caseService,rateService,quoteService,submitted,confirmed,published:published.active_release!,quote,doc,setClock:(value:string)=>{clock=value;}};
}

function workflowWithoutRate(f:Awaited<ReturnType<typeof setup>>){
  const noRateLock={withFclReadLock:()=>{throw new Error('rate_lock_forbidden');}};
  const noRateReader={get:()=>{throw new Error('rate_reader_forbidden');}};
  return new DocumentWorkflowService(new DocumentWorkflowStore(f.documentStore,{fcl:{mode:'reopen'}}),new DocumentService(f.documentStore,portal),portal,undefined,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'},{quoteService:f.quoteService,caseReader:f.caseService,caseLock:f.caseService,rateLock:noRateLock,rateReader:noRateReader});
}

function reviewRequest(f:Awaited<ReturnType<typeof setup>>){return {contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1};}
function approveRequest(hash:string,confirmed:true=true){return {contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:'',expected_version:1,review_hash:hash,confirmed};}

describe('FCL document review decisions',()=>{
  it('requires review then approved confirmation and records decision evidence',async()=>{
    const f=await setup();const review=f.workflow.reviewFclDocument(receiver,reviewRequest(f));expect(review.review_hash).toHaveLength(64);expect(review.quote.content_digest).toBe(f.quote.content_digest);
    expect(()=>f.workflow.approveFclDocument(receiver,{...approveRequest(review.review_hash),document_id:f.doc.document_id,confirmed:false as never},'fcl-review-approve-bad-01')).toThrow();
    expect(()=>f.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,review_hash:'f'.repeat(64),confirmed:true},'fcl-review-approve-fake-01')).toThrow('fcl_document_review_stale');
    const approved=f.workflow.approveFclDocument(receiver,{...approveRequest(review.review_hash),document_id:f.doc.document_id},'fcl-review-approve-0001');
    expect(approved).toMatchObject({state:'approved',version:2,decision:{kind:'approved',review_hash:review.review_hash,reviewed_at:'2026-10-08T12:00:00.000Z',review_expires_at:'2026-10-08T12:10:00.000Z',actor:receiverId}});
    expect(f.documentStore.db.prepare('SELECT state,review_hash,rejection_reason FROM document_revisions WHERE document_id=? AND version=2').get(f.doc.document_id)).toEqual({state:'approved',review_hash:review.review_hash,rejection_reason:null});
    f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('rejects, requires explicit resubmit, and supports explicit re_quote after an updated quote',async()=>{
    const f=await setup();const rejected=f.workflow.rejectFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,reason:'Customer condition needs correction'},'fcl-review-reject-0001');expect(rejected).toMatchObject({state:'rejected',version:2,decision:{kind:'rejected',reason:'Customer condition needs correction'}});
    expect(()=>f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'refresh',document_id:f.doc.document_id,expected_document_version:2,quote_ref:f.quote.quote_ref,expected_quote_version:1,expected_quote_digest:f.quote.content_digest,expected_case_version:f.confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-002',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-refresh-rejected-01')).toThrow('fcl_document_state_not_editable');
    const quote2=f.workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'update',quote_ref:f.quote.quote_ref,expected_version:1,source_binding:{mode:'retain'},input:quoteInput('3600')},'fcl-review-quote-0002');
    const resubmitted=f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'resubmit',document_id:f.doc.document_id,expected_document_version:2,quote_ref:quote2.quote_ref,expected_quote_version:2,expected_quote_digest:quote2.content_digest,expected_case_version:f.confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-002',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-resubmit-0001');expect(resubmitted).toMatchObject({state:'draft',version:3});
    const review=f.workflow.reviewFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:3});const approved=f.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:3,review_hash:review.review_hash,confirmed:true},'fcl-review-approve-0002');expect(approved.state).toBe('approved');
    expect(()=>f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'re_quote',document_id:f.doc.document_id,expected_document_version:4,quote_ref:quote2.quote_ref,expected_quote_version:2,expected_quote_digest:quote2.content_digest,expected_case_version:f.confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-003',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-requote-empty-01')).toThrow('fcl_document_re_quote_required');
    const quote3=f.workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'update',quote_ref:f.quote.quote_ref,expected_version:2,source_binding:{mode:'retain'},input:quoteInput('3700')},'fcl-review-quote-0003');const requoted=f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'re_quote',document_id:f.doc.document_id,expected_document_version:4,quote_ref:quote3.quote_ref,expected_quote_version:3,expected_quote_digest:quote3.content_digest,expected_case_version:f.confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-003',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-requote-0001');expect(requoted).toMatchObject({state:'draft',version:5});
    f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('invalidates review on Case/source/template changes and expires temporary credentials',async()=>{
    const caseChange=await setup();const caseReview=caseChange.workflow.reviewFclDocument(receiver,reviewRequest(caseChange));const caseView=caseChange.caseService.getFclCase(receiver,caseChange.confirmed.case_id);caseChange.caseService.updateFclCaseStatus(receiver,caseChange.confirmed.case_id,{expected_version:caseView.case_version,status:'needs_input',public_note:'Need input',internal_note:''},'fcl-review-case-change-01');expect(()=>caseChange.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:caseChange.doc.document_id,expected_version:1,review_hash:caseReview.review_hash,confirmed:true},'fcl-review-approve-stale-01')).toThrow('fcl_document_quote_not_current');caseChange.documentStore.close();caseChange.rateStore.close();caseChange.caseStore.close();

    const expired=await setup();const expiredReview=expired.workflow.reviewFclDocument(receiver,reviewRequest(expired));expired.setClock('2026-10-08T12:11:00.000Z');expect(()=>expired.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:expired.doc.document_id,expected_version:1,review_hash:expiredReview.review_hash,confirmed:true},'fcl-review-approve-expired-01')).toThrow('fcl_document_review_stale');expired.documentStore.close();expired.rateStore.close();expired.caseStore.close();
  });

  it('allows corrective reject without a usable Rate lock or active Rate',async()=>{
    const f=await setup();const result=workflowWithoutRate(f).rejectFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,reason:'Corrective rejection'},'fcl-review-reject-no-rate-01');expect(result.state).toBe('rejected');expect(JSON.stringify(f.caseService.getFclCase(receiver,f.confirmed.case_id).events)).not.toContain('Corrective rejection');f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('allows a rejected document to be resubmitted for display-only corrections on the same Quote',async()=>{
    const f=await setup();f.workflow.rejectFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,reason:'Fix quote number'},'fcl-review-reject-display-01');const resubmitted=f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'resubmit',document_id:f.doc.document_id,expected_document_version:2,quote_ref:f.quote.quote_ref,expected_quote_version:1,expected_quote_digest:f.quote.content_digest,expected_case_version:f.confirmed.case_version,expected_customer_supplement_ref:null,expected_config_version:1,quote_no:'FCL-REVIEW-CORRECTED',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:'Corrected display'},'fcl-review-resubmit-display-01');expect(resubmitted).toMatchObject({state:'draft',version:3,customer_input:{quote_no:'FCL-REVIEW-CORRECTED',remark:'Corrected display'}});f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('completes a real supplement, confirmation, quote replacement and resubmit before approval',async()=>{
    const f=await setup();f.workflow.rejectFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,reason:'Customer must update cargo'},'fcl-review-reject-real-flow-01');
    const caseBefore=await Promise.resolve(f.caseService.getFclCase(receiver,f.confirmed.case_id));f.caseService.updateFclCaseStatus(receiver,f.confirmed.case_id,{expected_version:caseBefore.case_version,status:'needs_input',public_note:'Please update cargo',internal_note:''},'fcl-review-real-flow-status-01');const needsInput=await Promise.resolve(f.caseService.getFclCase(receiver,f.confirmed.case_id));const supplemented=f.caseService.supplementFclCase(f.submitted.inquiry_id,f.submitted.credential,{expected_version:needsInput.case_version,fields:{changes:[{field:'cargo_name',value:'Updated synthetic cargo'}]},message:'Cargo name corrected'},'fcl-review-real-flow-supplement-01');const supplementedCase=await Promise.resolve(f.caseService.getFclCase(receiver,f.confirmed.case_id));f.caseService.confirmFclCase(receiver,f.confirmed.case_id,{expected_version:supplementedCase.case_version,expected_customer_supplement_ref:supplemented.events.at(-1)?.event_id??supplementedCase.review_context.latest_customer_supplement_ref,confirmed_fields:{changes:[]},reason:'Supplement confirmed'},'fcl-review-real-flow-confirm-01');const confirmedCase=await Promise.resolve(f.caseService.getFclCase(receiver,f.confirmed.case_id));
    const quote2=f.workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'update',quote_ref:f.quote.quote_ref,expected_version:1,source_binding:{mode:'replace',expected_case_version:confirmedCase.case_version,expected_customer_supplement_ref:confirmedCase.review_context.latest_customer_supplement_ref,selected_rate_id:(f.published.input as FclRateDataset).rates[0]!.rate_id,expected_release_id:f.published.release_id,expected_release_version:f.published.version,expected_dataset_digest:f.published.digest},input:quoteInput('3600')},'fcl-review-real-flow-quote-01');
    const resubmitted=f.workflow.saveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'resubmit',document_id:f.doc.document_id,expected_document_version:2,quote_ref:quote2.quote_ref,expected_quote_version:2,expected_quote_digest:quote2.content_digest,expected_case_version:confirmedCase.case_version,expected_customer_supplement_ref:confirmedCase.review_context.latest_customer_supplement_ref,expected_config_version:1,quote_no:'FCL-REVIEW-REAL',quote_date:'2026-10-08',valid_until:'2026-10-15',remark:null},'fcl-review-real-flow-resubmit-01');expect(resubmitted.state).toBe('draft');const review=f.workflow.reviewFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:3});expect(f.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:3,review_hash:review.review_hash,confirmed:true},'fcl-review-real-flow-approve-01').state).toBe('approved');f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('invalidates a review after real quote/template/rate changes but not unpublished rate drafts',async()=>{
    const quoteChange=await setup();const quoteReview=quoteChange.workflow.reviewFclDocument(receiver,reviewRequest(quoteChange));quoteChange.workflow.saveFclQuote(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,operation:'update',quote_ref:quoteChange.quote.quote_ref,expected_version:1,source_binding:{mode:'retain'},input:quoteInput('3600')},'fcl-review-quote-change-01');expect(()=>quoteChange.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:quoteChange.doc.document_id,expected_version:1,review_hash:quoteReview.review_hash,confirmed:true},'fcl-review-approve-quote-change')).toThrow('fcl_document_quote_not_current');quoteChange.documentStore.close();quoteChange.rateStore.close();quoteChange.caseStore.close();

    const templateChange=await setup();const templateReview=templateChange.workflow.reviewFclDocument(receiver,reviewRequest(templateChange));templateChange.workflow.saveFclConfig(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,expected_version:1,input:{issuer_name:'Changed',issuer_address:'Address',issuer_phone:'',issuer_email:'',terms:'Changed terms',standard_fee_template_v1:null},confirmed:true},'fcl-review-template-change-01');expect(()=>templateChange.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:templateChange.doc.document_id,expected_version:1,review_hash:templateReview.review_hash,confirmed:true},'fcl-review-approve-template-change')).toThrow('fcl_document_quote_not_current');templateChange.documentStore.close();templateChange.rateStore.close();templateChange.caseStore.close();

    const draftChange=await setup();const draftReview=draftChange.workflow.reviewFclDocument(receiver,reviewRequest(draftChange));const draft=rates();draft.rates[0]!.items[0]!.ocean_freight='3400';draftChange.rateService.save(receiver,'fcl',{expected_version:2,input:draft},'fcl-review-rate-draft-change');expect(draftChange.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:draftChange.doc.document_id,expected_version:1,review_hash:draftReview.review_hash,confirmed:true},'fcl-review-approve-draft-change')).toMatchObject({state:'approved'});draftChange.documentStore.close();draftChange.rateStore.close();draftChange.caseStore.close();

    const rateChange=await setup();const rateReview=rateChange.workflow.reviewFclDocument(receiver,reviewRequest(rateChange));const newRate=rates();newRate.rates[0]!.items[0]!.ocean_freight='3400';rateChange.rateService.save(receiver,'fcl',{expected_version:2,input:newRate},'fcl-review-rate-new-draft');const preview=rateChange.rateService.preview(receiver,'fcl');rateChange.rateService.publish(receiver,'fcl',{expected_version:3,preview_hash:preview.preview_hash,confirmation:'reviewed_sources_and_conditions'},'fcl-review-rate-publish-change');expect(()=>rateChange.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:rateChange.doc.document_id,expected_version:1,review_hash:rateReview.review_hash,confirmed:true},'fcl-review-approve-rate-change')).toThrow('fcl_document_quote_not_current');rateChange.documentStore.close();rateChange.rateStore.close();rateChange.caseStore.close();
  });

  it('expires exactly at the review boundary, loses credentials on restart and enforces idempotent decisions',async()=>{
    const exact=await setup();const exactReview=exact.workflow.reviewFclDocument(receiver,reviewRequest(exact));exact.setClock('2026-10-08T12:10:00.000Z');expect(()=>exact.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:exact.doc.document_id,expected_version:1,review_hash:exactReview.review_hash,confirmed:true},'fcl-review-expiry-boundary')).toThrow('fcl_document_review_stale');exact.documentStore.close();exact.rateStore.close();exact.caseStore.close();

    const restart=await setup();const restartReview=restart.workflow.reviewFclDocument(receiver,reviewRequest(restart));const restarted=new DocumentWorkflowService(new DocumentWorkflowStore(restart.documentStore,{fcl:{mode:'reopen'}}),new DocumentService(restart.documentStore,portal),portal,undefined,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'},{quoteService:restart.quoteService,caseReader:restart.caseService,caseLock:restart.caseService,rateLock:restart.rateService,rateReader:restart.rateService});expect(()=>restarted.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:restart.doc.document_id,expected_version:1,review_hash:restartReview.review_hash,confirmed:true},'fcl-review-restart-approve')).toThrow('fcl_document_review_stale');restart.documentStore.close();restart.rateStore.close();restart.caseStore.close();

    const idem=await setup();const idemReview=idem.workflow.reviewFclDocument(receiver,reviewRequest(idem));const approval={contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:idem.doc.document_id,expected_version:1,review_hash:idemReview.review_hash,confirmed:true as const};const approved=idem.workflow.approveFclDocument(receiver,approval,'fcl-review-idem-approve-01');const replay=idem.workflow.approveFclDocument(receiver,approval,'fcl-review-idem-approve-01');expect(replay).toMatchObject({version:approved.version,replay:{replayed:true,submitted_version:2,current:true}});expect(()=>idem.workflow.approveFclDocument(receiver,{...approval,document_id:idem.doc.document_id,review_hash:idemReview.review_hash,expected_version:2},'fcl-review-idem-approve-01')).toThrow('idempotency_conflict');expect(idem.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_revisions').get()).toEqual({n:2});idem.documentStore.close();idem.rateStore.close();idem.caseStore.close();
  });

  it('rejects enterprise/operator reviewers',async()=>{
    const f=await setup();expect(()=>f.workflow.reviewFclDocument(enterprise,reviewRequest(f))).toThrow('fcl_not_found');expect(()=>f.workflow.reviewFclDocument(operator,reviewRequest(f))).toThrow('fcl_not_found');f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('rolls back approval revision/current/event/audit/idempotency when decision payload is tampered',async()=>{
    const f=await setup();const review=f.workflow.reviewFclDocument(receiver,reviewRequest(f));f.documentStore.db.exec("CREATE TRIGGER fcl_review_decision_tamper AFTER INSERT ON document_idempotency BEGIN UPDATE document_revisions SET payload=json_set(payload,'$.decision.actor','tampered') WHERE state='approved'; END;");expect(()=>f.workflow.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,review_hash:review.review_hash,confirmed:true},'fcl-review-tamper-approve-01')).toThrow('fcl_document_readback_failed');expect(f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_revisions WHERE document_id=?').get(f.doc.document_id)).toEqual({n:1});expect(f.documentStore.db.prepare("SELECT COUNT(*) AS n FROM document_audit WHERE action='fcl-document-approve'").get()).toEqual({n:0});expect(f.documentStore.db.prepare("SELECT COUNT(*) AS n FROM document_idempotency WHERE scope LIKE '%\"fcl-document-approve\"%'").get()).toEqual({n:0});f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });

  it('rejects approve and reject on a read-only store without adding revisions',async()=>{
    const f=await setup(),before=f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_revisions').get();const readOnlyStore=DocumentWorkflowStore.openReadOnly(f.documentStore);const readOnlyService=new DocumentWorkflowService(readOnlyStore,new DocumentService(f.documentStore,portal),portal,undefined,{receiverUserId:receiverId,receiverIsActive:()=>true,now:()=> '2026-10-08T12:00:00.000Z'},{quoteService:f.quoteService,caseReader:f.caseService,caseLock:f.caseService,rateLock:f.rateService,rateReader:f.rateService});expect(()=>readOnlyService.approveFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,review_hash:'a'.repeat(64),confirmed:true},'fcl-review-readonly-approve-01')).toThrow('document_v3_rollback_read_only');expect(()=>readOnlyService.rejectFclDocument(receiver,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:f.doc.document_id,expected_version:1,reason:'No write'},'fcl-review-readonly-reject-01')).toThrow('document_v3_rollback_read_only');expect(f.documentStore.db.prepare('SELECT COUNT(*) AS n FROM document_revisions').get()).toEqual(before);f.documentStore.close();f.rateStore.close();f.caseStore.close();
  });
});
