import {describe,it,expect,afterEach} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DocumentService,DocumentStore} from '../../services/quote-documents/service';
import type {PortalContext} from '../../services/access-gateway/portal/contracts';
import type {PortalService} from '../../services/access-gateway/portal/service';
import {sample,template} from './fixtures';
const dirs:string[]=[];const stores:DocumentStore[]=[];
afterEach(()=>{stores.splice(0).forEach(s=>s.close());dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
const context=(user='owner',org='org'):PortalContext=>({identity:{userId:user,email:user+'@example.test',emailVerified:true,displayName:user,platformRole:null},organizationId:org});
function setup(){const dir=mkdtempSync(join(tmpdir(),'quote-docs-test-'));dirs.push(dir);const store=new DocumentStore(join(dir,'docs.sqlite'));stores.push(store);const portal={getState:(ctx:PortalContext)=>({data:{current_organization:{status:'active'},memberships:[{userId:ctx.identity.userId,organizationId:ctx.organizationId,status:'active',role:ctx.identity.userId==='owner'?'owner':'sales'}]}})} as unknown as Pick<PortalService,'getState'>;const svc=new DocumentService(store,portal,()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));return {svc,store};}
describe('documents permission and lifecycle',()=>{
 it('starts blank, needs preview and preserves snapshot after configuration changes',()=>{const {svc}=setup(),ctx=context();expect(svc.config(ctx).input).toBeNull();expect(()=>svc.preview(ctx,{input:sample()})).toThrow('document_template_missing');svc.saveConfig(ctx,{expected_version:0,input:template,confirmed:true},randomUUID());const p=svc.preview(ctx,{input:sample()});const input={input:p.input,template_version:p.template_version,preview_hash:p.preview_hash,preview_expires_at:p.preview_expires_at,confirmed:true};const key=randomUUID(),saved=svc.save(ctx,input,key);expect(svc.save(ctx,input,key).id).toBe(saved.id);expect(()=>svc.save(ctx,{...input,input:{...input.input,quote_no:'other'}},key)).toThrow();svc.saveConfig(ctx,{expected_version:1,input:{...template,company_name:'新公司'},confirmed:true},randomUUID());expect(svc.get(ctx,{id:saved.id}).template.company_name).toBe('测试物流');expect(()=>svc.save(ctx,input,randomUUID())).toThrow('document_preview_stale');});
 it('isolates actors and tenants, rejects sales approval and requires evidence',async()=>{const {svc}=setup(),ctx=context();svc.saveConfig(ctx,{expected_version:0,input:template,confirmed:true},randomUUID());const p=svc.preview(ctx,{input:sample()});const s=svc.save(ctx,{...p,confirmed:true},randomUUID());expect(()=>svc.get(context('sales'),{id:s.id})).toThrow('document_not_found');expect(()=>svc.get(context('owner','another'),{id:s.id})).toThrow('document_not_found');const approval={id:s.id,expected_version:1,evidence_ref:'manual:QA',evidence_version:'1',review_notes:'逐项核对',confirmation:'human_verified_price_and_source'};expect(()=>svc.approve(context('sales'),approval,randomUUID())).toThrow();const approved=svc.approve(ctx,approval,randomUUID());expect(approved.state).toBe('approved');const pdf=await svc.export(ctx,{id:s.id});expect(pdf.sha256).toHaveLength(64);expect(pdf.draft).toBe(false);});
 it('rejects expired approval and corrupt stored PDF',async()=>{const {svc,store}=setup(),ctx=context();svc.saveConfig(ctx,{expected_version:0,input:template,confirmed:true},randomUUID());const p=svc.preview(ctx,{input:{...sample(),quote_date:'2020-01-01',valid_until:'2020-01-02'}});const s=svc.save(ctx,{...p,confirmed:true},randomUUID());expect(()=>svc.approve(ctx,{id:s.id,expected_version:1,evidence_ref:'manual:QA',evidence_version:'1',review_notes:'核对',confirmation:'human_verified_price_and_source'},randomUUID())).toThrow('document_expired');expect((await svc.export(ctx,{id:s.id})).draft).toBe(true);store.db.prepare("UPDATE document_pdfs SET bytes=?").run(Buffer.from('broken'));await expect(svc.export(ctx,{id:s.id})).rejects.toThrow('document_pdf_invalid');});
});
describe('preview and export failure closure',()=>{
 it('rejects preview replay by another actor and expired preview',()=>{const {svc}=setup(),ctx=context();svc.saveConfig(ctx,{expected_version:0,input:template,confirmed:true},randomUUID());const p=svc.preview(ctx,{input:sample()});expect(()=>svc.save(context('sales'),{...p,confirmed:true},randomUUID())).toThrow('document_preview_stale');expect(()=>svc.save(ctx,{...p,preview_expires_at:Date.now()-1,confirmed:true},randomUUID())).toThrow('document_preview_stale');});
 it('rejects non-manager template mutation and version conflict',()=>{const {svc}=setup(),input={expected_version:0,input:template,confirmed:true};expect(()=>svc.saveConfig(context('sales'),input,randomUUID())).toThrow('document_management_denied');svc.saveConfig(context(),input,randomUUID());expect(()=>svc.saveConfig(context(),input,randomUUID())).toThrow('version_conflict');});
 it('preserves the original draft PDF when approval creates a new version',async()=>{const {svc,store}=setup(),ctx=context();svc.saveConfig(ctx,{expected_version:0,input:template,confirmed:true},randomUUID());const p=svc.preview(ctx,{input:sample()}),d=svc.save(ctx,{...p,confirmed:true},randomUUID());expect((await svc.export(ctx,{id:d.id})).draft).toBe(true);svc.approve(ctx,{id:d.id,expected_version:1,evidence_ref:'manual:qa',evidence_version:'1',review_notes:'核对',confirmation:'human_verified_price_and_source'},randomUUID());expect((await svc.export(ctx,{id:d.id})).version).toBe(2);expect((store.db.prepare('SELECT COUNT(*) AS n FROM document_pdfs').get() as {n:number}).n).toBe(2);});
});
