import {afterEach,expect,it} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CaseService,CaseStore} from '../../services/access-gateway/portal/cases';
import type {PortalContext} from '../../services/access-gateway/portal/contracts';
import type {PortalBusinessService} from '../../services/access-gateway/portal/business/service';
import type {PortalService} from '../../services/access-gateway/portal/service';
import {DocumentService,DocumentStore} from '../../services/quote-documents/service';
import {DocumentWorkflowService,DocumentWorkflowStore} from '../../services/quote-documents/workflow';
import {WORKFLOW_REQUEST_VERSION} from '../../services/quote-documents/workflow-contracts';
import {createNativeQuoteClient,type QuoteRelease} from '../../services/quote-native/client';
import {createDraft} from '../../apps/inquiry/model';
import {config as rates,request as quoteRequest} from '../quote-native/fixture';
import {template} from './fixtures';

const dirs:string[]=[];
afterEach(()=>dirs.splice(0).forEach(dir=>rmSync(dir,{recursive:true,force:true})));

it('keeps linked case identity immutable, rechecks customer supplements and exports only after approval',async()=>{
  const root=mkdtempSync(join(tmpdir(),'workflow-linked-test-'));dirs.push(root);
  const organization='org-linked',owner='owner-linked';
  const portal={getState:(context:PortalContext)=>({data:{current_organization:context.organizationId?{organizationId:organization,status:'active'}:null,memberships:context.organizationId===organization?[{organizationId:organization,userId:context.identity.userId,status:'active',role:'owner'}]:[]}})} as unknown as Pick<PortalService,'getState'>;
  const documentStore=new DocumentStore(join(root,'documents.sqlite')),caseStore=new CaseStore(join(root,'cases.sqlite'));
  const release:QuoteRelease={version:1,release_id:'release-linked',digest:'a'.repeat(64),input:rates,published_at:new Date().toISOString()};
  const client=createNativeQuoteClient(()=>release);
  const business={execute:async(_ctx:PortalContext,_tool:string,input:unknown,requestId:string)=>client.preview({input,requestId,actor:{type:'user',id:owner}})} as unknown as Pick<PortalBusinessService,'execute'>;
  const caseService=new CaseService(caseStore,portal);
  const caseAccess={readForQuoteView:(ctx:PortalContext,caseRef:string)=>caseService.readForQuoteView(ctx,caseRef),readForQuoteLink:(ctx:PortalContext,caseRef:string)=>caseService.readForQuoteLink(ctx,caseRef)};
  const documentService=new DocumentService(documentStore,portal,()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))),{business,current:()=>release},caseAccess);
  const workflow=new DocumentWorkflowService(new DocumentWorkflowStore(documentStore,{oldWritersStopped:true}),documentService,portal,()=>Promise.resolve(Buffer.from('%PDF-1.7\n'+'.'.repeat(120))));
  const ctx:PortalContext={identity:{userId:owner,email:'owner@example.test',emailVerified:true,displayName:'Owner',platformRole:null},organizationId:organization};
  workflow.saveConfig(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,expected_version:0,input:{...template,standard_fee_template_v1:{template_id:'freightclaw-standard-v1',template_version:1,items:[]}},confirmed:true},'workflow-linked-config-01');
  const createdCase=caseService.create(ctx,{...createDraft(),services:['ocean'],transportMode:'fcl',origin:'Shanghai',destination:'Toronto M5X 1A9',product:'Synthetic linked cargo',containerType:'40HQ',containerCount:'1',contactName:'Synthetic owner',email:'contact@example.test',consent:true},'workflow-linked-case-01');
  const addSupplement=(label:string)=>{
    const current=caseService.get(ctx,createdCase.case_id);
    caseService.update(ctx,createdCase.case_id,{expected_version:current.version,status:'needs_input',public_note:label,internal_note:''},`workflow-linked-update-${label}`);
    const updated=caseService.get(ctx,createdCase.case_id);
    caseService.reply(ctx,createdCase.case_id,{expected_version:updated.version,message:`Supplement ${label}`},`workflow-linked-reply-${label}`);
  };
  const prepare=()=>{
    const current=caseService.readForQuoteLink(ctx,createdCase.case_id);
    return workflow.prepareNative(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,document_kind:'linked',case_ref:createdCase.case_id,expected_customer_event_ref:current.latest_customer_supplement_ref,request:quoteRequest,customer:{quote_no:'QA-LINKED-V3',customer_name:'Synthetic owner',quote_date:new Date().toISOString().slice(0,10),valid_until:rates.valid_until,job_no:'',so_no:'',container_no:'',remark:''}});
  };
  const prepared=await prepare();
  const saved=workflow.save(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,operation:'create',document_kind:'linked',input:prepared.input,template_selection:{mode:'current'},native_quote_v1:prepared.native_quote_v1,inquiry_case_link_v1:prepared.inquiry_case_link_v1!,preview_hash:prepared.preview_hash,preview_expires_at:prepared.preview_expires_at,save_intent:'save_draft'},'workflow-linked-save-01');
  expect(saved).toMatchObject({document_kind:'linked',version:1,inquiry_case_link_v1:prepared.inquiry_case_link_v1});
  addSupplement('after-preview');
  expect(()=>workflow.save(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,operation:'update',document_kind:'linked',id:saved.id,expected_version:1,input:prepared.input,template_selection:{mode:'retain'},binding_update:{mode:'retain'},save_intent:'save_draft'},'workflow-linked-stale-01')).toThrow('inquiry_quote_case_review_required');
  const replacement=await prepare();
  const updated=workflow.save(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,operation:'update',document_kind:'linked',id:saved.id,expected_version:1,input:replacement.input,template_selection:{mode:'retain'},binding_update:{mode:'replace',native_quote_v1:replacement.native_quote_v1,inquiry_case_link_v1:replacement.inquiry_case_link_v1!,preview_hash:replacement.preview_hash,preview_expires_at:replacement.preview_expires_at},save_intent:'save_draft'},'workflow-linked-replace-01');
  expect(updated).toMatchObject({id:saved.id,version:2,inquiry_case_link_v1:replacement.inquiry_case_link_v1});
  const review=workflow.review(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,expected_version:2});
  if(review.status!=='success')throw new Error('linked review unexpectedly requires input');
  addSupplement('after-review');
  expect(()=>workflow.approve(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,expected_version:2,review_hash:review.review_hash,evidence_ref:'review:linked-v3',evidence_version:'1',review_notes:'核验',confirmation:'human_verified_price_and_source'},'workflow-linked-approve-stale')).toThrow('inquiry_quote_case_review_required');
  const latest=caseService.readForQuoteLink(ctx,createdCase.case_id);
  const replacement2=await workflow.prepareNative(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,document_kind:'linked',case_ref:createdCase.case_id,expected_customer_event_ref:latest.latest_customer_supplement_ref,request:quoteRequest,customer:{quote_no:'QA-LINKED-V3',customer_name:'Synthetic owner',quote_date:new Date().toISOString().slice(0,10),valid_until:rates.valid_until,job_no:'',so_no:'',container_no:'',remark:''}});
  const updated2=workflow.save(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,operation:'update',document_kind:'linked',id:saved.id,expected_version:2,input:replacement2.input,template_selection:{mode:'retain'},binding_update:{mode:'replace',native_quote_v1:replacement2.native_quote_v1,inquiry_case_link_v1:replacement2.inquiry_case_link_v1!,preview_hash:replacement2.preview_hash,preview_expires_at:replacement2.preview_expires_at},save_intent:'save_draft'},'workflow-linked-replace-02');
  const finalReview=workflow.review(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,expected_version:updated2.version});
  if(finalReview.status!=='success')throw new Error('linked review unexpectedly requires input');
  await expect(workflow.export(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,mode:'draft',expected_version:updated2.version})).rejects.toThrow('document_export_mode_invalid');
  const approved=workflow.approve(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,expected_version:updated2.version,review_hash:finalReview.review_hash,evidence_ref:'review:linked-v3',evidence_version:'1',review_notes:'核验',confirmation:'human_verified_price_and_source'},'workflow-linked-approve-01');
  expect(approved).toMatchObject({state:'approved',document_kind:'linked'});
  const exported=await workflow.export(ctx,{contract_version:WORKFLOW_REQUEST_VERSION,id:saved.id,mode:'formal',expected_version:approved.version});
  expect(exported).toMatchObject({mode:'formal',historical:false,valid_now:true});
  documentStore.close();
  caseStore.close();
});
