export const fixtureSnapshot = {
  schema_version: "2026-08-11.v1",
  tenant: {
    id: "tenant_demo",
    name: "北美跨境物流测试租户",
  },
  environment: "fixture",
  config: {
    current_version: "cfg-2026-08-11.2",
    draft_version: "cfg-2026-08-12-draft",
    last_published_at: "2026-08-11 17:20",
  },
  actor: {
    id: "actor_admin_demo",
    name: "演示管理员",
    role: "admin",
  },
  health: {
    healthz: {
      status: "ready",
      value: "服务在线",
      detail: "只说明进程存活，不代表下游数据可用。",
      endpoint: "/healthz",
    },
    readyz: {
      status: "blocked",
      value: "未满足发布门槛",
      detail: "正式依赖、租户映射和适配器仍待核验。",
      endpoint: "/readyz",
    },
  },
  blockers: [
    "生产模式缺少已验证的身份校验、租户映射和适配器来源。",
    "RiskCustoms ready=false，不能把演示数据当成正式关务结果。",
    "发布需要正式后台的校验、审批、写后读回接口；本原型未连接。",
  ],
  clients: [
    {
      name: "ChatGPT",
      client_id: "client_chatgpt_demo",
      issuer: "https://id.example.invalid/issuer",
      audience: "mcp-gateway",
      allowed_origins: ["https://chatgpt.example.invalid"],
      check: {
        status: "ready",
        checked_at: "2026-08-12 09:24",
        detail: "issuer、audience、来源地址已通过演示校验。",
      },
    },
    {
      name: "Codex",
      client_id: "client_codex_demo",
      issuer: "https://id.example.invalid/issuer",
      audience: "mcp-gateway",
      allowed_origins: ["https://codex.example.invalid"],
      check: {
        status: "manual_review",
        checked_at: "2026-08-12 09:18",
        detail: "需确认项目级租户绑定，再进入正式发布。",
      },
    },
    {
      name: "企业助手",
      client_id: "client_enterprise_demo",
      issuer: "https://id.example.invalid/issuer",
      audience: "mcp-gateway",
      allowed_origins: [],
      check: {
        status: "blocked",
        checked_at: "2026-08-12 09:03",
        detail: "未登记允许来源；不会静默放行。",
      },
    },
  ],
  roles: [
    { key: "admin", label: "管理员", description: "管理平台配置、授权和审计。" },
    { key: "sales", label: "销售", description: "补询价字段、试算并保存报价草稿。" },
    { key: "operator", label: "运营", description: "核对货物、状态、装柜摘要和复核任务。" },
    { key: "customs_reviewer", label: "关务审核", description: "审核 HS 候选、税率和措施风险。" },
    { key: "finance", label: "财务", description: "查看计费口径、版本和税费估算。" },
    { key: "viewer", label: "查看者", description: "查看已授权的结构化结果。" },
    { key: "service", label: "后台服务", description: "用最小权限执行确定性工具。" },
  ],
  tools: [
    {
      name: "knowledge.search_curated",
      label: "精选知识搜索",
      description: "只搜当前精选的 SOP、规则说明和模板。",
      permission: "knowledge:read",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "system.get_data_status",
      label: "查询数据状态",
      description: "读取现有系统的版本和就绪原因。",
      permission: "system:read",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "cargo.calculate",
      label: "货物确定性计算",
      description: "计算 CBM、体积重、分泡和计费重。",
      permission: "quote:calculate",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "container.plan_summary",
      label: "装柜摘要计算",
      description: "区分物理容量、运营目标和超限提醒。",
      permission: "container:calculate",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "quote.canada_final_mile.calculate",
      label: "加拿大尾程试算",
      description: "按已版本化规则读取现有报价系统并试算。",
      permission: "quote:calculate",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "customs.ca.search",
      label: "加拿大关务候选",
      description: "读取 RiskCustoms 的 HS 候选和缺失问题。",
      permission: "tariff:read",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "customs.ca.estimate",
      label: "加拿大税费估算",
      description: "按已发布版本形成带确认边界的估算。",
      permission: "tariff:estimate",
      kind: "read",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance", "viewer", "service"],
    },
    {
      name: "quote.save_draft",
      label: "保存报价草稿",
      description: "只允许保存现有报价系统的不可发送草稿。",
      permission: "quote:draft_write",
      kind: "write",
      roles: ["admin", "sales", "operator"],
    },
    {
      name: "review.create_task",
      label: "创建人工复核",
      description: "只创建人工复核任务，并要求写后读回。",
      permission: "review:create_task",
      kind: "write",
      roles: ["admin", "sales", "operator", "customs_reviewer", "finance"],
    },
  ],
  sources: [
    {
      name: "Quote Engine",
      label: "现有报价引擎",
      type: "报价适配器",
      endpoint_ref: "endpoint_ref:quote-engine/v1",
      secret_ref: "secret_ref:quote-engine",
      source_version: "quote-2026-08-11",
      readiness: "manual_review",
      reason: "端点、租户映射和草稿写后读回待适配验证。",
    },
    {
      name: "RiskCustoms",
      label: "RiskCustoms 关务",
      type: "关务适配器",
      endpoint_ref: "endpoint_ref:riskcustoms/status",
      secret_ref: "secret_ref:riskcustoms",
      source_version: "release-pending",
      readiness: "unavailable",
      reason: "ready=false；没有可用于正式查询的已发布快照。",
    },
    {
      name: "knowledge",
      label: "精选知识",
      type: "知识适配器",
      endpoint_ref: "endpoint_ref:knowledge/curated",
      secret_ref: "secret_ref:knowledge",
      source_version: "knowledge-2026-08-11",
      readiness: "ready",
      reason: "精选索引和版本引用已绑定。",
    },
    {
      name: "status",
      label: "系统状态",
      type: "状态适配器",
      endpoint_ref: "endpoint_ref:system/status",
      secret_ref: "secret_ref:status",
      source_version: "status-contract-v1",
      readiness: "ready",
      reason: "只读状态入口可展示，写操作仍需正式门禁。",
    },
    {
      name: "review",
      label: "人工复核任务",
      type: "复核适配器",
      endpoint_ref: "endpoint_ref:review/tasks",
      secret_ref: "secret_ref:review",
      source_version: "review-contract-pending",
      readiness: "unavailable",
      reason: "正式任务系统尚未接入；演示只显示计划状态。",
    },
  ],
  approvals: {
    draft: {
      version: "cfg-2026-08-12-draft",
      created_at: "2026-08-12 09:28",
      owner: "actor_admin_demo",
      persistence: "仅浏览器本地预览，未持久化",
    },
    validation: {
      status: "manual_review",
      summary: "发现 2 项需要人工确认，不能直接发布。",
    },
    changes: [
      { path: "adapters.RiskCustoms.readiness", before: "ready=false", after: "unavailable", status: "ready" },
      { path: "clients.client_codex_demo.tenant_binding", before: "未确认", after: "待核验", status: "manual_review" },
      { path: "release.external_publish", before: "允许配置", after: "Phase 1 禁止", status: "blocked" },
    ],
    chain: [
      { label: "字段和 Schema 校验", status: "ready", detail: "结构化字段完整。" },
      { label: "适配器来源核验", status: "manual_review", detail: "需要责任人确认端点、版本和租户边界。" },
      { label: "管理员审批", status: "blocked", detail: "未连接正式审批接口。" },
      { label: "发布后读回", status: "blocked", detail: "正式发布接口未提供。" },
    ],
  },
  audit: [
    {
      actor: "actor_admin_demo",
      tenant: "tenant_demo",
      action: "config.preview",
      result: "success",
      reason: "生成本地草稿差异",
      config_version: "cfg-2026-08-12-draft",
      trace_id: "trace_demo_01",
    },
    {
      actor: "actor_ops_demo",
      tenant: "tenant_demo",
      action: "adapter.readiness.check",
      result: "manual_review",
      reason: "来源版本待确认",
      config_version: "cfg-2026-08-11.2",
      trace_id: "trace_demo_02",
    },
    {
      actor: "actor_admin_demo",
      tenant: "tenant_demo",
      action: "release.commit",
      result: "blocked",
      reason: "fixture 模式禁止发布",
      config_version: "cfg-2026-08-12-draft",
      trace_id: "trace_demo_03",
    },
  ],
  status_legend: [
    { key: "loading", label: "加载中", detail: "正在读取快照。" },
    { key: "empty", label: "暂无记录", detail: "没有可展示内容，不代表可以自动补数据。" },
    { key: "error", label: "加载失败", detail: "请求或数据格式有问题，需要重试或联系管理员。" },
    { key: "unavailable", label: "不可用", detail: "权威源或适配器当前不能使用。" },
    { key: "blocked", label: "已阻断", detail: "权限、阶段或安全门禁禁止继续。" },
    { key: "manual_review", label: "人工复核", detail: "有冲突或高风险，需要人员确认。" },
    { key: "ready", label: "已就绪", detail: "当前检查项通过，不代表可以发布业务数据。" },
  ],
};
