import {randomUUID} from 'node:crypto';
import type {z} from 'zod';
import {PortalError,type PortalContext} from './contracts';
import {executionDigest,type FclExecutionService} from './fcl-execution';
import type {FclExecutionMailService} from './fcl-execution-mail';
import type {DocumentWorkflowService} from '../../quote-documents/workflow';
import {FCL_DOCUMENT_WORKFLOW_VERSION} from '../../quote-documents/fcl-contracts';
import {FCL_EXECUTION_VERSION} from './fcl-execution-contracts';
import {customerClaimSchema,customerConfirmSchema,customerPublishSchema,customerOfferSchema,customerCaseSchema,customerListSchema,type CustomerAction} from './fcl-customer-contracts';

type Event={event_id:string;actor_id:string;created_at:string;payload_json:string;message:string};
type Offer=z.infer<typeof customerOfferSchema>&{handoff:z.infer<typeof customerPublishSchema>['handoff']};
export class FclCustomerService{
 constructor(readonly execution:FclExecutionService,readonly workflow:DocumentWorkflowService,readonly mail:FclExecutionMailService){}
 private get db(){return this.execution.cases.store.db;}
 private actor(ctx:PortalContext){if(!ctx.identity.emailVerified||!ctx.identity.userId)throw new PortalError('authentication_required');return ctx.identity.userId;}
 private row(id:string){const r=this.db.prepare('SELECT c.owner_id,c.version,c.status,c.input_json,i.inquiry_no FROM business_cases c JOIN fcl_inquiries i ON i.case_id=c.case_id WHERE c.case_id=? AND c.organization_id IS NULL').get(id) as {owner_id:string;version:number;status:string;input_json:string;inquiry_no:string}|undefined;if(!r)throw new PortalError('fcl_not_found');return r;}
 private event(id:string,kind:string){return this.db.prepare('SELECT event_id,actor_id,created_at,payload_json,message FROM business_case_events WHERE case_id=? AND event_kind=? ORDER BY rowid DESC LIMIT 1').get(id,`portal_${kind}`) as Event|undefined;}
 private claimed(ctx:PortalContext,id:string){const claim=this.event(id,'claim');if(!claim||claim.actor_id!==this.actor(ctx))throw new PortalError('fcl_not_found');return claim;}
 private owner(ctx:PortalContext,id:string){this.execution.cases.getFclCase(ctx,id);}
 private offer(id:string):Offer|null{const e=this.event(id,'offer');return e?JSON.parse(e.payload_json) as Offer:null;}
 private current(id:string,offer:Offer){const row=this.row(id);if(['closed','cancelled'].includes(row.status)||row.version!==offer.handoff.expected_case_version||!this.workflow.isFclOfferCurrent(row.owner_id,offer.handoff))throw new PortalError('fcl_customer_quote_changed');}
 private write(ctx:PortalContext,id:string,kind:string,payload:unknown,message:string){const row=this.row(id),eventId=randomUUID(),at=this.execution.now();this.db.prepare('INSERT INTO business_case_events(event_id,case_id,version,status,message,visibility,actor_label,created_at,actor_id,event_kind,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(eventId,id,row.version,row.status,message,'customer',ctx.identity.displayName,at,this.actor(ctx),`portal_${kind}`,JSON.stringify(payload));return {eventId,at};}
 private transaction<T>(ctx:PortalContext,id:string,kind:string,input:unknown,key:string,write:()=>void,read:()=>T){
  if(!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('idempotency_key_invalid');
  const scope=JSON.stringify(['personal-customer',this.actor(ctx),kind]),digest=executionDigest(input);this.db.exec('BEGIN IMMEDIATE');
  try{const prior=this.db.prepare('SELECT digest,case_id FROM business_case_idempotency WHERE scope=? AND key=?').get(scope,key) as {digest:string;case_id:string}|undefined;
   if(prior){if(prior.digest!==digest||prior.case_id!==id)throw new PortalError('idempotency_conflict');}else{write();this.db.prepare('INSERT INTO business_case_idempotency VALUES(?,?,?,?)').run(scope,key,digest,id);}const result=read();this.db.exec('COMMIT');return result;
  }catch(e){this.db.exec('ROLLBACK');throw e;}
 }
 claim(ctx:PortalContext,input:unknown,key:string){const r=customerClaimSchema.parse(input);this.actor(ctx);const view=this.execution.cases.getFclCustomerView(r.inquiry_id,r.credential);const row=this.db.prepare('SELECT case_id,original_payload_json FROM fcl_inquiries WHERE fcl_inquiry_id=?').get(r.inquiry_id) as {case_id:string;original_payload_json:string};
  const original=JSON.parse(row.original_payload_json) as {contact:{email:string}};if(original.contact.email.toLowerCase()!==ctx.identity.email.toLowerCase())throw new PortalError('fcl_not_found');void view;
  return this.transaction(ctx,row.case_id,'claim',{inquiry_id:r.inquiry_id},key,()=>{const old=this.event(row.case_id,'claim');if(old&&old.actor_id!==ctx.identity.userId)throw new PortalError('fcl_not_found');if(!old){const e=this.write(ctx,row.case_id,'claim',{customer_id:ctx.identity.userId,email:ctx.identity.email},'已关联本人询价');this.mail.enqueueCustomerNotice(row.case_id,e.eventId,'progress','询价已收到，运营将在核对需求后为您报价。');}},()=>this.get(ctx,{case_ref:row.case_id}));
 }
 list(ctx:PortalContext,input:unknown){const r=customerListSchema.parse(input),actor=this.actor(ctx);const rows=this.db.prepare("SELECT rowid,case_id FROM business_case_events WHERE event_kind='portal_claim' AND actor_id=? AND rowid<? ORDER BY rowid DESC LIMIT ?").all(actor,r.before??Number.MAX_SAFE_INTEGER,r.limit+1) as {rowid:number;case_id:string}[];return {items:rows.slice(0,r.limit).map(row=>this.get(ctx,{case_ref:row.case_id})),next_before:rows.length>r.limit?rows[r.limit-1]!.rowid:null};}
 get(ctx:PortalContext,input:{case_ref:string}){this.claimed(ctx,input.case_ref);return this.project(input.case_ref);}
 private project(id:string){const row=this.row(id),offer=this.offer(id),confirmation=this.event(id,'confirm'),execution=this.execution.readForDispatch(id);const confirmed=confirmation&&offer&&(JSON.parse(confirmation.payload_json) as {offer_id:string}).offer_id===offer.offer_id;
  const events=this.db.prepare("SELECT message,created_at FROM business_case_events WHERE case_id=? AND event_kind LIKE 'portal_%' ORDER BY rowid DESC LIMIT 5000").all(id) as {message:string;created_at:string}[];
  return customerCaseSchema.parse({case_ref:id,inquiry_no:row.inquiry_no,state:['closed','cancelled'].includes(row.status)?'ended':execution?.state??(confirmed?'awaiting_acceptance':offer?'awaiting_customer':'inquiry'),offer:offer?customerOfferSchema.parse(Object.fromEntries(Object.entries(offer).filter(([k])=>k!=='handoff'))):null,events:[...events.map(e=>({message:e.message,at:e.created_at})),...(execution?.history.filter(e=>['node_start','node_complete','node_exception','node_return'].includes(e.action)).map(e=>({message:`${e.node_id?({booking:'订舱',pickup:'提货',export_customs:'出口报关',shipping_documents:'运输文件',canada_customs:'加拿大清关',devanning_storage:'拆柜入仓',delivery:'提柜派送'}[e.node_id]):'业务'}：${e.action==='node_complete'?'已完成':e.action==='node_start'?'处理中':e.action==='node_return'?'待补资料':'异常处理中'}`,at:e.created_at}))??[])].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,5000),nodes:execution?.nodes.map(n=>({id:n.node_id,status:n.status,completed_at:n.completed_at}))??[]});
 }
 publish(ctx:PortalContext,input:unknown,key:string){const r=customerPublishSchema.parse(input),id=r.handoff.case_ref;this.owner(ctx,id);if(!this.event(id,'claim'))throw new PortalError('fcl_customer_claim_required');if(this.execution.readForDispatch(id))throw new PortalError('fcl_execution_already_exists_use_amend');
  this.workflow.getFclHandoff(ctx,{contract_version:r.handoff.contract_version,case_ref:id});
  // Reuse the formal handoff validator without creating execution or acceptance.
  this.workflow.previewFclExecution(ctx,{contract_version:FCL_EXECUTION_VERSION,handoff:r.handoff,confirmation:{method:'in_person',confirmed_at:this.execution.now(),contact_name:ctx.identity.displayName,note:'报价发布校验，未登记客户确认',evidence_refs:[]},coordinator_id:ctx.identity.userId,expected_config_version:this.execution.configuration(ctx).version,confirmed:true},this.execution);
  const doc=this.workflow.getFclDocument(ctx,{contract_version:FCL_DOCUMENT_WORKFLOW_VERSION,document_id:r.handoff.document_id,version:r.handoff.expected_document_version});
  return this.transaction(ctx,id,'offer',r,key,()=>{const previous=this.offer(id);if(previous?.handoff.document_id===r.handoff.document_id&&previous.handoff.expected_document_version===r.handoff.expected_document_version&&previous.handoff.expected_pdf_sha256===r.handoff.expected_pdf_sha256)return;const offer:Offer={offer_id:randomUUID(),document_version:doc.version,document:{...doc.customer_input,fee_items:doc.customer_input.fee_items.map(f=>({...f,source_kind:'manual' as const,template_ref:null}))},scope:doc.customer_scope.map(({included_row_refs:_refs,...item})=>{void _refs;return item;}),issuer:doc.template,totals:doc.customer_totals,published_at:this.execution.now(),handoff:r.handoff};const event=this.write(ctx,id,'offer',offer,'报价已发布，请确认');this.mail.enqueueCustomerNotice(id,event.eventId,'quote',`报价已发布。\n金额：${Object.entries(offer.totals.by_currency).filter(([,v])=>!/^0(?:\.0+)?$/.test(v)).map(([c,v])=>`${v} ${c}`).join('；')}\n有效期至：${offer.document.valid_until}\n请登录核对费用和服务范围，确认后提交委托。`,offer.offer_id);},()=>this.project(id).offer!);
 }
 confirm(ctx:PortalContext,input:unknown,key:string){const r=customerConfirmSchema.parse(input);this.claimed(ctx,r.case_ref);return this.transaction(ctx,r.case_ref,'confirm',r,key,()=>{const offer=this.offer(r.case_ref);if(!offer||offer.offer_id!==r.offer_id)throw new PortalError('fcl_customer_quote_changed');this.current(r.case_ref,offer);const old=this.event(r.case_ref,'confirm');if(old&&(JSON.parse(old.payload_json) as {offer_id:string}).offer_id===r.offer_id)return;const e=this.write(ctx,r.case_ref,'confirm',{offer_id:r.offer_id,customer_id:ctx.identity.userId,contact_name:ctx.identity.displayName},'客户已确认，等待运营接单');this.mail.enqueueCustomerNotice(r.case_ref,e.eventId,'confirmed','您的委托已提交，等待运营接单。',r.offer_id);const row=this.row(r.case_ref);this.mail.enqueueCaseEvent({event_id:e.eventId,case_ref:r.case_ref,owner_id:row.owner_id,case_version:row.version,kind:'fcl_handoff_recorded',status:row.status});},()=>this.get(ctx,r));}
 accept(ctx:PortalContext,input:unknown,key:string){const r=customerConfirmSchema.parse(input);this.owner(ctx,r.case_ref);const offer=this.offer(r.case_ref),confirmation=this.event(r.case_ref,'confirm');if(!offer||offer.offer_id!==r.offer_id||!confirmation||(JSON.parse(confirmation.payload_json) as {offer_id:string}).offer_id!==r.offer_id)throw new PortalError('fcl_customer_confirmation_required');
  const payload=JSON.parse(confirmation.payload_json) as {contact_name:string};
  this.workflow.startFclExecution(ctx,{contract_version:FCL_EXECUTION_VERSION,handoff:offer.handoff,confirmation:{method:'signed_document',confirmed_at:confirmation.created_at,contact_name:payload.contact_name,note:'客户在网站确认报价并提交委托',evidence_refs:[`portal:${confirmation.event_id}`]},coordinator_id:ctx.identity.userId,expected_config_version:this.execution.configuration(ctx).version,confirmed:true},key,this.execution);
  return this.transaction(ctx,r.case_ref,'accept',r,key,()=>{if(this.event(r.case_ref,'accept'))return;this.write(ctx,r.case_ref,'accept',{offer_id:r.offer_id},'运营已接单，开始执行');},()=>this.project(r.case_ref));
 }
 run(ctx:PortalContext,action:CustomerAction,input:unknown,key:()=>string){switch(action){case 'customer-claim':return this.claim(ctx,input,key());case 'customer-list':return this.list(ctx,input);case 'customer-get':return this.get(ctx,input as {case_ref:string});case 'customer-pdf':{const r=input as {case_ref:string;offer_id:string};this.claimed(ctx,r.case_ref);const event=this.db.prepare("SELECT payload_json FROM business_case_events WHERE case_id=? AND event_kind='portal_offer' AND json_extract(payload_json,'$.offer_id')=?").get(r.case_ref,r.offer_id) as {payload_json:string}|undefined;if(!event)throw new PortalError('fcl_not_found');return this.workflow.readPublishedFclPdf(this.row(r.case_ref).owner_id,(JSON.parse(event.payload_json) as Offer).handoff);}case 'customer-confirm':return this.confirm(ctx,input,key());case 'customer-quote-publish':return this.publish(ctx,input,key());case 'customer-order-accept':return this.accept(ctx,input,key());case 'customer-order-get':{const r=input as {case_ref:string};this.owner(ctx,r.case_ref);return this.project(r.case_ref);}}}
}
