import { createHash, randomUUID } from 'node:crypto';
import { openPortalProductionDatabase, securePortalDatabaseFiles } from './production-persistence';
import { PortalError, type PortalContext } from './contracts';
import type { PortalService } from './service';
import { type CustomsDataset } from '../../customs-native/contracts';
import { validateCustomsDataset, customsRelease } from '../../customs-native/publication';
import { residentialRatesSchema, validateResidentialRates, type ResidentialRates } from '../../quote-native/contracts';
import { nativePublishSchema,nativeDisableSchema,nativeRollbackSchema,customsSaveSchema,residentialSaveSchema,type NativeKind } from './native-admin-contracts';
export const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
interface Row{scope:string;kind:NativeKind;version:number;draft:string;active:string|null}
export interface NativePublication<T=CustomsDataset|ResidentialRates>{release_id:string;version:number;input:T;published_at:string;digest:string}
export class NativeAdminStore{
 readonly db;
 constructor(readonly path:string){this.db=openPortalProductionDatabase(path,'freightclaw-native-business');const v=this.db.prepare('PRAGMA user_version').get() as {user_version:number};if(v.user_version>1){this.db.close();throw new Error('native_schema_incompatible');}this.db.exec(`CREATE TABLE IF NOT EXISTS native_configs(scope TEXT NOT NULL,kind TEXT NOT NULL,version INTEGER NOT NULL,draft TEXT NOT NULL,active TEXT,PRIMARY KEY(scope,kind));CREATE TABLE IF NOT EXISTS native_releases(id TEXT PRIMARY KEY,scope TEXT NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL);CREATE TABLE IF NOT EXISTS native_audit(id TEXT PRIMARY KEY,scope TEXT NOT NULL,kind TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,digest TEXT NOT NULL,created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS native_idempotency(scope TEXT NOT NULL,key TEXT NOT NULL,digest TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(scope,key));PRAGMA user_version=1;`);securePortalDatabaseFiles(path);}
 close(){this.db.close();securePortalDatabaseFiles(this.path);}
 current<T=CustomsDataset|ResidentialRates>(scope:string,kind:NativeKind):NativePublication<T>|null{const r=this.db.prepare('SELECT r.payload FROM native_releases r JOIN native_configs c ON c.active=r.id AND c.scope=r.scope AND c.kind=r.kind WHERE c.scope=? AND c.kind=?').get(scope,kind) as {payload:string}|undefined;return r?JSON.parse(r.payload) as NativePublication<T>:null;}
 customsReader(scope:string){return {current:(date:string)=>{const r=this.current<CustomsDataset>(scope,'customs');if(!r||r.input.rule_date>date)return null;return customsRelease(r.input,r.release_id,r.published_at);}};}
}
export class NativeAdminService{
 constructor(private store:NativeAdminStore,private portal:Pick<PortalService,'getState'>){}
 private scope(ctx:PortalContext,write=false){if(!ctx.identity.emailVerified||!ctx.organizationId||ctx.identity.platformRole!==null)throw new PortalError('native_organization_required');const state=this.portal.getState(ctx).data;const member=state?.memberships.find(m=>m.userId===ctx.identity.userId&&m.organizationId===ctx.organizationId&&m.status==='active');if(!member||state?.current_organization?.status!=='active'||write&&!['owner','admin'].includes(member.role))throw new PortalError('native_management_denied');return ctx.organizationId;}
 private row(scope:string,kind:NativeKind){return this.store.db.prepare('SELECT * FROM native_configs WHERE scope=? AND kind=?').get(scope,kind) as Row|undefined;}
 get(ctx:PortalContext,kind:NativeKind){const scope=this.scope(ctx),row=this.row(scope,kind);const history=this.store.db.prepare('SELECT payload FROM native_releases WHERE scope=? AND kind=? ORDER BY rowid DESC LIMIT 50').all(scope,kind).map(r=>{const p=JSON.parse(r.payload as string) as NativePublication;return {release_id:p.release_id,version:p.version,label:p.input.label,published_at:p.published_at,digest:p.digest};});return {kind,version:row?.version??0,draft:row?JSON.parse(row.draft) as unknown:null,active_release:this.store.current(scope,kind),history};}
 private problems(kind:NativeKind,input:unknown){const errors=kind==='customs'?validateCustomsDataset(input):validateResidentialRates(input);if(kind==='residential'&&residentialRatesSchema.safeParse(input).success&&(input as ResidentialRates).valid_until<new Date().toISOString().slice(0,10))errors.push('运价已经到期。');return errors;}
 preview(ctx:PortalContext,kind:NativeKind,releaseId?:string){const scope=this.scope(ctx),row=this.row(scope,kind);if(!row)throw new PortalError('native_draft_missing');let input=JSON.parse(row.draft) as unknown;if(releaseId){const r=this.store.db.prepare('SELECT payload FROM native_releases WHERE id=? AND scope=? AND kind=?').get(releaseId,scope,kind) as {payload:string}|undefined;if(!r)throw new PortalError('native_release_not_found');input=(JSON.parse(r.payload) as NativePublication).input;}const blockers=this.problems(kind,input);return {kind,version:row.version,input,release_id:releaseId??null,preview_hash:digest([scope,kind,row.version,input,releaseId??null]),can_publish:blockers.length===0,blockers};}
 private mutate(ctx:PortalContext,kind:NativeKind,action:string,input:unknown,key:string,write:(scope:string)=>void){const scope=this.scope(ctx,true);if(!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('idempotency_key_invalid');const db=this.store.db,partition=JSON.stringify([scope,ctx.identity.userId,kind,action]),hash=digest(input);db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT digest,result FROM native_idempotency WHERE scope=? AND key=?').get(partition,key) as {digest:string;result:string}|undefined;if(old){if(old.digest!==hash)throw new PortalError('idempotency_conflict');db.exec('COMMIT');return JSON.parse(old.result) as ReturnType<NativeAdminService['get']>;}write(scope);const result=this.get(ctx,kind);db.prepare('INSERT INTO native_audit VALUES(?,?,?,?,?,?,?)').run(randomUUID(),scope,kind,ctx.identity.userId,action,hash,new Date().toISOString());db.prepare('INSERT INTO native_idempotency VALUES(?,?,?,?)').run(partition,key,hash,JSON.stringify(result));db.exec('COMMIT');return this.get(ctx,kind);}catch(e){db.exec('ROLLBACK');throw e;}}
 private expected(scope:string,kind:NativeKind,version:number){const row=this.row(scope,kind);if((row?.version??0)!==version)throw new PortalError('version_conflict');if(version>=1000)throw new PortalError('native_version_limit');return row;}
 save(ctx:PortalContext,kind:NativeKind,input:unknown,key:string){const parsed=(kind==='customs'?customsSaveSchema:residentialSaveSchema).safeParse(input);if(!parsed.success)throw new PortalError('native_input_invalid');const d=parsed.data;return this.mutate(ctx,kind,'save',d,key,scope=>{this.expected(scope,kind,d.expected_version);this.store.db.prepare('INSERT INTO native_configs VALUES(?,?,?,?,NULL) ON CONFLICT(scope,kind) DO UPDATE SET draft=excluded.draft,version=excluded.version').run(scope,kind,d.expected_version+1,JSON.stringify(d.input));});}
 publish(ctx:PortalContext,kind:NativeKind,input:unknown,key:string){const p=nativePublishSchema.safeParse(input);if(!p.success)throw new PortalError('native_input_invalid');return this.mutate(ctx,kind,'publish',p.data,key,scope=>{this.expected(scope,kind,p.data.expected_version);const preview=this.preview(ctx,kind);if(preview.preview_hash!==p.data.preview_hash)throw new PortalError('native_preview_mismatch');if(!preview.can_publish)throw new PortalError('native_publication_blocked');const release={release_id:randomUUID(),version:p.data.expected_version+1,input:preview.input,published_at:new Date().toISOString(),digest:digest(preview.input)};this.store.db.prepare('INSERT INTO native_releases VALUES(?,?,?,?)').run(release.release_id,scope,kind,JSON.stringify(release));this.store.db.prepare('UPDATE native_configs SET active=?,version=version+1 WHERE scope=? AND kind=?').run(release.release_id,scope,kind);});}
 disable(ctx:PortalContext,kind:NativeKind,input:unknown,key:string){const p=nativeDisableSchema.safeParse(input);if(!p.success)throw new PortalError('native_input_invalid');return this.mutate(ctx,kind,'disable',p.data,key,scope=>{if(!this.expected(scope,kind,p.data.expected_version))throw new PortalError('native_draft_missing');this.store.db.prepare('UPDATE native_configs SET active=NULL,version=version+1 WHERE scope=? AND kind=?').run(scope,kind);});}
 rollback(ctx:PortalContext,kind:NativeKind,input:unknown,key:string){const p=nativeRollbackSchema.safeParse(input);if(!p.success)throw new PortalError('native_input_invalid');return this.mutate(ctx,kind,'rollback',p.data,key,scope=>{this.expected(scope,kind,p.data.expected_version);const preview=this.preview(ctx,kind,p.data.release_id);if(preview.preview_hash!==p.data.preview_hash||!preview.can_publish)throw new PortalError('native_preview_mismatch');this.store.db.prepare('UPDATE native_configs SET active=?,version=version+1 WHERE scope=? AND kind=?').run(p.data.release_id,scope,kind);});}
}
