import { createCipheriv, createDecipheriv, randomBytes, randomUUID, createHmac } from 'node:crypto';
import { constants, existsSync, closeSync, fstatSync, openSync, readFileSync, writeFileSync } from 'node:fs';
import type { NativeAdminStore } from './native-admin';
import type { PortalService } from './service';
import { PortalError, type PortalContext } from './contracts';
import { freightcomSaveSchema,freightcomDisableSchema } from './native-admin-contracts';
export class NativeFreightcomService{
 private key:Buffer;
 constructor(private store:NativeAdminStore,private portal:Pick<PortalService,'getState'>){const path=store.path+'.encryption-key';const table=store.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='native_freightcom'").get();if(!existsSync(path)&&table&&store.db.prepare('SELECT scope FROM native_freightcom WHERE encrypted IS NOT NULL LIMIT 1').get())throw new Error('native_encryption_key_missing');try{writeFileSync(path,randomBytes(32),{mode:0o600,flag:'wx'});}catch(e){if((e as NodeJS.ErrnoException).code!=='EEXIST')throw e;}const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const s=fstatSync(fd);if(!s.isFile()||s.size!==32||(s.mode&0o077)!==0)throw new Error('native_encryption_key_invalid');this.key=readFileSync(fd);}finally{closeSync(fd);}store.db.exec('CREATE TABLE IF NOT EXISTS native_freightcom(scope TEXT PRIMARY KEY,version INTEGER NOT NULL,label TEXT NOT NULL,encrypted TEXT,updated TEXT NOT NULL)');}
 close(){this.key.fill(0);}
 private scope(ctx:PortalContext){if(!ctx.identity.emailVerified||!ctx.organizationId||ctx.identity.platformRole!==null)throw new PortalError('native_organization_required');const state=this.portal.getState(ctx).data;const member=state?.memberships.find(m=>m.organizationId===ctx.organizationId&&m.userId===ctx.identity.userId&&m.status==='active');if(!member||!['owner','admin'].includes(member.role)||state?.current_organization?.status!=='active')throw new PortalError('native_management_denied');return ctx.organizationId;}
 private row(scope:string){return this.store.db.prepare('SELECT * FROM native_freightcom WHERE scope=?').get(scope) as {version:number;label:string;encrypted:string|null;updated:string}|undefined;}
 get(ctx:PortalContext){const row=this.row(this.scope(ctx));return {version:row?.version??0,label:row?.label??'',credential_present:!!row?.encrypted,updated_at:row?.updated??null,provider:'Freightcom',live_rate_verified:false};}
 credential(scope:string){const row=this.row(scope);if(!row?.encrypted)throw new Error('freightcom_connection_unconfigured');const [iv,tag,value]=row.encrypted.split('.').map(v=>Buffer.from(v,'base64'));const cipher=createDecipheriv('aes-256-gcm',this.key,iv!);cipher.setAAD(Buffer.from(scope));cipher.setAuthTag(tag!);return Buffer.concat([cipher.update(value!),cipher.final()]).toString('utf8');}
 change(ctx:PortalContext,input:unknown,key:string,disable=false){const scope=this.scope(ctx),parsed=(disable?freightcomDisableSchema:freightcomSaveSchema).safeParse(input);if(!parsed.success||!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('native_input_invalid');const p=parsed.data,save=disable?null:freightcomSaveSchema.parse(input),hash=createHmac('sha256',this.key).update(JSON.stringify(p)).digest('hex'),partition=JSON.stringify([scope,ctx.identity.userId,'freightcom',disable]);const db=this.store.db;db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT digest,result FROM native_idempotency WHERE scope=? AND key=?').get(partition,key) as {digest:string;result:string}|undefined;if(old){if(old.digest!==hash)throw new PortalError('idempotency_conflict');db.exec('COMMIT');return JSON.parse(old.result) as ReturnType<NativeFreightcomService['get']>;}const row=this.row(scope);if((row?.version??0)!==p.expected_version)throw new PortalError('version_conflict');let encrypted:string|null=null;if(save){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(Buffer.from(scope));const bytes=Buffer.concat([cipher.update(save.credential,'utf8'),cipher.final()]);encrypted=[iv,cipher.getAuthTag(),bytes].map(v=>v.toString('base64')).join('.');}db.prepare('INSERT INTO native_freightcom VALUES(?,?,?,?,?) ON CONFLICT(scope) DO UPDATE SET version=excluded.version,label=excluded.label,encrypted=excluded.encrypted,updated=excluded.updated').run(scope,p.expected_version+1,save?.label??row?.label??'',encrypted,new Date().toISOString());const result=this.get(ctx);db.prepare('INSERT INTO native_audit VALUES(?,?,?,?,?,?,?)').run(randomUUID(),scope,'freightcom',ctx.identity.userId,disable?'disable':'save',hash,new Date().toISOString());db.prepare('INSERT INTO native_idempotency VALUES(?,?,?,?)').run(partition,key,hash,JSON.stringify(result));db.exec('COMMIT');return this.get(ctx);}catch(e){db.exec('ROLLBACK');throw e;}}
}
