import { randomUUID } from 'node:crypto';
import { createNativeCustomsClients } from '../../customs-native/client';
import type { NativeAdminStore } from './native-admin';
import { customsHistoryListInput, customsHistoryGetInput, customsHistoryListResponse, customsHistoryGetResponse } from './business/customs-history-client';
import { inputSchema } from './business/customs-client';
import { singleInputSchema, batchInputSchema, batchResponseSchema } from './business/tax-client';
import type { PortalBusinessClientResult, PortalBusinessConnection } from './business/service';
export function nativeCustomsWithHistory(store:NativeAdminStore,scope:string,tenant:string):Pick<PortalBusinessConnection,'customsClient'|'taxClient'|'customsHistoryClient'>{
 store.db.exec('CREATE TABLE IF NOT EXISTS native_customs_history(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,scope TEXT NOT NULL,actor TEXT NOT NULL,operation TEXT NOT NULL,payload TEXT NOT NULL,created TEXT NOT NULL);CREATE INDEX IF NOT EXISTS native_history_owner ON native_customs_history(scope,actor,operation,seq)');
 const clients=createNativeCustomsClients(store.customsReader(scope));
 type Request={input:unknown;actor:{type:'user'|'service';id:string};requestId:string};
 const save=(r:Request,operation:'customs.query'|'customs.tax.estimate',result:PortalBusinessClientResult)=>{if(r.actor.type!=='user')return;const input=(operation==='customs.query'?inputSchema:singleInputSchema).safeParse(r.input);if(!input.success)return;const snapshot=result.data as {snapshotHash?:string;result?:{publication?:{snapshotHash?:string}}}|null;const snapshotHash=snapshot?.snapshotHash??snapshot?.result?.publication?.snapshotHash;const record={record_ref:randomUUID(),operation,created_at:new Date().toISOString(),status:result.status,data_version:snapshotHash?`snapshot:${snapshotHash}`:'not_returned'};const payload={operation,record,input:input.data,snapshot:result.data};const checked=customsHistoryGetResponse.parse({schema_version:'customs-history@2026-09-06.v1',request_id:r.requestId,tenant_id:tenant,actor_ref:r.actor.id,application_id:'freightclaw-native',status:'success',data:payload,reason_codes:[]});store.db.prepare('INSERT INTO native_customs_history(id,scope,actor,operation,payload,created) VALUES(?,?,?,?,?,?)').run(record.record_ref,scope,r.actor.id,operation,JSON.stringify(checked.data),record.created_at);};
 async function query(r:Request){const result=await clients.customsClient.query(r);save(r,'customs.query',result);return result;}
 async function estimate(r:Request){const result=await clients.taxClient.estimate(r);save(r,'customs.tax.estimate',result);return result;}
 async function estimateBatch(r:Request){const result=await clients.taxClient.estimateBatch(r),parsed=batchInputSchema.safeParse(r.input),data=batchResponseSchema.safeParse(result.data);if(parsed.success&&data.success)for(const item of data.data.results){save({...r,input:{...item.input,ruleDate:parsed.data.ruleDate}},'customs.tax.estimate',{...result,status:item.status,data:{contractVersion:data.data.contractVersion,requestId:r.requestId,delegatedActor:data.data.delegatedActor,status:item.status,result:item}});}return result;}
 return {customsClient:{query},taxClient:{estimate,estimateBatch},customsHistoryClient:{read:request=>{
  const base={schema_version:'customs-history@2026-09-06.v1',request_id:request.requestId,tenant_id:tenant,actor_ref:request.actorId,application_id:'freightclaw-native',status:'success',reason_codes:[]};
  if(request.action==='get'){const p=customsHistoryGetInput.parse(request.input);const row=store.db.prepare('SELECT payload FROM native_customs_history WHERE id=? AND scope=? AND actor=? AND operation=?').get(p.record_ref,scope,request.actorId,p.operation) as {payload:string}|undefined;return Promise.resolve(customsHistoryGetResponse.parse({...base,status:row?'success':'blocked',reason_codes:row?[]:['customs_history_record_not_found'],data:row?JSON.parse(row.payload) as unknown:null}));}
  const p=customsHistoryListInput.parse(request.input);let cursor=Number.MAX_SAFE_INTEGER;if(p.cursor){const row=store.db.prepare('SELECT seq FROM native_customs_history WHERE id=? AND scope=? AND actor=? AND operation=?').get(p.cursor,scope,request.actorId,p.operation) as {seq:number}|undefined;if(!row)return Promise.resolve(customsHistoryListResponse.parse({...base,status:'blocked',data:null,reason_codes:['customs_history_cursor_invalid']}));cursor=row.seq;}
  const rows=store.db.prepare('SELECT id,payload FROM native_customs_history WHERE scope=? AND actor=? AND operation=? AND seq<? ORDER BY seq DESC LIMIT ?').all(scope,request.actorId,p.operation,cursor,p.limit+1) as {id:string;payload:string}[];return Promise.resolve(customsHistoryListResponse.parse({...base,data:{records:rows.slice(0,p.limit).map(r=>(JSON.parse(r.payload) as {record:unknown}).record),next_cursor:rows.length>p.limit?rows[p.limit-1]!.id:null}}));
 }}};
}
