import { createHash, randomUUID } from "node:crypto";
import { PORTAL_CAPABILITIES, PortalError, success, type AccessRequest, type Application, type Grant, type Organization, type PortalCapabilityId, type PortalContext, type PortalEnvelope, type PortalMutation, type PortalRole, type PortalState } from "./contracts";
import type { PortalData, PortalRepository } from "./store";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const identifier = (value: string) => /^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$/u.test(value);
const uniqCaps = (values: readonly PortalCapabilityId[]) => [...new Set(values)].sort();

export interface PortalServiceOptions { readonly repository: PortalRepository; readonly dataMode?: "fixtures" | "production"; readonly now?: () => string; readonly id?: (prefix: string) => string }
export interface PortalBusinessReviewApplicationSummary {
  readonly organizationId: string; readonly organizationName: string; readonly organizationStatus: Organization["status"];
  readonly tenantId: string; readonly applicationId: string; readonly applicationName: string; readonly applicationStatus: Application["status"];
  readonly clientId: string;
}
export class PortalService {
  readonly #repo: PortalRepository; readonly #dataMode: "fixtures" | "production"; readonly #now: () => string; readonly #id: (prefix:string)=>string;
  constructor(options: PortalServiceOptions) { this.#repo=options.repository; this.#dataMode=options.dataMode ?? (options.repository.kind === "synthetic" ? "fixtures" : "production"); this.#now=options.now ?? (()=>new Date().toISOString()); this.#id=options.id ?? ((p)=>`${p}_${randomUUID().replaceAll("-","")}`); }
  #member(data: PortalData, ctx: PortalContext) { return ctx.organizationId === null ? undefined : data.memberships.find(x=>x.organizationId===ctx.organizationId&&x.userId===ctx.identity.userId&&x.status==="active"); }
  #requireMember(data: PortalData, ctx: PortalContext, roles?: readonly PortalRole[]) { const member=this.#member(data,ctx); if(!member||!data.organizations.some(x=>x.organizationId===ctx.organizationId&&x.status==="active")) throw new PortalError("membership_required"); if(roles&&!roles.includes(member.role)) throw new PortalError("organization_role_required"); return member; }
  #mutate<T>(ctx:PortalContext, action:string, mutation:PortalMutation<T>, fn:(data:PortalData,input:T)=>unknown):PortalEnvelope<unknown>{
    if(!ctx.identity.emailVerified) throw new PortalError("verified_identity_required");
    try { return this.#repo.transact(action,mutation.idempotencyKey,hash({actorUserId:ctx.identity.userId,organizationId:ctx.organizationId,action,expectedVersion:mutation.expectedVersion??null,input:mutation.input}),data=>success(fn(data,mutation.input))); }
    catch(e){ if(e instanceof PortalError) throw e; throw new PortalError(e instanceof Error ? e.message : "portal_store_unavailable"); }
  }
  #op(data:PortalData,ctx:PortalContext,action:string,type:string,ref:string,from:string|null,to:string|null){data.operations.push({operationId:this.#id("op"),organizationId:ctx.organizationId,actorUserId:ctx.identity.userId,action,objectType:type,objectRef:ref,fromState:from,toState:to,createdAt:this.#now()});}
  #recordUser(data:PortalData,ctx:PortalContext){if(!data.users.some(x=>x.userId===ctx.identity.userId))data.users.push({userId:ctx.identity.userId,displayName:ctx.identity.displayName,email:ctx.identity.email.toLowerCase(),emailVerified:ctx.identity.emailVerified,createdAt:this.#now()});}
  getState(ctx: PortalContext): PortalEnvelope<PortalState> {
    if(!ctx.identity.emailVerified) throw new PortalError("verified_identity_required"); const d=this.#repo.read(); const now=Date.parse(this.#now());
    const ownMemberships=d.memberships.filter(x=>x.userId===ctx.identity.userId&&x.status==="active"); const ownOrgIds=new Set(ownMemberships.map(x=>x.organizationId));
    const matchingInvitations=d.invitations.filter(x=>x.email===ctx.identity.email.toLowerCase()&&x.status==="pending"&&Date.parse(x.expiresAt)>now);
    const selectableOrgIds=new Set([...ownOrgIds,...matchingInvitations.map(x=>x.organizationId)]); const organizationSummaries=d.organizations.filter(x=>selectableOrgIds.has(x.organizationId)).map(({organizationId,displayName,status})=>({organizationId,displayName,status}));
    const emptyBase={data_mode:this.#dataMode,identity:ctx.identity,current_organization:null,organizations:organizationSummaries,users:[],memberships:ownMemberships,invitations:matchingInvitations,applications:[],requests:[],grants:[],catalog:PORTAL_CAPABILITIES.map(capabilityId=>({capabilityId,available:true,reasonCode:null})),operations:[]};
    if(ctx.organizationId===null)return success(emptyBase);
    const current=d.organizations.find(x=>x.organizationId===ctx.organizationId&&x.status==="active")??null;if(!ownOrgIds.has(ctx.organizationId)||current===null)throw new PortalError("active_organization_membership_required");
    const scoped=<T extends {organizationId:string}>(xs:T[])=>xs.filter(x=>x.organizationId===ctx.organizationId);const visibleUsers=new Set(scoped(d.memberships).map(x=>x.userId));const role=this.#member(d,ctx)?.role;
    return success({...emptyBase,current_organization:current,users:d.users.filter(x=>visibleUsers.has(x.userId)).slice(0,500).map(({userId,displayName})=>({userId,displayName})),memberships:scoped(d.memberships),invitations:scoped(d.invitations).map(x=>({...x,status:x.status==="pending"&&Date.parse(x.expiresAt)<=now?"expired":x.status,email:role==="owner"||role==="admin"?x.email:"redacted"})),applications:scoped(d.applications),requests:scoped(d.requests),grants:scoped(d.grants),catalog:[...PORTAL_CAPABILITIES.map(capabilityId=>({capabilityId,available:true,reasonCode:null})),{capabilityId:"customs.query",available:false,reasonCode:"capability_not_provisionable"},{capabilityId:"quote.calculate",available:false,reasonCode:"capability_not_provisionable"}],operations:d.operations.filter(x=>x.organizationId===ctx.organizationId).slice(-100)});
  }
  getReviewQueue(ctx:PortalContext):PortalEnvelope<Readonly<{requests:readonly {requestId:string;organizationId:string;applicationId:string;requestedCapabilities:readonly PortalCapabilityId[];state:AccessRequest["state"];version:number;applicantUserId:string;applicantDisplayName:string;justification:string;reviewReason:string|null;reviewerUserId:string|null;createdAt:string;updatedAt:string}[];organizations:readonly {organizationId:string;displayName:string}[];applications:readonly {applicationId:string;organizationId:string;name:string;environment:"test"|"production"}[]}>>{if((ctx.identity.platformRole!=="reviewer"&&ctx.identity.platformRole!=="operator")||ctx.organizationId!==null)throw new PortalError("reviewer_required");const d=this.#repo.read();const allowed=new Set(["submitted","in_review","needs_input","approved","rejected"]);const requests=d.requests.filter(x=>allowed.has(x.state)).slice(-200).map(({requestId,organizationId,applicationId,requestedCapabilities,state,version,applicantUserId,justification,reviewReason,reviewerUserId,createdAt,updatedAt})=>({requestId,organizationId,applicationId,requestedCapabilities,state,version,applicantUserId,applicantDisplayName:d.users.find(x=>x.userId===applicantUserId)?.displayName??"未知申请人",justification,reviewReason,reviewerUserId,createdAt,updatedAt}));const orgIds=new Set(requests.map(x=>x.organizationId));const appIds=new Set(requests.map(x=>x.applicationId));return success({requests,organizations:d.organizations.filter(x=>orgIds.has(x.organizationId)).map(({organizationId,displayName})=>({organizationId,displayName})),applications:d.applications.filter(x=>appIds.has(x.applicationId)).map(({applicationId,organizationId,name,environment})=>({applicationId,organizationId,name,environment}))});}
  getProvisioningQueue(ctx:PortalContext):PortalEnvelope<Readonly<{grants:readonly {grantId:string;version:number;organizationId:string;applicationId:string;capabilities:readonly PortalCapabilityId[];state:"provisioning";createdAt:string;updatedAt:string}[];organizations:readonly {organizationId:string;displayName:string}[];applications:readonly {applicationId:string;organizationId:string;name:string;environment:"test"|"production"}[]}>>{if(ctx.identity.platformRole!=="operator"||ctx.organizationId!==null)throw new PortalError("operator_required");const d=this.#repo.read();const grants=d.grants.filter(x=>x.state==="provisioning").slice(0,200).map(({grantId,version,organizationId,applicationId,capabilities,state,createdAt,updatedAt})=>({grantId,version,organizationId,applicationId,capabilities,state:state as "provisioning",createdAt,updatedAt}));const orgIds=new Set(grants.map(x=>x.organizationId));const appIds=new Set(grants.map(x=>x.applicationId));return success({grants,organizations:d.organizations.filter(x=>orgIds.has(x.organizationId)).map(({organizationId,displayName})=>({organizationId,displayName})),applications:d.applications.filter(x=>appIds.has(x.applicationId)).map(({applicationId,organizationId,name,environment})=>({applicationId,organizationId,name,environment}))});}
  getPlatformState(ctx:PortalContext){if(ctx.organizationId!==null||(ctx.identity.platformRole!=="reviewer"&&ctx.identity.platformRole!=="operator"))throw new PortalError("platform_context_required");const grants=ctx.identity.platformRole==="operator"?this.#repo.read().grants.slice(-200).map(({grantId,organizationId,applicationId,requestId,capabilities,state,version,expiresAt,createdAt,updatedAt})=>({grantId,organizationId,applicationId,requestId,capabilities,state,version,expiresAt,createdAt,updatedAt})):[];return success({review:this.getReviewQueue(ctx).data,provisioning:ctx.identity.platformRole==="operator"?this.getProvisioningQueue(ctx).data:null,grants});}
  bootstrapOrganization(ctx:PortalContext, mutation:PortalMutation<{organizationId:string;tenantId:string;displayName:string}>){ if(this.#repo.kind!=="synthetic"||ctx.identity.platformRole!=="operator") throw new PortalError("synthetic_bootstrap_forbidden"); return this.#mutate(ctx,"organization.bootstrap",mutation,(d,i)=>{if(!identifier(i.organizationId)||!identifier(i.tenantId)||!i.displayName.trim())throw new PortalError("input_invalid"); if(d.organizations.some(x=>x.organizationId===i.organizationId))throw new PortalError("organization_exists");const createdAt=this.#now();this.#recordUser(d,ctx);d.organizations.push({...i,displayName:i.displayName.trim(),status:"active",createdAt});d.memberships.push({organizationId:i.organizationId,userId:ctx.identity.userId,role:"owner",status:"active",createdAt});this.#op(d,{...ctx,organizationId:i.organizationId},"organization.bootstrap","organization",i.organizationId,null,"active");return {organizationId:i.organizationId};}); }
  inviteMember(ctx:PortalContext,mutation:PortalMutation<{email:string;role:PortalRole;expiresAt:string}>){return this.#mutate(ctx,"invitation.create",mutation,(d,i)=>{const inviter=this.#requireMember(d,ctx,["owner","admin"]);const expiry=Date.parse(i.expiresAt);if((i.role==="owner"&&inviter.role!=="owner")||!/^[^@\s]+@[^@\s]+$/u.test(i.email)||!Number.isFinite(expiry)||expiry<=Date.parse(this.#now()))throw new PortalError("input_invalid");const invitationId=this.#id("inv");d.invitations.push({invitationId,organizationId:ctx.organizationId!,email:i.email.toLowerCase(),role:i.role,status:"pending",expiresAt:i.expiresAt,invitedBy:ctx.identity.userId,claimedBy:null,createdAt:this.#now()});this.#op(d,ctx,"invitation.create","invitation",invitationId,null,"pending");return {invitationId};});}
  claimInvitation(ctx:PortalContext,invitationId:string,idempotencyKey:string){return this.#mutate(ctx,`invitation.claim:${invitationId}`,{idempotencyKey,input:{invitationId}},(d)=>{const inv=d.invitations.find(x=>x.invitationId===invitationId);if(!inv||inv.status!=="pending")throw new PortalError("invitation_unavailable");if(inv.email!==ctx.identity.email.toLowerCase())throw new PortalError("invitation_identity_mismatch");if(Date.parse(inv.expiresAt)<=Date.parse(this.#now()))throw new PortalError("invitation_expired");if(d.memberships.some(x=>x.organizationId===inv.organizationId&&x.userId===ctx.identity.userId))throw new PortalError("membership_exists");this.#recordUser(d,ctx);inv.status="claimed";inv.claimedBy=ctx.identity.userId;d.memberships.push({organizationId:inv.organizationId,userId:ctx.identity.userId,role:inv.role,status:"active",createdAt:this.#now()});this.#op(d,{...ctx,organizationId:inv.organizationId},"invitation.claim","invitation",invitationId,"pending","claimed");return {organizationId:inv.organizationId};});}
  revokeInvitation(ctx:PortalContext,invitationId:string,idempotencyKey:string){return this.#mutate(ctx,`invitation.revoke:${invitationId}`,{idempotencyKey,input:{invitationId}},d=>{this.#requireMember(d,ctx,["owner","admin"]);const inv=d.invitations.find(x=>x.organizationId===ctx.organizationId&&x.invitationId===invitationId);if(!inv||inv.status!=="pending")throw new PortalError("invitation_unavailable");(inv as {status:string}).status="revoked";this.#op(d,ctx,"invitation.revoke","invitation",invitationId,"pending","revoked");return {invitationId};});}
  changeMembership(ctx:PortalContext,userId:string,mutation:PortalMutation<{role?:PortalRole;status?:"active"|"suspended"}>){return this.#mutate(ctx,`membership.change:${userId}`,mutation,(d,i)=>{const actor=this.#requireMember(d,ctx,["owner","admin"]);const m=d.memberships.find(x=>x.organizationId===ctx.organizationId&&x.userId===userId);if(!m)throw new PortalError("membership_not_found");if(actor.role!=="owner"&&(m.role==="owner"||i.role==="owner"))throw new PortalError("owner_change_forbidden");const removingOwner=m.role==="owner"&&(i.role&&i.role!=="owner"||i.status==="suspended");if(removingOwner&&d.memberships.filter(x=>x.organizationId===ctx.organizationId&&x.role==="owner"&&x.status==="active").length===1)throw new PortalError("last_owner_protected");if((i.status==="suspended"||i.role==="viewer")&&d.applications.some(x=>x.organizationId===ctx.organizationId&&x.ownerUserId===userId&&x.status==="active"))throw new PortalError("application_owner_protected");const before=`${m.role}:${m.status}`;Object.assign(m,i);this.#op(d,ctx,"membership.change","membership",userId,before,`${m.role}:${m.status}`);return m;});}
  createApplication(ctx:PortalContext,mutation:PortalMutation<{applicationId:string;clientId:string;name:string;purpose:string;environment:"test"|"production";ownerUserId:string}>){return this.#mutate(ctx,"application.create",mutation,(d,i)=>{this.#requireMember(d,ctx,["owner","admin","developer"]);if(!identifier(i.applicationId)||!identifier(i.clientId)||!i.name.trim()||d.applications.some(x=>x.applicationId===i.applicationId||x.clientId===i.clientId))throw new PortalError("input_invalid");if(!d.memberships.some(x=>x.organizationId===ctx.organizationId&&x.userId===i.ownerUserId&&x.status==="active"&&x.role!=="viewer"))throw new PortalError("application_owner_invalid");const app:Application={...i,organizationId:ctx.organizationId!,name:i.name.trim(),purpose:i.purpose.trim(),status:"active",createdAt:this.#now(),version:1};d.applications.push(app);this.#op(d,ctx,"application.create","application",app.applicationId,null,"active");return app;});}
  changeApplication(ctx:PortalContext,id:string,mutation:PortalMutation<{ownerUserId?:string;status?:"active"|"suspended"}>){return this.#mutate(ctx,`application.change:${id}`,mutation,(d,i)=>{const member=this.#requireMember(d,ctx,["owner","admin","developer"]);const app=d.applications.find(x=>x.organizationId===ctx.organizationId&&x.applicationId===id);if(!app)throw new PortalError("application_not_found");if(member.role==="developer"&&app.ownerUserId!==ctx.identity.userId)throw new PortalError("application_access_denied");if(mutation.expectedVersion!==app.version)throw new PortalError("version_conflict");if(i.ownerUserId&&!d.memberships.some(x=>x.organizationId===ctx.organizationId&&x.userId===i.ownerUserId&&x.status==="active"&&x.role!=="viewer"))throw new PortalError("application_owner_invalid");Object.assign(app,i,{version:app.version+1});this.#op(d,ctx,"application.change","application",id,null,app.status);return app;});}
  createRequest(ctx:PortalContext,mutation:PortalMutation<{requestId:string;applicationId:string;capabilities:readonly PortalCapabilityId[];justification:string}>){return this.#mutate(ctx,"request.create",mutation,(d,i)=>{const app=this.requireApplicationAccess(ctx,i.applicationId,d,"manage");const caps=uniqCaps(i.capabilities);if(!identifier(i.requestId)||!caps.length||caps.some(x=>!PORTAL_CAPABILITIES.includes(x))||d.requests.some(x=>x.requestId===i.requestId))throw new PortalError("input_invalid");const now=this.#now();const req:AccessRequest={requestId:i.requestId,organizationId:app.organizationId,applicationId:app.applicationId,requestedCapabilities:caps,state:"draft",version:1,applicantUserId:ctx.identity.userId,justification:i.justification.trim(),reviewReason:null,reviewerUserId:null,createdAt:now,updatedAt:now};d.requests.push(req);this.#op(d,ctx,"request.create","access_request",req.requestId,null,"draft");return req;});}
  #transition(ctx:PortalContext,id:string,expectedVersion:number,idempotencyKey:string,action:string,allowed:string[],next:AccessRequest["state"]){return this.#mutate(ctx,`${action}:${id}`,{idempotencyKey,expectedVersion,input:{id}},d=>{const req=d.requests.find(x=>x.requestId===id&&x.organizationId===ctx.organizationId);if(!req)throw new PortalError("request_not_found");if(req.version!==expectedVersion)throw new PortalError("version_conflict");if(!allowed.includes(req.state))throw new PortalError("state_conflict");if(action==="request.submit"||action==="request.withdraw")this.requireApplicationAccess(ctx,req.applicationId,d,"manage");else if(ctx.identity.platformRole!=="reviewer"&&ctx.identity.platformRole!=="operator")throw new PortalError("reviewer_required");const from=req.state;(req as {state:AccessRequest["state"];version:number;updatedAt:string}).state=next;req.version++;req.updatedAt=this.#now();this.#op(d,ctx,action,"access_request",id,from,next);return req;});}
  submitRequest(ctx:PortalContext,id:string,expectedVersion:number,key:string){return this.#transition(ctx,id,expectedVersion,key,"request.submit",["draft","needs_input"],"submitted");}
  withdrawRequest(ctx:PortalContext,id:string,expectedVersion:number,key:string){return this.#transition(ctx,id,expectedVersion,key,"request.withdraw",["draft","submitted","needs_input"],"withdrawn");}
  markRequestInReview(ctx:PortalContext,id:string,expectedVersion:number,key:string){return this.#transition(ctx,id,expectedVersion,key,"request.review_start",["submitted"],"in_review");}
  decideRequest(ctx:PortalContext,id:string,mutation:PortalMutation<{decision:"approve"|"reject"|"needs_input";reason:string;approvedCapabilities?:readonly PortalCapabilityId[]}>){return this.#mutate(ctx,`request.decide:${id}`,mutation,(d,i)=>{if(ctx.identity.platformRole!=="reviewer"&&ctx.identity.platformRole!=="operator")throw new PortalError("reviewer_required");const req=d.requests.find(x=>x.requestId===id&&(ctx.organizationId===null||x.organizationId===ctx.organizationId));if(!req)throw new PortalError("request_not_found");if(req.applicantUserId===ctx.identity.userId)throw new PortalError("self_review_forbidden");if(req.version!==mutation.expectedVersion)throw new PortalError("version_conflict");if(!["submitted","in_review"].includes(req.state))throw new PortalError("state_conflict");const from=req.state;req.state=i.decision==="approve"?"approved":i.decision==="reject"?"rejected":"needs_input";req.reviewReason=i.reason.trim();req.reviewerUserId=ctx.identity.userId;req.version++;req.updatedAt=this.#now();let grant:Grant|null=null;if(i.decision==="approve"){const approved=uniqCaps(i.approvedCapabilities??req.requestedCapabilities);if(approved.length===0||approved.some(x=>!req.requestedCapabilities.includes(x)))throw new PortalError("approved_capabilities_invalid");grant={grantId:this.#id("grant"),organizationId:req.organizationId,applicationId:req.applicationId,requestId:req.requestId,capabilities:approved,state:"provisioning",version:1,expiresAt:null,provisionedRef:null,createdAt:this.#now(),updatedAt:this.#now()};d.grants.push(grant);}this.#op(d,{...ctx,organizationId:req.organizationId},"request.decide","access_request",id,from,req.state);return {request:req,grant};});}
  markGrantActive(ctx:PortalContext,id:string,mutation:PortalMutation<{provisionedRef:string;expiresAt?:string}>){return this.#mutate(ctx,`grant.activate:${id}`,mutation,(d,i)=>{if(ctx.identity.platformRole!=="operator")throw new PortalError("operator_required");const g=d.grants.find(x=>x.grantId===id&&(ctx.organizationId===null||x.organizationId===ctx.organizationId));if(!g||g.state!=="provisioning")throw new PortalError("grant_not_provisionable");if(g.version!==mutation.expectedVersion||!identifier(i.provisionedRef))throw new PortalError("version_conflict");if(i.expiresAt!==undefined&&(!Number.isFinite(Date.parse(i.expiresAt))||Date.parse(i.expiresAt)<=Date.parse(this.#now())))throw new PortalError("grant_expiry_invalid");g.state="active";g.provisionedRef=i.provisionedRef;g.expiresAt=i.expiresAt??null;g.version++;g.updatedAt=this.#now();this.#op(d,{...ctx,organizationId:g.organizationId},"grant.activate","grant",id,"provisioning","active");return g;});}
  changeGrantState(ctx:PortalContext,id:string,mutation:PortalMutation<{state:"suspended"|"revoked"}>){return this.#mutate(ctx,`grant.change:${id}`,mutation,(d,i)=>{const member=ctx.organizationId?this.#member(d,ctx):undefined;if(ctx.identity.platformRole!=="operator"&&(!member||!["owner","admin"].includes(member.role)))throw new PortalError("grant_admin_required");const g=d.grants.find(x=>x.grantId===id&&(ctx.organizationId===null||x.organizationId===ctx.organizationId));if(!g)throw new PortalError("grant_not_found");if((i.state==="suspended"&&g.state!=="active")||(i.state==="revoked"&&g.state==="revoked"))throw new PortalError("state_conflict");if(g.version!==mutation.expectedVersion)throw new PortalError("version_conflict");const from=g.state;g.state=i.state;g.version++;g.updatedAt=this.#now();this.#op(d,{...ctx,organizationId:g.organizationId},"grant.change","grant",id,from,g.state);return g;});}
  updateRequest(ctx:PortalContext,id:string,mutation:PortalMutation<{capabilities:readonly PortalCapabilityId[];justification:string}>){return this.#mutate(ctx,`request.update:${id}`,mutation,(d,i)=>{const req=d.requests.find(x=>x.requestId===id&&x.organizationId===ctx.organizationId);if(!req)throw new PortalError("request_not_found");this.requireApplicationAccess(ctx,req.applicationId,d,"manage");if(req.state!=="draft"&&req.state!=="needs_input")throw new PortalError("state_conflict");if(req.version!==mutation.expectedVersion)throw new PortalError("version_conflict");const caps=uniqCaps(i.capabilities);if(!caps.length||caps.some(x=>!PORTAL_CAPABILITIES.includes(x)))throw new PortalError("input_invalid");req.requestedCapabilities=caps;req.justification=i.justification.trim();req.reviewReason=null;req.reviewerUserId=null;req.version++;req.updatedAt=this.#now();this.#op(d,ctx,"request.update","access_request",id,req.state,req.state);return req;});}
  changeGrantCapabilities(ctx:PortalContext,id:string,mutation:PortalMutation<{capabilities:readonly PortalCapabilityId[];expiresAt?:string|null}>){return this.#mutate(ctx,`grant.scope:${id}`,mutation,(d,i)=>{if(ctx.identity.platformRole!=="operator")throw new PortalError("operator_required");const g=d.grants.find(x=>x.grantId===id&&(ctx.organizationId===null||x.organizationId===ctx.organizationId));if(!g||g.state!=="active"||g.version!==mutation.expectedVersion)throw new PortalError("version_conflict");const caps=uniqCaps(i.capabilities);if(!caps.length||caps.some(x=>!g.capabilities.includes(x)))throw new PortalError("grant_scope_expansion_forbidden");if(i.expiresAt!==undefined&&(i.expiresAt===null||!Number.isFinite(Date.parse(i.expiresAt))||Date.parse(i.expiresAt)<=Date.parse(this.#now())||(g.expiresAt!==null&&Date.parse(i.expiresAt)>Date.parse(g.expiresAt))))throw new PortalError("grant_expiry_invalid");g.capabilities=caps;g.expiresAt=i.expiresAt===undefined?g.expiresAt:i.expiresAt;g.version++;g.updatedAt=this.#now();this.#op(d,{...ctx,organizationId:g.organizationId},"grant.scope","grant",id,"active","active");return g;});}
  requireApplicationAccess(ctx:PortalContext,applicationId:string,data=this.#repo.read(),action:"read"|"manage"|"credential"="read"):Application{const m=this.#requireMember(data,ctx);const app=data.applications.find(x=>x.applicationId===applicationId&&x.organizationId===ctx.organizationId);if(!app)throw new PortalError("application_not_found");if(action==="credential"&&ctx.identity.platformRole!==null)throw new PortalError("application_access_denied");if(action!=="read"&&m.role==="viewer")throw new PortalError("application_access_denied");if((m.role==="developer"||action==="credential")&&app.ownerUserId!==ctx.identity.userId)throw new PortalError("application_access_denied");return app;}
  getEffectiveGrant(ctx:PortalContext,applicationId:string,capabilityId:PortalCapabilityId):Grant|null{this.requireApplicationAccess(ctx,applicationId);const now=Date.parse(this.#now());return this.#repo.read().grants.filter(x=>x.organizationId===ctx.organizationId&&x.applicationId===applicationId&&x.capabilities.includes(capabilityId)&&x.state==="active"&&(x.expiresAt===null||Date.parse(x.expiresAt)>now)).sort((a,b)=>b.version-a.version)[0]??null;}
  requireApplicationCreation(ctx:PortalContext,ownerUserId:string):Readonly<{organizationId:string;tenantId:string}>{const data=this.#repo.read();this.#requireMember(data,ctx,["owner","admin","developer"]);const org=data.organizations.find(x=>x.organizationId===ctx.organizationId&&x.status==="active");const owner=data.memberships.find(x=>x.organizationId===ctx.organizationId&&x.userId===ownerUserId&&x.status==="active"&&x.role!=="viewer");if(!org||!owner)throw new PortalError("application_creation_denied");return Object.freeze({organizationId:org.organizationId,tenantId:org.tenantId});}
  requireGrantProvisioning(ctx:PortalContext,grantId:string):Readonly<{grantId:string;version:number;organizationId:string;tenantId:string;applicationId:string;clientId:string;environment:"test"|"production";capabilities:readonly PortalCapabilityId[]}>{if(ctx.identity.platformRole!=="operator")throw new PortalError("operator_required");const data=this.#repo.read();const grant=data.grants.find(x=>x.grantId===grantId&&x.state==="provisioning"&&(ctx.organizationId===null||x.organizationId===ctx.organizationId));const org=grant?data.organizations.find(x=>x.organizationId===grant.organizationId&&x.status==="active"):undefined;const app=grant?data.applications.find(x=>x.applicationId===grant.applicationId&&x.organizationId===grant.organizationId&&x.status==="active"):undefined;if(!grant||!org||!app)throw new PortalError("grant_not_provisionable");return Object.freeze({grantId:grant.grantId,version:grant.version,organizationId:org.organizationId,tenantId:org.tenantId,applicationId:app.applicationId,clientId:app.clientId,environment:app.environment,capabilities:Object.freeze([...grant.capabilities])});}
  requireBusinessApplication(clientId:string):Readonly<{organizationId:string;tenantId:string;applicationId:string;clientId:string;environment:"test"|"production";ownerUserId:string}>{
    const data=this.#repo.read(); const applications=data.applications.filter(x=>x.clientId===clientId&&x.status==="active");
    if(applications.length!==1)throw new PortalError("business_application_denied");
    const app=applications[0]!;const org=data.organizations.find(x=>x.organizationId===app.organizationId&&x.status==="active");
    const owner=data.memberships.find(x=>x.organizationId===app.organizationId&&x.userId===app.ownerUserId&&x.status==="active"&&["owner","admin","developer"].includes(x.role));
    if(!org||!owner)throw new PortalError("business_application_denied");
    return Object.freeze({organizationId:org.organizationId,tenantId:org.tenantId,applicationId:app.applicationId,clientId:app.clientId,environment:app.environment,ownerUserId:app.ownerUserId});
  }
  getBusinessApplicationReviewSummaries(ctx:PortalContext,clientIds:readonly string[]):readonly PortalBusinessReviewApplicationSummary[]{
    if(ctx.organizationId!==null||!ctx.identity.emailVerified||!ctx.identity.platformRole||!["reviewer","operator"].includes(ctx.identity.platformRole))throw new PortalError("reviewer_required");
    const requested=[...new Set(clientIds)];if(requested.length>400||requested.some(clientId=>!identifier(clientId)))throw new PortalError("input_invalid");
    const data=this.#repo.read(),byClient=new Map(data.applications.filter(app=>requested.includes(app.clientId)).map(app=>[app.clientId,app]));
    return Object.freeze(requested.flatMap(clientId=>{const app=byClient.get(clientId);if(!app)return[];const org=data.organizations.find(value=>value.organizationId===app.organizationId);if(!org)return[];return[Object.freeze({organizationId:org.organizationId,organizationName:org.displayName,organizationStatus:org.status,tenantId:org.tenantId,applicationId:app.applicationId,applicationName:app.name,applicationStatus:app.status,clientId:app.clientId})];}));
  }
  requireMachineGrants(clientId:string,capabilityIds:readonly PortalCapabilityId[]):Readonly<{organizationId:string;tenantId:string;applicationId:string;clientId:string;capabilities:readonly PortalCapabilityId[]}>{
    const data=this.#repo.read(); const requested=uniqCaps(capabilityIds); const app=data.applications.find(x=>x.clientId===clientId&&x.status==="active");
    if(!app||requested.length===0||requested.some(x=>!PORTAL_CAPABILITIES.includes(x)))throw new PortalError("machine_authorization_denied");
    const org=data.organizations.find(x=>x.organizationId===app.organizationId&&x.status==="active");if(!org)throw new PortalError("machine_authorization_denied");
    const owner=data.memberships.find(x=>x.organizationId===app.organizationId&&x.userId===app.ownerUserId&&x.status==="active"&&["owner","admin","developer"].includes(x.role));if(!owner)throw new PortalError("machine_authorization_denied");
    const now=Date.parse(this.#now()); const covered=new Set(data.grants.filter(x=>x.organizationId===org.organizationId&&x.applicationId===app.applicationId&&x.state==="active"&&(x.expiresAt===null||Date.parse(x.expiresAt)>now)).flatMap(x=>x.capabilities));
    if(requested.some(x=>!covered.has(x)))throw new PortalError("machine_authorization_denied");
    return Object.freeze({organizationId:org.organizationId,tenantId:org.tenantId,applicationId:app.applicationId,clientId,capabilities:Object.freeze(requested)});
  }
}
