import { pathToFileURL } from 'node:url';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const artifacts = resolve(process.env.PORTAL_ARTIFACTS || '.runtime/portal-browser');
await mkdir(artifacts, { recursive: true });
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const issues=[]; page.on('pageerror', e=>issues.push(e.message));
const base=process.env.PORTAL_BASE_URL || 'http://127.0.0.1:8882';
if(!['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname))throw new Error('Loopback fixture URL required');
const checks=[];
async function login(label){
 await page.goto(`${base}/console/#login`);await page.locator('[data-action=logout], .identity-list button').first().waitFor();
 const logout=page.getByRole('button',{name:'退出',exact:true});
 if(await logout.isVisible()){const response=page.waitForResponse(value=>value.request().method()==='POST'&&value.url().endsWith('/console/api/v1/logout'));await logout.click();await response;await page.goto(`${base}/console/#login`);await page.reload();await page.locator('.identity-list button').first().waitFor();}
 const identity=page.getByRole('button',{name:label});await identity.waitFor();const response=page.waitForResponse(value=>value.request().method()==='POST'&&value.url().endsWith('/console/api/v1/fixture-login'));await identity.click();await response;await page.locator('[data-action=logout]').first().waitFor();
 const selector=page.locator('#organization');if(await selector.count() && await selector.locator('option[value=org_fixture]').count() && await selector.inputValue()!=='org_fixture'){await selector.selectOption('org_fixture');await page.waitForURL('**/#home');await page.locator('[data-go=quote]').first().waitFor();}
}
async function go(hash){await page.goto(`${base}/console/#${hash}`);await page.locator('[data-action=logout]').first().waitFor();}
await login('企业开发者 developer@example.test');
await go('app-new');await page.getByLabel('应用名称').fill('集成验收 · 物流助手');await page.getByLabel('应用用途').fill('本地验收：核对受邀企业的货物计算与应用权限。');await page.getByRole('button',{name:'创建应用',exact:true}).click();
await page.getByRole('heading',{name:'集成验收 · 物流助手',exact:true}).waitFor();
const appId=decodeURIComponent(new URL(page.url()).hash.split('/')[1]);checks.push('application-created-without-key');
await go(`request-new/${appId}`);await page.getByRole('checkbox',{name:/货物计算/}).check();await page.getByRole('checkbox',{name:/装柜规划/}).check();await page.getByLabel('使用说明').fill('用于物流团队录单前的体积与重量校验，进行本地端到端验收。');await page.getByRole('button',{name:'保存草稿'}).click();await page.getByRole('button',{name:'提交审核',exact:true}).waitFor();
const reqId=decodeURIComponent(new URL(page.url()).hash.split('/')[1]);await page.getByRole('button',{name:'提交审核',exact:true}).click();await page.getByRole('button',{name:'撤回申请',exact:true}).waitFor();checks.push('draft-submit-readback');
await login('平台审核员 reviewer@example.test');await go(`request/${reqId}`);await page.getByLabel('审核结论').selectOption('needs_input');await page.getByLabel('审核说明').fill('请说明预期调用量。');await page.getByRole('button',{name:'提交审核结论'}).click();await page.getByText('审核意见：请说明预期调用量。').waitFor();checks.push('review-needs-input');
await login('企业开发者 developer@example.test');await go(`request-edit/${reqId}`);await page.getByLabel('使用说明').fill('内部物流录单校验，每日约100次，先验证货物计算。');await page.getByRole('button',{name:'保存修改'}).click();await page.getByRole('button',{name:'重新提交审核'}).click();await page.getByRole('button',{name:'撤回申请'}).waitFor();checks.push('edit-resubmit');
await login('平台审核员 reviewer@example.test');await go(`request/${reqId}`);await page.getByRole('checkbox',{name:/装柜规划/}).uncheck();await page.getByLabel('审核说明').fill('批准货物计算用于本地验收；装柜能力暂不批准。');await page.getByRole('button',{name:'提交审核结论'}).click();await page.getByText('审核意见：批准货物计算用于本地验收；装柜能力暂不批准。').waitFor();checks.push('partial-approval');
await login('平台运维管理员 operator@example.test');await go('grants');await page.getByRole('button',{name:'核对并开通'}).last().click();await page.getByRole('button',{name:'管理授权'}).last().waitFor();checks.push('provision-readback');
await login('企业开发者 developer@example.test');await go(`credential-new/${appId}`);await page.getByLabel('凭证名称').fill('本地验收 Key');await page.getByRole('button',{name:'创建并显示 Key'}).click();await page.locator('#secret-dialog[open]').waitFor();
const key=await page.locator('#secret-value').innerText();assert.match(key,/^lmcpk_/);await page.getByRole('button',{name:'已保存，完成'}).click();await page.locator('#secret-dialog[open]').waitFor({state:'hidden'});assert.equal(await page.locator('#secret-value').innerText(),'');checks.push('secret-one-time-ack-cleared');
await go('diagnostics');await page.getByRole('heading',{name:'接口调试',exact:true}).waitFor();await page.getByRole('button',{name:'验证调用',exact:true}).waitFor();checks.push('legacy-diagnostics-route');
const exchange = await fetch(`${base}/access/v1/token/exchange`,{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Authorization:`ApiKey ${key}`},body:JSON.stringify({schema_version:'2026-08-27.v1',requested_tool_names:['cargo.calculate']})});const tokenResult=await exchange.json();assert.equal(exchange.status,200,JSON.stringify(tokenResult));const token=tokenResult.data?.access_token||tokenResult.access_token;assert.ok(token);checks.push('key-exchange');
const source=(id,rule)=>({source_id:id,source_type:rule?'internal_system':'user_input',system:rule?'quote-rule-registry':'mcp-gateway',locator:rule?'channel/CAQ-HP/dimensional-weight':'opaque://request/acceptance',version:rule?'CAQ-HP@2026-01-01':'input@2026-08-11',retrieved_at:'2026-08-11T09:00:00Z',authority:rule?'authoritative':'user_provided',content_hash:`sha256:${id}`});
const input={schema_version:'2026-08-11.v1',version:'cargo.calculate@2026-08-11.v1',cargo_lines:[{version:'cargo-line@2026-08-11.v1',line_id:'line_1',description:'local acceptance cartons',quantity:2,quantity_unit:'carton',package_type:'carton',unit_weight:{value:'12.5',unit:'kg'},dimensions:[{length:{value:'60',unit:'cm'},width:{value:'50',unit:'cm'},height:{value:'40',unit:'cm'},quantity:2}],stackable:true,fragile:false,sensitive:false,source_ref_ids:['src_input_1']}],dimensional_divisor:null,bubble_rule:{channel:'CAQ-HP',mode:'full',ratio:null,rule_version:'CAQ-HP@2026-01-01',source_ref_ids:['src_rule_1'],density:{value:'1000',unit:'kg_per_cbm'},unit:'kg',rounding:{mode:'none',decimals:6}},channel_code:'CAQ-HP',source_refs:[source('src_input_1',false),source('src_rule_1',true)]};
const call=await fetch(`${base}/api/fixture/v1/tools/cargo.calculate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({input})});const result=await call.json();assert.equal(result.status,'success',JSON.stringify(result));checks.push('real-cargo-calculation');
await go(`app/${appId}`);await page.getByText('本地验收 Key',{exact:true}).waitFor();await page.screenshot({path:resolve(artifacts, 'portal-app-desktop.png'),fullPage:true});
for(const width of [390,320,768]){await page.setViewportSize({width,height:900});await go('app-new');await page.getByLabel('应用名称').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width}`);await page.screenshot({path:resolve(artifacts, `portal-form-${width}.png`),fullPage:true});}checks.push('responsive-390-320-768');
await page.setViewportSize({width:1440,height:1000});await login('企业所有者 owner@example.test');await go('grants');await page.locator('tr').filter({hasText:'集成验收 · 物流助手'}).filter({has:page.getByRole('button',{name:'管理授权'})}).last().getByRole('button',{name:'管理授权'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'暂停授权',exact:true}).click();await page.getByRole('button',{name:'暂停授权',exact:true}).waitFor({state:'hidden'});
const blocked=await fetch(`${base}/api/fixture/v1/tools/cargo.calculate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({input})});const denial=await blocked.json();assert.equal(denial.status,'blocked');checks.push('existing-token-rejected-after-grant-suspend');
await login('业务员 sales@example.test');await go('members');const invitation=page.getByRole('button',{name:'接受邀请'});if(await invitation.isVisible())await invitation.click();await page.getByRole('heading',{name:'企业成员',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'邀请成员',exact:true}).count(),0);checks.push('viewer-invite-no-admin-actions');
assert.equal(issues.length,0,JSON.stringify(issues));console.log(JSON.stringify({checks,calculationStatus:result.status,cargoData:result.data,consoleErrors:issues}));await browser.close();
