import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
const imported = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const { chromium } = imported.default || imported;
const fs=require('node:fs');const assert=require('node:assert/strict');
const base=process.env.CASES_FIXTURE_ORIGIN || 'http://127.0.0.1:8906',out=process.env.CASES_SCREENSHOTS || '.impeccable/review/cases';
if(new URL(base).protocol!=='http:'||!['127.0.0.1','[::1]'].includes(new URL(base).hostname))throw new Error('loopback_fixture_required');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{})});const customer=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),ops=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[],checks=[];const page=await customer.newPage(),admin=await ops.newPage();for(const p of[page,admin])p.on('pageerror',e=>errors.push(e.message));
async function login(context,id){let r=await context.request.get(base+'/console/api/v1/session'),s=await r.json();r=await context.request.post(base+'/console/api/v1/fixture-login',{headers:{origin:base,'x-csrf-token':s.csrf_token,'idempotency-key':require('node:crypto').randomUUID()},data:{identity_id:id}});assert.equal(r.status(),200);}
async function capture(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:`${out}/${name}.png`,fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} overflow`);checks.push(name);}
await login(ops,'fixture-operator');await admin.goto(base+'/console/#operations');await admin.getByRole('heading',{name:'还没有收到询价'}).waitFor();await capture(admin,'management-empty');
await page.goto(base+'/inquiry/');await page.locator('input[name="services"][value="ocean"]').check();await page.getByRole('button',{name:/下一步：运输信息/}).click();await page.locator('input[name=transportMode][value=fcl]').check();await page.locator('#origin').fill('上海');await page.locator('#destination').fill('温哥华');await page.locator('#product').fill('合成验收货物 · 家具');await page.locator('#containerType').selectOption('40HQ');await page.locator('#containerCount').fill('1');await page.getByRole('button',{name:/下一步：确认询价/}).click();await page.locator('#contactName').fill('验收客户');await page.locator('#email').fill('acceptance@example.test');await page.locator('#consent').check();await page.getByRole('button',{name:'提交询价'}).click();await page.getByRole('link',{name:'登录账号 ↗'}).waitFor();checks.push('anonymous draft retained without creating record');await login(customer,'fixture-sales');await page.getByRole('button',{name:'提交询价'}).click();await page.getByRole('heading',{name:'需求已提交'}).waitFor();await capture(page,'submitted');await page.getByRole('link',{name:'查看询价进度'}).click();await page.getByRole('heading',{name:'需求资料'}).waitFor();const caseUrl=page.url();
await admin.getByRole('button',{name:'刷新进度'}).click();await admin.locator('.case-card').waitFor();await capture(admin,'management-desktop');await admin.setViewportSize({width:1920,height:1080});await capture(admin,'user-1920');await admin.setViewportSize({width:1440,height:1000});await admin.locator('.case-card').first().click();await admin.getByRole('heading',{name:'处理这票询价'}).waitFor();await admin.locator('#case-status').selectOption('needs_input');await admin.locator('#case-public').fill('已收到您的运输需求，请补充外包装方式和预计出货日期。');await admin.locator('#case-internal').fill('内部验收备注，仅后台可见。');await capture(admin,'detail-desktop');await admin.getByRole('button',{name:'保存并同步进展'}).click();await admin.getByText('内部验收备注，仅后台可见。',{exact:true}).waitFor();
await page.reload();await page.getByRole('heading',{name:'补充资料',exact:true}).waitFor();assert.equal(await page.locator('.case-question').textContent().then(t=>t.includes('请补充外包装方式')),true);assert.equal(await page.getByText('内部验收备注，仅后台可见。',{exact:true}).count(),0);await capture(page,'customer-desktop');await page.setViewportSize({width:390,height:844});await capture(page,'customer-mobile');await admin.setViewportSize({width:390,height:844});await capture(admin,'management-mobile');await page.locator('#case-message').fill('纸箱包装，预计 9 月下旬出货。');await page.getByRole('button',{name:'提交补充资料'}).click();await page.getByText('纸箱包装，预计 9 月下旬出货。',{exact:true}).waitFor();await admin.reload();await admin.getByText('纸箱包装，预计 9 月下旬出货。',{exact:true}).waitFor();checks.push('customer reply read back by operator');
await page.goto(base+'/console/#cases');await page.locator('.case-card').waitFor();await capture(page,'list-mobile');await page.getByRole('button',{name:'账号菜单'}).click();await page.locator('#account-menu [data-go=cases]').waitFor();checks.push('account menu');assert.equal(errors.length,0);fs.writeFileSync(out+'/qa.json',JSON.stringify({checks,errors,caseUrl,environment:'isolated synthetic fixture; no production writes'},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
