import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';
import { loginFixture } from './fixture-login.mjs';
const imported = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const { chromium } = imported.default || imported;
const base = process.env.PORTAL_BASE_URL || 'http://127.0.0.1:8907';
assert.ok(new URL(base).protocol === 'http:' && ['127.0.0.1', 'localhost', '[::1]'].includes(new URL(base).hostname));
const out = process.env.PORTAL_ARTIFACTS || '.runtime/login-browser';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_EXECUTABLE_PATH ? { executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH } : {}) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
try {
 await page.goto(`${base}/console/#login`);
 await page.locator('.login-submit:not([disabled])').waitFor();
 assert.equal(await page.locator('.identity-list').count(), 0);
 assert.equal(await page.locator('.local-login-help[open]').count(), 0);
 const previous = await page.locator('form').getAttribute('data-captcha-id');
 const loaded = page.waitForResponse(response => response.url().endsWith('/login/captcha'));
 await page.getByRole('button', { name: '更换图形验证码' }).click();
 const fresh = (await (await loaded).json()).data;
 await page.locator('.login-submit:not([disabled])').waitFor();
 assert.notEqual(fresh.captcha_id, previous);
 assert.equal(await page.locator('form').getAttribute('data-captcha-id'), fresh.captcha_id);
 assert.equal(await page.locator('.captcha-image').getAttribute('src'), fresh.image);
 checks.push('refresh displays the server challenge paired with its ID');
 await page.route('**/login/captcha', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ status: 'unavailable', reason_codes: ['unavailable'] }) }));
 await page.getByRole('button', { name: '更换图形验证码' }).click();
 await page.getByText('加载失败，点击重试', { exact: true }).waitFor();
 assert.equal(await page.locator('.login-submit').isDisabled(), true);
 assert.equal(await page.locator('.captcha-image').isVisible(), false);
 await page.screenshot({ path: `${out}/refresh-error.png`, fullPage: true });
 await page.unroute('**/login/captcha');
 await page.getByRole('button', { name: '更换图形验证码' }).click();
 await page.locator('.login-submit:not([disabled])').waitFor();
 checks.push('failed refresh stays visible and retry recovers');
 await page.getByLabel('账号', { exact: true }).fill('admin');
 await page.getByLabel('密码', { exact: true }).fill('invalid');
 await page.getByLabel('验证码', { exact: true }).fill('00000');
 await page.getByRole('button', { name: '登录', exact: true }).click();
 await page.locator('.form-error:not([hidden])').waitFor();
 assert.equal(await page.getByLabel('密码', { exact: true }).inputValue(), '');
 assert.equal(await page.getByLabel('验证码', { exact: true }).inputValue(), '');
 checks.push('rejected login clears password and captcha');
 await loginFixture(page, base, '企业所有者 owner@example.test');
 await page.goto(`${base}/console/#member-new`);
 await page.locator('#role').waitFor();
 assert.deepEqual(await page.locator('#role option').allTextContents(), ['业务用户', '管理员']);
 await page.goto(`${base}/console/#member-edit/fixture-developer`);
 await page.locator('#role').waitFor();
 assert.deepEqual(await page.locator('#role option').allTextContents(), ['业务用户', '管理员', '业务用户（接口权限）']);
 assert.equal(await page.locator('#role').inputValue(), 'developer');
 checks.push('two normal invitation roles and existing developer permission preserved');
 assert.deepEqual(errors, []);
 await writeFile(`${out}/qa.json`, JSON.stringify({ checks, errors, environment: 'loopback fixture only' }, null, 2));
 console.log(JSON.stringify({ checks, errors }));
} finally { await browser.close(); }
