"""Apply dedicated FreightClaw Chinese authentication flows through `ak shell`."""
import json,os
from django.db import transaction
from authentik.flows.models import Flow,FlowStageBinding
from authentik.stages.identification.models import IdentificationStage
from authentik.stages.password.models import PasswordStage
from authentik.stages.user_login.models import UserLoginStage
from authentik.stages.user_write.models import UserWriteStage
from authentik.stages.prompt.models import Prompt,PromptStage
from authentik.stages.email.models import EmailStage
from authentik.stages.dummy.models import DummyStage
from authentik.policies.password.models import PasswordPolicy
from authentik.policies.expression.models import ExpressionPolicy
from authentik.policies.models import PolicyBinding
from authentik.providers.oauth2.models import OAuth2Provider
from authentik.core.models import Application
AUTH="freightclaw-cn-authentication";ENROLL="freightclaw-cn-enrollment";RECOVER="freightclaw-cn-recovery";SMTP=os.environ.get("FREIGHTCLAW_SMTP_READY")=="true"
def bind(flow,stage,order):FlowStageBinding.objects.update_or_create(target=flow,stage=stage,defaults={"order":order,"re_evaluate_policies":True,"evaluate_on_plan":False,"policy_engine_mode":"all"})
def policy(binding,value,order=0):PolicyBinding.objects.update_or_create(target=binding,policy=value,defaults={"order":order,"enabled":True,"negate":False,"timeout":30,"failure_result":False})
def flow(slug,name,title,designation):return Flow.objects.update_or_create(slug=slug,defaults={"name":name,"title":title,"designation":designation,"layout":"stacked","policy_engine_mode":"all","compatibility_mode":True})[0]
def prompt(name,key,label,kind,order):return Prompt.objects.update_or_create(name=name,defaults={"field_key":key,"label":label,"type":kind,"required":True,"placeholder":"","initial_value":"","order":order})[0]
with transaction.atomic():
 password,_=PasswordStage.objects.update_or_create(name="FreightClaw 密码校验",defaults={"backends":["authentik.core.auth.InbuiltBackend"],"failed_attempts_before_cancel":5,"allow_show_password":True})
 login,_=UserLoginStage.objects.update_or_create(name="FreightClaw 登录会话",defaults={"session_duration":"hours=12","remember_me_offset":"days=30"})
 strong,_=PasswordPolicy.objects.update_or_create(name="FreightClaw 强密码",defaults={"password_field":"password","check_static_rules":True,"check_zxcvbn":True,"zxcvbn_score_threshold":3,"length_min":12,"amount_uppercase":1,"amount_lowercase":1,"amount_digits":1,"amount_symbols":1,"error_message":"密码至少12位，并包含大小写字母、数字和符号"})
 enrollment=flow(ENROLL,"FreightClaw 邮箱注册","注册 FreightClaw 账号","enrollment");enroll_prompt,_=PromptStage.objects.get_or_create(name="FreightClaw 注册资料");enroll_prompt.fields.set([prompt("FreightClaw 注册邮箱","email","企业邮箱","email",10),prompt("FreightClaw 注册姓名","name","姓名","text",20),prompt("FreightClaw 注册密码","password","设置密码","password",30)]);enroll_prompt.validation_policies.set([strong])
 enroll_write,_=UserWriteStage.objects.update_or_create(name="FreightClaw 创建邮箱用户",defaults={"user_creation_mode":"create_when_required","create_users_as_inactive":False,"user_type":"external","user_path_template":"users/freightclaw"})
 recovery=flow(RECOVER,"FreightClaw 找回密码","找回密码","recovery");recover_identify,_=IdentificationStage.objects.update_or_create(name="FreightClaw 找回账号",defaults={"user_fields":["email"],"case_insensitive_matching":True,"show_matched_user":False,"pretend_user_exists":True,"enable_remember_me":False});recover_identify.sources.set([]);recover_prompt,_=PromptStage.objects.get_or_create(name="FreightClaw 重设密码");recover_prompt.fields.set([prompt("FreightClaw 新密码","password","设置新密码","password",10)]);recover_prompt.validation_policies.set([strong]);recover_write,_=UserWriteStage.objects.update_or_create(name="FreightClaw 保存新密码",defaults={"user_creation_mode":"never_create","create_users_as_inactive":False,"user_type":"external"})
 email_defaults={"use_global_settings":False,"host":os.environ.get("FREIGHTCLAW_SMTP_HOST","localhost"),"port":int(os.environ.get("FREIGHTCLAW_SMTP_PORT","25")),"username":os.environ.get("FREIGHTCLAW_SMTP_USERNAME",""),"password":os.environ.get("FREIGHTCLAW_SMTP_PASSWORD",""),"use_tls":os.environ.get("FREIGHTCLAW_SMTP_TLS","true")=="true","use_ssl":os.environ.get("FREIGHTCLAW_SMTP_SSL","false")=="true","timeout":10,"from_address":os.environ.get("FREIGHTCLAW_SMTP_FROM","noreply@freightclaw.net"),"recovery_max_attempts":3,"recovery_cache_timeout":"minutes=15","activate_user_on_success":False,"token_expiry":"minutes=20","subject":"FreightClaw 邮箱验证"}
 verify_email,_=EmailStage.objects.update_or_create(name="FreightClaw 验证企业邮箱",defaults={**email_defaults,"template":"email/account_confirmation.html"});recover_email,_=EmailStage.objects.update_or_create(name="FreightClaw 找回密码邮件",defaults={**email_defaults,"subject":"FreightClaw 重设密码","template":"email/password_reset.html"})
 username,_=ExpressionPolicy.objects.update_or_create(name="FreightClaw 邮箱生成用户名",defaults={"expression":"data=request.context['prompt_data']\nemail=data['email'].strip().lower()\ndata['email']=email\ndata['username']=email\nreturn True"})
 verified,_=ExpressionPolicy.objects.update_or_create(name="FreightClaw 邮箱验证完成",defaults={"expression":f"user=request.context.get('pending_user')\ntoken=request.context.get('is_restored')\nbinding=request.obj\nif not {SMTP!r} or user is None or user.pk is None or token is None or binding is None:\n    return False\nif token.__class__.__name__ != 'FlowToken' or token.user_id != user.pk or token.flow_id != binding.target_id:\n    return False\nif user.is_active is not True:\n    return False\nattrs=dict(user.attributes)\nattrs['email_verified']=True\nuser.attributes=attrs\nuser.save(update_fields=['attributes'])\nreturn True"})
 needs_verification,_=ExpressionPolicy.objects.update_or_create(name="FreightClaw 需要邮箱验证",defaults={"expression":f"user=request.context.get('pending_user')\nreturn {SMTP!r} and user is not None and user.attributes.get('email_verified') is not True"})
 verification_marker,_=DummyStage.objects.update_or_create(name="FreightClaw 写入邮箱验证状态",defaults={"throw_error":False})
 for target in (enrollment,recovery):FlowStageBinding.objects.filter(target=target).delete()
 bind(enrollment,enroll_prompt,10);write_binding=FlowStageBinding.objects.create(target=enrollment,stage=enroll_write,order=20,re_evaluate_policies=True,evaluate_on_plan=False,policy_engine_mode="all");policy(write_binding,username);bind(enrollment,verify_email,30);verified_binding=FlowStageBinding.objects.create(target=enrollment,stage=verification_marker,order=40,re_evaluate_policies=True,evaluate_on_plan=False,policy_engine_mode="all");policy(verified_binding,verified);bind(enrollment,login,50)
 bind(recovery,recover_identify,10);bind(recovery,recover_email,20);bind(recovery,recover_prompt,30);bind(recovery,recover_write,40);recover_verified_binding=FlowStageBinding.objects.create(target=recovery,stage=verification_marker,order=50,re_evaluate_policies=True,evaluate_on_plan=False,policy_engine_mode="all");policy(recover_verified_binding,verified);bind(recovery,login,60)
 auth=flow(AUTH,"FreightClaw 中文登录","登录 FreightClaw","authentication");identify,_=IdentificationStage.objects.update_or_create(name="FreightClaw 邮箱与密码",defaults={"user_fields":["email"],"password_stage":password,"case_insensitive_matching":True,"show_matched_user":False,"pretend_user_exists":True,"enable_remember_me":True,"recovery_flow":recovery if SMTP else None,"enrollment_flow":enrollment if SMTP else None});identify.sources.set([]);FlowStageBinding.objects.filter(target=auth).delete();bind(auth,identify,10);auth_email_binding=FlowStageBinding.objects.create(target=auth,stage=verify_email,order=20,re_evaluate_policies=True,evaluate_on_plan=False,policy_engine_mode="all");policy(auth_email_binding,needs_verification);auth_verified_binding=FlowStageBinding.objects.create(target=auth,stage=verification_marker,order=30,re_evaluate_policies=True,evaluate_on_plan=False,policy_engine_mode="all");policy(auth_verified_binding,verified,10);bind(auth,login,100)
 provider=OAuth2Provider.objects.get(name="freightclaw-portal");provider.authentication_flow=auth;provider.save(update_fields=["authentication_flow"]);app=Application.objects.get(slug="freightclaw-portal");app.name="FreightClaw 工作台";app.meta_description="企业物流与关务工作台";app.save(update_fields=["name","meta_description"])
print("RESULT "+json.dumps({"authentication_flow":AUTH,"smtp_configured":SMTP,"recovery_link_enabled":SMTP,"self_service_enrollment_enabled":SMTP,"email_verified_only_after_email_stage":True},ensure_ascii=False))
