import { it, expect } from 'vitest';
import { customsRelease, validateCustomsDataset } from '../../services/customs-native/publication';
import { createNativeCustomsClients } from '../../services/customs-native/client';
import { NativeCustomsEngine, releaseRepository } from '../../services/customs-native/engine';
import { dataset } from './publication-fixture';
const query={query:'7323930090',codeCountry:'CA',ruleDate:'2026-09-07',attributes:{originCountry:'CN',vacuumInsulated:'no',contains_steel_aluminum:'no'}};
it('runs migrated query offline with the existing full Portal contract and immutable identity',async()=>{expect(validateCustomsDataset(dataset)).toEqual([]);const release=customsRelease(dataset,'native-test-release','2026-09-07T12:00:00.000Z');const client=createNativeCustomsClients({current:()=>release});const r=await client.customsClient.query({input:query,actor:{type:'user',id:'user1'},requestId:'req_native1234'});expect(r.data,r.reason_codes.join(',')).not.toBeNull();expect(r.data).toMatchObject({contractVersion:'riskcustoms-query.v2',testData:false,delegatedActor:{ref:'user1'},dataStatus:{ready:true,serviceVersion:'freightclaw-native-customs/1'}});});
it('preserves test-data, snapshot integrity, changed-release and no-result gates',async()=>{const release=customsRelease(dataset,'native-test-release','2026-09-07T12:00:00.000Z');for(const bad of [{...release,snapshot:{...release.snapshot,test_data:1}},{...release,snapshot:{...release.snapshot,gate_report_sha256:'b'.repeat(64)}}])expect((await new NativeCustomsEngine({current:()=>bad}).query({...query,attributes:{originCountry:'CN'}})).status).toBe('unavailable');expect((await new NativeCustomsEngine({current:()=>release}).query({...query,query:'9999999999',attributes:{originCountry:'CN'}})).status).not.toBe('success');expect(customsRelease({...dataset,test_data:true},'test','2026-09-07T12:00:00.000Z').snapshot.test_data).toBe(1);});
it('keeps chapter99-linked rules and excludes expired data without latest-prior fallback',async()=>{const release=customsRelease(dataset,'native-test-release','2026-09-07T12:00:00.000Z'),rule={...release.tariffs[0]!,code_match_type:'chapter99_link' as const};const repo=releaseRepository({...release,tariffs:[rule]});expect(await repo.findTariffRules(rule.country,rule.code,'2026-09-07')).toHaveLength(1);expect(await releaseRepository({...release,tariffs:[{...rule,effective_to:'2026-09-06'}]}).findTariffRules(rule.country,rule.code,'2026-09-07')).toEqual([]);});
