import {execFileSync} from 'node:child_process';
import {it,expect,afterEach} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {CustomsPackages} from '../../services/customs-native/packages';
import {NativeAdminStore} from '../../services/access-gateway/portal/native-admin';
import type {PortalService} from '../../services/access-gateway/portal/service';
import type {PortalContext} from '../../services/access-gateway/portal/contracts';
import {dataset} from './publication-fixture';
const cleanup:(()=>void)[]=[];afterEach(()=>cleanup.splice(0).forEach(f=>f()));
const ctx:PortalContext={organizationId:'org',identity:{userId:'owner',displayName:'Owner',email:'owner@example.test',emailVerified:true,platformRole:null}};
const portal={getState:(c:PortalContext)=>({data:{current_organization:{status:'active'},memberships:[{organizationId:c.organizationId,userId:c.identity.userId,role:c.identity.userId==='viewer'?'viewer':'owner',status:'active'}]}})} as unknown as PortalService;
function setup(ready:boolean){const root=mkdtempSync(join(tmpdir(),'customs-package-')),inbox=join(root,'inbox');mkdirSync(inbox);const file=join(inbox,'snapshot.sqlite'),db=new DatabaseSync(file);const write=(table:string,rows:Record<string,unknown>[])=>{const keys=Object.keys(rows[0]??{id:'',release_id:''});db.exec('CREATE TABLE '+table+' ('+keys.map(k=>'"'+k+'" '+(typeof rows[0]?.[k]==='number'?'INTEGER':'TEXT')).join(',')+')');for(const row of rows)db.prepare('INSERT INTO '+table+' VALUES('+keys.map(()=>'?').join(',')+')').run(...keys.map(k=>row[k] as string|number|null));};const source=dataset.sources.map(s=>({...s,status:ready?'published':'staged'}));write('source_release',source);const raw=(rows:readonly object[])=>rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>!k.startsWith('release_')||k==='release_id')));write('nomenclature',raw(dataset.nomenclature));write('tariff_rule',raw(dataset.tariffs));write('trade_measure',raw(dataset.measures));write('regulatory_requirement',raw(dataset.requirements));write('publication_snapshot',[{id:'snapshot-fixture',evaluated_at:new Date().toISOString(),rule_date:'2026-09-07',ready:ready?1:0,test_data:0,release_ids_json:JSON.stringify(source.map(s=>s.id)),approval_ids_json:JSON.stringify(ready?['isolated-test-approval']:[]),reasons_json:JSON.stringify(ready?[]:['review_required']),gate_report_sha256:'a'.repeat(64),last_source_check_at:new Date().toISOString()}]);db.close();const store=new NativeAdminStore(join(root,'native.sqlite')),svc=new CustomsPackages(store,portal,inbox);store.packages=svc;cleanup.push(()=>{store.close();rmSync(root,{recursive:true,force:true});});return {svc,store,root,file,input:{filename:'snapshot.sqlite',sha256:createHash('sha256').update(readFileSync(file)).digest('hex'),label:'Isolated synthetic package'}};}
it('imports the full snapshot as blocked and never promotes staged source rows',async()=>{const {svc,input}=setup(false);const result=await svc.import(ctx,input,randomUUID());expect(result.items[0]?.state).toBe('blocked');expect(result.items[0]?.counts.nomenclature).toBe(dataset.nomenclature.length);expect(svc.browse(ctx,{selection:'draft',collection:'nomenclature',limit:1}).rows).toHaveLength(1);expect(svc.browse(ctx,{selection:'published'}).rows).toHaveLength(0);expect(svc.current('org','2026-09-08')).toBeNull();await expect(svc.publish(ctx,{id:result.items[0]!.id,sha256:input.sha256,expected_active:null,confirmation:'reviewed_sources_and_conditions'},randomUUID())).rejects.toThrow('customs_package_not_ready');});
it('binds hash and tenant, activates ready snapshots, queries SQL rows and disables without fallback',async()=>{const {svc,store,input}=setup(true);const result=await svc.import(ctx,input,randomUUID()),id=result.items[0]!.id;expect(result.items[0]?.state).toBe('ready');await expect(svc.publish({...ctx,organizationId:'other'},{id,sha256:input.sha256,expected_active:null,confirmation:'reviewed_sources_and_conditions'},randomUUID())).rejects.toThrow('customs_package_not_found');await svc.publish(ctx,{id,sha256:input.sha256,expected_active:null,confirmation:'reviewed_sources_and_conditions'},randomUUID());const release=store.customsReader('org').current('2026-09-08');expect(release?.release_id).toBe(id);const row=dataset.nomenclature[0]!;expect((await release!.repository!.findExactCode(row.country,row.code,'2026-09-08')).length).toBeGreaterThan(0);svc.disable(ctx,{expected_active:id},randomUUID());expect(svc.hasSelection('org')).toBe(true);expect(store.customsReader('org').current('2026-09-08')).toBeNull();});
it('rejects a mismatched checksum, path traversal, non-manager and cross-scope access',async()=>{const {svc,input}=setup(false);await expect(svc.import(ctx,{...input,sha256:'0'.repeat(64)},randomUUID())).rejects.toThrow('customs_package_hash_mismatch');await expect(svc.import(ctx,{...input,filename:'../snapshot.sqlite'},randomUUID())).rejects.toThrow();await expect(svc.import({...ctx,identity:{...ctx.identity,userId:'viewer'}},input,randomUUID())).rejects.toThrow('native_management_denied');const key=randomUUID(),one=await svc.import(ctx,input,key),two=await svc.import(ctx,input,key);expect(two.items[0]!.id).toBe(one.items[0]!.id);expect(svc.list({...ctx,organizationId:'other'}).items).toEqual([]);});

it('exports only regulatory data and preserves an unready snapshot',()=>{const {root,file}=setup(false);const source=new DatabaseSync(file);source.exec("CREATE TABLE customer_secrets(value TEXT);INSERT INTO customer_secrets VALUES('not-for-export')");source.close();const output=join(root,'sanitized.sqlite');const result=JSON.parse(execFileSync('python3',['deploy/scripts/export-customs-snapshot.py','--source',file,'--output',output],{encoding:'utf8'})) as {counts:Record<string,number>;publication_status_preserved:boolean};expect(result.counts.customer_secrets).toBeUndefined();expect(result.publication_status_preserved).toBe(true);const db=new DatabaseSync(output,{readOnly:true});expect(db.prepare('SELECT ready FROM publication_snapshot').get()!.ready).toBe(0);expect(db.prepare("SELECT name FROM sqlite_master WHERE name='customer_secrets'").get()).toBeUndefined();db.close();});

it('replays an import even when the inbox file is gone and leaves no duplicate snapshot',async()=>{const {svc,input,file}=setup(false);const key=randomUUID();const first=await svc.import(ctx,input,key);rmSync(file);expect(await svc.import(ctx,input,key)).toEqual(first);expect(readdirSync(svc.directory)).toHaveLength(1);});
it('closes queries when an active snapshot cannot be read after restart',async()=>{const {svc,store,input}=setup(true);const result=await svc.import(ctx,input,randomUUID()),id=result.items[0]!.id;await svc.publish(ctx,{id,sha256:input.sha256,expected_active:null,confirmation:'reviewed_sources_and_conditions'},randomUUID());rmSync(join(svc.directory,id+'.sqlite'));expect(store.customsReader('org').current('2026-09-08')).toBeNull();});
it('marks the new native format so older binaries refuse incompatible rollback',()=>{const {store}=setup(false);expect(store.db.prepare('PRAGMA user_version').get()!.user_version).toBe(2);});
