import { z } from 'zod';
export const VERSION='quote-documents@2026-09-08.v1';
const text=(n=200)=>z.string().trim().max(n);
export const decimal=z.string().regex(/^(?:0|[1-9][0-9]{0,9})(?:\.[0-9]{1,6})?$/u);
export const currency=z.enum(['USD','CAD','CNY']);
const date=z.iso.date();
export const feeSchema=z.object({id:z.string().uuid(),name:text().min(1),description:text(500).default(''),group:z.enum(['A','B','C']),quantity:decimal,unit:text(20).min(1),unit_price:decimal,currency,display:z.enum(['detail','hiddenIncluded','hiddenExcluded','merged']),merge_name:text().default(''),note:text(500).default('')}).strict().refine(f=>f.display!=='merged'||f.merge_name.length>0,{message:'合并费用必须填写显示名称'});
export const templateSchema=z.object({company_name:text().min(1),company_address:text(500),company_phone:text(50),company_email:text(254),terms:text(4000).min(1),fee_items:z.array(feeSchema).max(60)}).strict();
export const documentSchema=z.object({quote_no:text(80).min(1),customer_name:text().min(1),quote_date:date,valid_until:date,origin:text(),destination:text(),route_name:text(),job_no:text(80),so_no:text(80),container_no:text(80),remark:text(4000),exchange_rates:z.object({USD:decimal.nullable(),CAD:decimal.nullable()}).strict(),fee_items:z.array(feeSchema).min(1).max(60)}).strict().superRefine((d,c)=>{if(d.valid_until<d.quote_date)c.addIssue({code:'custom',message:'有效期早于报价日期'});if(new Set(d.fee_items.map(f=>f.id)).size!==d.fee_items.length)c.addIssue({code:'custom',message:'费用 ID 重复'});for(const rate of Object.values(d.exchange_rates))if(rate!==null&&/^0(?:\.0+)?$/u.test(rate))c.addIssue({code:'custom',message:'汇率必须大于零'});});
export const configSaveSchema=z.object({expected_version:z.number().int().min(0),input:templateSchema,confirmed:z.literal(true)}).strict();
export const previewSchema=z.object({input:documentSchema}).strict();
export const saveSchema=z.object({input:documentSchema,template_version:z.number().int().positive(),preview_hash:z.string().regex(/^[a-f0-9]{64}$/u),preview_expires_at:z.number().int().positive(),confirmed:z.literal(true)}).strict();
export const approveSchema=z.object({id:z.string().uuid(),expected_version:z.number().int().positive(),evidence_ref:text(500).min(1),evidence_version:text(100).min(1),review_notes:text(2000).min(1),confirmation:z.literal('human_verified_price_and_source')}).strict();
export const idSchema=z.object({id:z.string().uuid()}).strict();
export const listSchema=z.object({limit:z.number().int().min(1).max(100).default(30),before:z.number().int().positive().optional()}).strict();
export const quoteDocumentSchemas={'template':templateSchema,'input':documentSchema,'config-save':configSaveSchema,'preview':previewSchema,'save':saveSchema,'approve':approveSchema,'get':idSchema,'list':listSchema};
export type QuoteDocument=z.infer<typeof documentSchema>;
export type QuoteTemplate=z.infer<typeof templateSchema>;
const sha=z.string().regex(/^[a-f0-9]{64}$/u);
export const configViewSchema=z.object({version:z.number().int().nonnegative(),input:templateSchema.nullable()}).strict();
export const totalsSchema=z.object({rows:z.array(feeSchema.and(z.object({amount:z.string()}))).max(60),by_currency:z.object({USD:z.string(),CAD:z.string(),CNY:z.string()}).strict(),total_cny:z.string().nullable(),total_usd:z.string().nullable(),warnings:z.array(z.string()),calculation_version:z.literal('quote-documents-decimal-v1')}).strict();
// Rows are a closed extension of the validated fee input, with computed amount only.
export const calculatedFeeSchema=z.object({...feeSchema.shape,amount:z.string().regex(/^[0-9]+\.[0-9]{2}$/u)}).strict();
export const calculatedTotalsSchema=totalsSchema.extend({rows:z.array(calculatedFeeSchema).max(60)});
export const previewViewSchema=saveSchema.omit({confirmed:true}).extend({totals:calculatedTotalsSchema});
export const documentViewSchema=z.object({id:z.string().uuid(),version:z.number().int().positive(),state:z.enum(['draft','approved']),input:documentSchema,template:templateSchema,template_version:z.number().int().positive(),created_at:z.iso.datetime(),owner_id:z.string(),approval:z.object({evidence_ref:z.string(),evidence_version:z.string(),review_notes:z.string(),actor:z.string(),at:z.iso.datetime()}).strict().nullable()}).strict();
export const documentListViewSchema=z.object({items:z.array(documentViewSchema.pick({id:true,version:true,state:true,created_at:true}).extend({quote_no:z.string(),customer_name:z.string()})).max(100),next_cursor:z.number().int().positive().nullable()}).strict();
export const exportViewSchema=z.object({id:z.string().uuid(),version:z.number().int().positive(),draft:z.boolean(),filename:z.string().regex(/^quotation-[a-f0-9-]+-v[0-9]+\.pdf$/u),sha256:sha,byte_length:z.number().int().min(100).max(8388608),content_base64:z.string().max(11184812).regex(/^[A-Za-z0-9+/]+={0,2}$/u),totals:calculatedTotalsSchema}).strict();
export const outputSchemas:Record<string,z.ZodType>={config:configViewSchema,'config-save':configViewSchema,preview:previewViewSchema,save:documentViewSchema,get:documentViewSchema,approve:documentViewSchema,list:documentListViewSchema,export:exportViewSchema};
export const responseSchema=(action:string)=>z.object({schema_version:z.literal(VERSION),status:z.literal('success'),data:outputSchemas[action]!,reason_codes:z.array(z.string()).length(0)}).strict();
