import type {PortalBusinessService} from '../access-gateway/portal/business/service';
import type {QuoteRelease} from '../quote-native/client';
import {zoneDataSchema,sourceRefSchema} from '../access-gateway/portal/business/quote-client';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import type {z} from 'zod';
import {openPortalProductionDatabase,securePortalDatabaseFiles} from '../access-gateway/portal/production-persistence';
import {PortalError,type PortalContext} from '../access-gateway/portal/contracts';
import type {PortalService} from '../access-gateway/portal/service';
import {configSaveSchema,previewSchema,saveSchema,approveSchema,idSchema,listSchema,nativePrepareSchema,nativeQuoteBindingSchema,rejectSchema,type QuoteTemplate,type QuoteDocument} from './contracts';
import {calculate,renderHtml} from './engine';
import {renderPdf} from './renderer';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const parse=<T>(s:z.ZodType<T>,i:unknown):T=>{const p=s.safeParse(i);if(!p.success)throw new PortalError('document_input_invalid');return p.data;};
type Scope={org:string;user:string;manager:boolean};
export type DocumentView={id:string;version:number;state:'draft'|'approved'|'rejected';native_quote_v1?:z.infer<typeof nativeQuoteBindingSchema>;rejection?:{reason:string;actor:string;at:string};input:QuoteDocument;template:QuoteTemplate;template_version:number;created_at:string;owner_id:string;approval:{evidence_ref:string;evidence_version:string;review_notes:string;actor:string;at:string}|null};
export class DocumentStore{
 readonly db;
 constructor(readonly path:string){this.db=openPortalProductionDatabase(path,'freightclaw-quote-documents',2);const version=(this.db.prepare('PRAGMA user_version').get() as {user_version:number}).user_version;if(version>2){this.db.close();throw new Error('documents_schema_incompatible');}this.db.exec(`CREATE TABLE IF NOT EXISTS document_configs(org TEXT PRIMARY KEY,version INTEGER NOT NULL,input TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS quote_documents(id TEXT PRIMARY KEY,org TEXT NOT NULL,owner TEXT NOT NULL,payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS document_idempotency(scope TEXT NOT NULL,key TEXT NOT NULL,digest TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(scope,key));
 CREATE TABLE IF NOT EXISTS document_audit(id TEXT PRIMARY KEY,org TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,digest TEXT NOT NULL,created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS document_pdfs(id TEXT NOT NULL,version INTEGER NOT NULL,sha256 TEXT NOT NULL,bytes BLOB NOT NULL,PRIMARY KEY(id,version));PRAGMA user_version=2;`);securePortalDatabaseFiles(path);}
 close(){this.db.close();securePortalDatabaseFiles(this.path);}
}
export class DocumentService{
 private secret=randomBytes(32).toString('hex');
 constructor(readonly store:DocumentStore,private portal:Pick<PortalService,'getState'>,private renderer:(html:string)=>Promise<Buffer>=renderPdf,private native?:{business:Pick<PortalBusinessService,'execute'>;current:(org:string)=>QuoteRelease|null}){}
 private scope(ctx:PortalContext,manage=false):Scope{if(!ctx.identity.emailVerified||!ctx.organizationId||ctx.identity.platformRole!==null)throw new PortalError('document_organization_required');const s=this.portal.getState(ctx).data,m=s?.memberships.find(m=>m.userId===ctx.identity.userId&&m.organizationId===ctx.organizationId&&m.status==='active');if(!m||s?.current_organization?.status!=='active')throw new PortalError('document_access_denied');const manager=['owner','admin'].includes(m.role);if(manage&&!manager)throw new PortalError('document_management_denied');return {org:ctx.organizationId,user:ctx.identity.userId,manager};}
 config(ctx:PortalContext){const s=this.scope(ctx),r=this.store.db.prepare('SELECT version,input FROM document_configs WHERE org=?').get(s.org) as {version:number;input:string}|undefined;return {version:r?.version??0,input:r?JSON.parse(r.input) as QuoteTemplate:null};}
 private write<T>(s:Scope,action:string,input:unknown,key:string,fn:()=>T):T{if(!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('idempotency_key_invalid');const partition=JSON.stringify([s.org,s.user,action]),digest=hash(input),db=this.store.db;db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT digest,result FROM document_idempotency WHERE scope=? AND key=?').get(partition,key) as {digest:string;result:string}|undefined;if(old){if(old.digest!==digest)throw new PortalError('idempotency_conflict');db.exec('COMMIT');return JSON.parse(old.result) as T;}const result=fn();db.prepare('INSERT INTO document_audit VALUES(?,?,?,?,?,?)').run(randomUUID(),s.org,s.user,action,digest,new Date().toISOString());db.prepare('INSERT INTO document_idempotency VALUES(?,?,?,?)').run(partition,key,digest,JSON.stringify(result));db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
 saveConfig(ctx:PortalContext,input:unknown,key:string){const s=this.scope(ctx,true),d=parse(configSaveSchema,input);return this.write(s,'config',d,key,()=>{if(this.config(ctx).version!==d.expected_version)throw new PortalError('version_conflict');this.store.db.prepare('INSERT INTO document_configs VALUES(?,?,?) ON CONFLICT(org) DO UPDATE SET version=excluded.version,input=excluded.input').run(s.org,d.expected_version+1,JSON.stringify(d.input));return this.config(ctx);});}
 private signature(s:Scope,version:number,input:QuoteDocument,expires:number,binding:unknown=null){return hash([this.secret,s.org,s.user,version,input,expires,binding]);}
 preview(ctx:PortalContext,input:unknown){const s=this.scope(ctx),d=parse(previewSchema,input),t=this.config(ctx);if(!t.input)throw new PortalError('document_template_missing');const expires=Date.now()+600000;return {input:d.input,template_version:t.version,preview_expires_at:expires,preview_hash:this.signature(s,t.version,d.input,expires)};}
 private checkNative(ctx:PortalContext,binding:DocumentView['native_quote_v1']){if(!binding)return;const release=this.native?.current(this.scope(ctx).org),today=new Date().toISOString().slice(0,10);if(!release||release.release_id!==binding.release_id||release.digest!==binding.release_digest||today<release.input.valid_from||today>release.input.valid_until||hash(binding.request)!==binding.request_hash)throw new PortalError('native_quote_source_changed');}
 async prepareNative(ctx:PortalContext,input:unknown){this.scope(ctx);const d=parse(nativePrepareSchema,input);if(!this.native)throw new PortalError('native_quote_unavailable');const result=await this.native.business.execute(ctx,'quote.zone_preview',d.request,'req_'+randomUUID().replaceAll('-',''));if(result.status!=='success')throw new PortalError(result.reason_codes[0]??'native_quote_unavailable');const preview=parse(zoneDataSchema,result.data),refs=parse(sourceRefSchema.array().min(1),'source_refs' in result?result.source_refs:[]),release=this.native.current(ctx.organizationId!);if(!release||!refs.some(r=>r.system==='freightclaw-native-quote'&&r.source_id===release.release_id&&r.content_hash==='sha256:'+release.digest))throw new PortalError('native_quote_source_changed');const maxDays=release.input.extensions?.quote_valid_days_v1;if(maxDays&&Date.parse(d.customer.valid_until)-Date.parse(d.customer.quote_date)>maxDays*86400000)throw new PortalError('native_quote_validity_invalid');if(d.customer.valid_until>release.input.valid_until||d.customer.quote_date<release.input.valid_from)throw new PortalError('native_quote_validity_invalid');const feeLabels:Record<string,string>={residential_fee_usd:'住宅费',liftgate_fee_usd:'尾板费',pallet_jack_fee_usd:'地牛费',appointment_fee_usd:'预约费',detention_fee_usd:'等待费'};const amounts=[['基础运费',preview.base_price],['燃油费',preview.fuel],...Object.entries(preview.accessorials).map(([name,value])=>[feeLabels[name]??name,value])];const quote:QuoteDocument={...d.customer,origin:preview.origin||'',destination:[preview.city,preview.province,preview.postal_code].filter(Boolean).join(' '),route_name:release.input.label,exchange_rates:{USD:null,CAD:null},fee_items:amounts.filter(([,a],i)=>a!==null&&(i===0||a!=='0.00')).map(([name,amount],i)=>({id:randomUUID(),name:name!,description:'',group:'C',quantity:'1',unit:'票',unit_price:amount!,currency:'USD',display:'detail',merge_name:'',note:i===0?'已发布运价计算':''})),remark:d.customer.remark.includes('适用条件：'+release.input.customer_terms)?d.customer.remark:d.customer.remark+'\n适用条件：'+release.input.customer_terms};if(calculate(quote).by_currency.USD!==preview.total_price)throw new PortalError('native_quote_amount_conflict');const binding=nativeQuoteBindingSchema.parse({request:d.request,preview,source_refs:refs,release_id:release.release_id,release_digest:release.digest,request_hash:hash(d.request)}),p=this.preview(ctx,{input:quote});return {...p,native_quote_v1:binding,preview_hash:this.signature(this.scope(ctx),p.template_version,p.input,p.preview_expires_at,binding)};}
 save(ctx:PortalContext,input:unknown,key:string){const s=this.scope(ctx),d=parse(saveSchema,input);return this.write(s,'save',d,key,()=>{const t=this.config(ctx);if(!t.input||t.version!==d.template_version||d.preview_expires_at<Date.now()||d.preview_hash!==this.signature(s,t.version,d.input,d.preview_expires_at,d.native_quote_v1??null))throw new PortalError('document_preview_stale');this.checkNative(ctx,d.native_quote_v1);const row:DocumentView={...(d.native_quote_v1?{native_quote_v1:d.native_quote_v1}:{}),id:randomUUID(),version:1,state:'draft',input:d.input,template:t.input,template_version:t.version,created_at:new Date().toISOString(),owner_id:s.user,approval:null};this.store.db.prepare('INSERT INTO quote_documents VALUES(?,?,?,?)').run(row.id,s.org,s.user,JSON.stringify(row));return this.get(ctx,{id:row.id});});}
 get(ctx:PortalContext,input:unknown):DocumentView{const s=this.scope(ctx),d=parse(idSchema,input),r=this.store.db.prepare('SELECT owner,payload FROM quote_documents WHERE id=? AND org=?').get(d.id,s.org) as {owner:string;payload:string}|undefined;if(!r||r.owner!==s.user&&!s.manager)throw new PortalError('document_not_found');return JSON.parse(r.payload) as DocumentView;}
 list(ctx:PortalContext,input:unknown){const s=this.scope(ctx),d=parse(listSchema,input);const rows=this.store.db.prepare('SELECT rowid,id FROM quote_documents WHERE org=? AND (?=1 OR owner=?) AND rowid<? ORDER BY rowid DESC LIMIT ?').all(s.org,s.manager?1:0,s.user,d.before??Number.MAX_SAFE_INTEGER,d.limit+1) as {rowid:number;id:string}[];const page=rows.slice(0,d.limit);return {items:page.map(r=>{const v=this.get(ctx,{id:r.id});return {id:v.id,version:v.version,state:v.state,quote_no:v.input.quote_no,customer_name:v.input.customer_name,created_at:v.created_at};}),next_cursor:rows.length>d.limit?page.at(-1)!.rowid:null};}
 private valid(row:DocumentView){const date=new Date().toISOString().slice(0,10);return row.input.quote_date<=date&&date<=row.input.valid_until;}
 approve(ctx:PortalContext,input:unknown,key:string){const s=this.scope(ctx,true),d=parse(approveSchema,input);return this.write(s,'approve',d,key,()=>{const row=this.get(ctx,{id:d.id});if(row.version!==d.expected_version||row.state!=='draft')throw new PortalError('version_conflict');if(!this.valid(row))throw new PortalError('document_expired');this.checkNative(ctx,row.native_quote_v1);row.state='approved';row.version++;row.approval={evidence_ref:d.evidence_ref,evidence_version:d.evidence_version,review_notes:d.review_notes,actor:s.user,at:new Date().toISOString()};this.store.db.prepare('UPDATE quote_documents SET payload=? WHERE id=? AND org=?').run(JSON.stringify(row),row.id,s.org);return this.get(ctx,{id:row.id});});}
 reject(ctx:PortalContext,input:unknown,key:string){const s=this.scope(ctx,true),d=parse(rejectSchema,input);return this.write(s,'reject',d,key,()=>{const row=this.get(ctx,{id:d.id});if(row.version!==d.expected_version||row.state!=='draft')throw new PortalError('version_conflict');row.state='rejected';row.version++;row.rejection={reason:d.reason,actor:s.user,at:new Date().toISOString()};this.store.db.prepare('UPDATE quote_documents SET payload=? WHERE id=? AND org=?').run(JSON.stringify(row),row.id,s.org);return this.get(ctx,{id:row.id});});}
 async export(ctx:PortalContext,input:unknown){const row=this.get(ctx,input);if(row.state==='rejected')throw new PortalError('document_rejected');if(row.state==='approved')this.checkNative(ctx,row.native_quote_v1);if(row.state==='approved'&&!this.valid(row))throw new PortalError('document_expired');let cached=this.store.db.prepare('SELECT sha256,bytes FROM document_pdfs WHERE id=? AND version=?').get(row.id,row.version) as {sha256:string;bytes:Uint8Array}|undefined;
 if(!cached){let bytes:Buffer;try{bytes=await this.renderer(renderHtml(row.input,row.template,row.state==='approved'));}catch{throw new PortalError('document_renderer_unavailable');}const current=this.get(ctx,input);if(current.state==='approved')this.checkNative(ctx,current.native_quote_v1);if(current.version!==row.version)throw new PortalError('version_conflict');if(row.state==='approved'&&!this.valid(current))throw new PortalError('document_expired');if(bytes.length<100||bytes.length>8388608||bytes.subarray(0,5).toString()!=='%PDF-')throw new PortalError('document_pdf_invalid');const sha256=createHash('sha256').update(bytes).digest('hex');this.store.db.prepare('INSERT OR IGNORE INTO document_pdfs VALUES(?,?,?,?)').run(row.id,row.version,sha256,bytes);cached=this.store.db.prepare('SELECT sha256,bytes FROM document_pdfs WHERE id=? AND version=?').get(row.id,row.version) as {sha256:string;bytes:Uint8Array};}
 const bytes=Buffer.from(cached.bytes);if(bytes.length<100||bytes.length>8388608||bytes.subarray(0,5).toString()!=='%PDF-'||createHash('sha256').update(bytes).digest('hex')!==cached.sha256)throw new PortalError('document_pdf_invalid');return {id:row.id,version:row.version,draft:row.state!=='approved',filename:`quotation-${row.id}-v${row.version}.pdf`,sha256:cached.sha256,byte_length:bytes.length,content_base64:bytes.toString('base64'),totals:calculate(row.input)};
 }
}
