import type { PortalContext } from "../contracts";
import { BusinessAccessError,type ApplicationCredentialT0Mode,type BusinessMutation,type BusinessOperation } from "./contracts";
import type { BusinessAccessService } from "./service";
type Service=Pick<BusinessAccessService,"getState"|"getReviewQueue"|"createRequest"|"updateRequest"|"submitRequest"|"withdrawRequest"|"decideRequest"|"activateGrant"|"changeGrant"|"scopeGrant"|"issueCredential"|"acknowledgeCredential"|"rotateCredential"|"revokeCredential"|"setCredentialT0Mode">;
export interface BusinessAccessConsoleRequest{context:PortalContext;path:string;method:string;input?:unknown;idempotencyKey?:string;service:Service}
function object(value:unknown,keys:readonly string[]){if(typeof value!=="object"||value===null||Array.isArray(value)||Object.keys(value).some(x=>!keys.includes(x)))throw new BusinessAccessError("business_body_invalid");return value as Record<string,unknown>;}
function text(v:Record<string,unknown>,key:string){if(typeof v[key]!=="string")throw new BusinessAccessError("business_body_invalid");return v[key];}
function version(v:Record<string,unknown>){if(!Number.isSafeInteger(v.expected_version))throw new BusinessAccessError("business_body_invalid");return v.expected_version as number;}
function operations(v:Record<string,unknown>){if(!Array.isArray(v.operations)||v.operations.some(x=>typeof x!=="string"))throw new BusinessAccessError("business_body_invalid");return v.operations as BusinessOperation[];}
function t0Mode(v:Record<string,unknown>,key="t0_mode"):ApplicationCredentialT0Mode{const value=v[key];if(value!=="none"&&value!=="current_grant")throw new BusinessAccessError("business_body_invalid");return value;}
function mutation<T>(request:BusinessAccessConsoleRequest,expectedVersion:number|undefined,input:T):BusinessMutation<T>{if(!request.idempotencyKey)throw new BusinessAccessError("idempotency_key_required");return{ idempotencyKey:request.idempotencyKey,...(expectedVersion===undefined?{}:{expectedVersion}),input};}
export async function handleBusinessAccessRequest(r:BusinessAccessConsoleRequest):Promise<unknown>{const prefix="/console/api/v1/business-access";if(r.path===`${prefix}/state`&&r.method==="GET")return r.service.getState(r.context);if(r.path===`${prefix}/review-queue`&&r.method==="GET")return r.service.getReviewQueue(r.context);let match:RegExpExecArray|null;
  if(r.path===`${prefix}/requests`&&r.method==="POST"){const v=object(r.input,["application_id","operations","justification"]);return r.service.createRequest(r.context,mutation(r,undefined,{applicationId:text(v,"application_id"),operations:operations(v),justification:text(v,"justification")}));}
  if((match=new RegExp(`^${prefix}/requests/([^/]+)$`,`u`).exec(r.path))&&r.method==="PATCH"){const v=object(r.input,["expected_version","operations","justification"]);return r.service.updateRequest(r.context,match[1]!,mutation(r,version(v),{operations:operations(v),justification:text(v,"justification")}));}
  if((match=new RegExp(`^${prefix}/requests/([^/]+)/(submit|withdraw)$`,`u`).exec(r.path))&&r.method==="POST"){const v=object(r.input,["expected_version"]),id=match[1]!;if(!r.idempotencyKey)throw new BusinessAccessError("idempotency_key_required");return match[2]==="submit"?r.service.submitRequest(r.context,id,version(v),r.idempotencyKey):r.service.withdrawRequest(r.context,id,version(v),r.idempotencyKey);}
  if((match=new RegExp(`^${prefix}/requests/([^/]+)/decision$`,`u`).exec(r.path))&&r.method==="POST"){const v=object(r.input,["expected_version","decision","reason","approved_operations"]);if(!["approve","reject","needs_input"].includes(String(v.decision)))throw new BusinessAccessError("business_body_invalid");const approved=v.approved_operations===undefined?undefined:(Array.isArray(v.approved_operations)&&v.approved_operations.every(x=>typeof x==="string")?v.approved_operations as BusinessOperation[]:(()=>{throw new BusinessAccessError("business_body_invalid");})());return r.service.decideRequest(r.context,match[1]!,mutation(r,version(v),{decision:v.decision as "approve"|"reject"|"needs_input",reason:text(v,"reason"),...(approved?{approvedOperations:approved}:{})}));}
  if((match=new RegExp(`^${prefix}/grants/([^/]+)/(activate|change|scope)$`,`u`).exec(r.path))&&r.method==="POST"){const id=match[1]!,action=match[2]!;if(action==="activate"){const v=object(r.input,["expected_version","expires_at"]);return r.service.activateGrant(r.context,id,mutation(r,version(v),{...(v.expires_at===undefined?{}:{expiresAt:text(v,"expires_at")})}));}if(action==="scope"){const v=object(r.input,["expected_version","operations","expires_at"]);return r.service.scopeGrant(r.context,id,mutation(r,version(v),{operations:operations(v),...(v.expires_at===undefined?{}:{expiresAt:text(v,"expires_at")})}));}const v=object(r.input,["expected_version","state","operations"]);if(v.state!=="suspended"&&v.state!=="revoked")throw new BusinessAccessError("business_body_invalid");return r.service.changeGrant(r.context,id,mutation(r,version(v),{state:v.state,...(v.operations===undefined?{}:{operations:operations(v)})}));}
  if((match=new RegExp(`^${prefix}/applications/([^/]+)/credentials$`,`u`).exec(r.path))&&r.method==="POST"){const v=object(r.input,["label","operations","t0_mode","expires_in_seconds"]);if(!Number.isSafeInteger(v.expires_in_seconds))throw new BusinessAccessError("business_body_invalid");return r.service.issueCredential(r.context,match[1]!,mutation(r,undefined,{label:text(v,"label"),operations:operations(v),t0Mode:t0Mode(v),expiresInSeconds:v.expires_in_seconds as number}));}
  if((match=new RegExp(`^${prefix}/credentials/([^/]+)/(acknowledge|rotate|revoke)$`,`u`).exec(r.path))&&r.method==="POST"){const id=match[1]!,action=match[2]!;if(action==="rotate"){const v=object(r.input,["expected_version","operations","t0_mode","expires_in_seconds"]);if(!Number.isSafeInteger(v.expires_in_seconds))throw new BusinessAccessError("business_body_invalid");return r.service.rotateCredential(r.context,id,mutation(r,version(v),{operations:operations(v),t0Mode:t0Mode(v),expiresInSeconds:v.expires_in_seconds as number}));}const v=object(r.input,["expected_version"]),m=mutation(r,version(v),{});return action==="acknowledge"?r.service.acknowledgeCredential(r.context,id,m):r.service.revokeCredential(r.context,id,m);}
  if((match=new RegExp(`^${prefix}/credentials/([^/]+)/t0-mode$`,`u`).exec(r.path))&&r.method==="POST"){const v=object(r.input,["expected_version","mode"]);if(v.mode!=="none"&&v.mode!=="current_grant")throw new BusinessAccessError("business_body_invalid");return r.service.setCredentialT0Mode(r.context,match[1]!,mutation(r,version(v),{mode:v.mode}));}
  throw new BusinessAccessError("business_route_not_found");}
