import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { BUSINESS_CALL_SCHEMA_VERSION, BUSINESS_EXCHANGE_SCHEMA_VERSION, BUSINESS_OPERATIONS, BusinessAccessError, type BusinessOperation } from "./contracts";
import type { BusinessAccessService } from "./service";
import { inputSchema as customsQueryInputSchema } from "../business/customs-client";
import { batchInputSchema as taxBatchInputSchema, singleInputSchema as taxInputSchema } from "../business/tax-client";
import { extractInputSchema as quoteExtractInputSchema, zoneInputSchema as quotePreviewInputSchema } from "../business/quote-client";
import { freightcomInputSchema } from "../business/freightcom-client";
const MAX=32*1024;
const routes=new Map<string,BusinessOperation>([["/api/v2/business/customs/query","customs.query"],["/api/v2/business/customs/tax-estimate","customs.tax.estimate"],["/api/v2/business/customs/tax-estimates/batch","customs.tax.estimate"],["/api/v2/business/quote/zone-preview","quote.zone_preview"],["/api/v2/business/quote/ai-extract-preview","quote.ai_extract_preview"],["/api/v2/business/quote/freightcom-ltl-preview","quote.freightcom_ltl.preview"]]);
export interface BusinessMachineExecutionResult{schema_version:"portal-customs@2026-09-05.v1"|"portal-tax@2026-09-05.v1"|"portal-quote@2026-09-05.v1"|"portal-freightcom-rate@2026-09-05.v1"|"portal-business@2026-09-05.v1";status:"success"|"needs_input"|"manual_review"|"blocked"|"unavailable";data:unknown;reason_codes:readonly string[];readonly [key:string]:unknown}
export interface BusinessMachineExecutionPort{execute(input:{operation:BusinessOperation;batch:boolean;input:unknown;requestId:string;machine:{tenantId:string;clientId:string;applicationId:string;credentialId:string}}):Promise<unknown>}
export interface BusinessMachineHttpOptions{mode:"fixtures"|"production";service:Pick<BusinessAccessService,"exchange"|"authorize"|"repositoryKind">&Partial<Pick<BusinessAccessService,"authorizeApiKey">>;executor:BusinessMachineExecutionPort;allowedHosts:readonly string[];allowedOrigins:readonly string[];trustedProxyAddresses:readonly string[];maxBodyBytes?:number}
const count=(r:IncomingMessage,n:string)=>r.rawHeaders.filter((_,i)=>i%2===0&&r.rawHeaders[i]?.toLowerCase()===n).length;
function send(res:ServerResponse,status:number,value:unknown){res.setHeader("cache-control","no-store");res.setHeader("content-security-policy","default-src 'none'; frame-ancestors 'none'");res.setHeader("referrer-policy","no-referrer");res.setHeader("x-content-type-options","nosniff");res.setHeader("content-type","application/json; charset=utf-8");res.statusCode=status;res.end(JSON.stringify(value));}
async function body(req:IncomingMessage,max:number){if(!/^application\/json(?:\s*;\s*charset=utf-8)?$/iu.test(String(req.headers["content-type"]??"")))throw new BusinessAccessError("business_body_invalid");const chunks:Uint8Array[]=[];let size=0;for await(const chunk of req){const bytes=typeof chunk==="string"?Buffer.from(chunk):new Uint8Array(chunk);size+=bytes.length;if(size>max)throw new BusinessAccessError("business_body_too_large");chunks.push(bytes);}try{return JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;}catch{throw new BusinessAccessError("business_body_invalid");}}
function auth(req:IncomingMessage,scheme:"ApiKey"|"Bearer"){if(count(req,"authorization")!==1||req.headers.cookie!==undefined)throw new BusinessAccessError("business_authentication_failed");const match=new RegExp(`^${scheme} ([^\\s]{1,16384})$`,`u`).exec(String(req.headers.authorization??""));if(!match?.[1])throw new BusinessAccessError("business_authentication_failed");return match[1];}
function callAuth(req:IncomingMessage){if(count(req,"authorization")!==1||req.headers.cookie!==undefined)throw new BusinessAccessError("business_authentication_failed");const match=/^(ApiKey|Bearer) ([^\s]{1,16384})$/u.exec(String(req.headers.authorization??""));if(!match?.[1]||!match[2])throw new BusinessAccessError("business_authentication_failed");return{scheme:match[1] as "ApiKey"|"Bearer",credential:match[2]};}
function boundary(req:IncomingMessage,o:BusinessMachineHttpOptions){const remote=req.socket.remoteAddress??"",local=req.socket.localAddress??"";const loopback=(value:string)=>["127.0.0.1","::1","::ffff:127.0.0.1"].includes(value);if(count(req,"host")!==1||!o.allowedHosts.includes(String(req.headers.host)))throw new BusinessAccessError("business_request_denied");const origin=req.headers.origin;if(origin!==undefined&&(count(req,"origin")!==1||typeof origin!=="string"||!o.allowedOrigins.includes(origin)))throw new BusinessAccessError("business_request_denied");if(o.mode==="fixtures"){if(!loopback(remote)||!loopback(local)||o.service.repositoryKind!=="synthetic")throw new BusinessAccessError("business_request_denied");return;}if(o.service.repositoryKind!=="production"||!o.trustedProxyAddresses.includes(remote)||count(req,"x-forwarded-proto")!==1||req.headers["x-forwarded-proto"]!=="https")throw new BusinessAccessError("business_request_denied");}
const statuses=new Set(["success","needs_input","manual_review","blocked","unavailable"]);
function validInput(operation:BusinessOperation,batch:boolean,input:unknown){const schema=operation==="customs.query"?customsQueryInputSchema:operation==="customs.tax.estimate"?(batch?taxBatchInputSchema:taxInputSchema):operation==="quote.zone_preview"?quotePreviewInputSchema:operation==="quote.ai_extract_preview"?quoteExtractInputSchema:freightcomInputSchema;if(!schema.safeParse(input).success)throw new BusinessAccessError("business_body_invalid");}
function dangerous(value:unknown):boolean{if(Array.isArray(value))return value.some(dangerous);if(typeof value!=="object"||value===null)return false;return Object.entries(value as Record<string,unknown>).some(([key,item])=>/(?:^|_)(?:api_?key|access_?token|token|secret|authorization|cookie|private_?key)(?:$|_)/iu.test(key)||dangerous(item));}
export function assertBusinessMachineExecutionResult(value:unknown,requestId:string,operation:BusinessOperation):BusinessMachineExecutionResult{if(typeof value!=="object"||value===null||Array.isArray(value))throw new BusinessAccessError("business_execution_contract_invalid");const raw=value as Record<string,unknown>,schema=raw.schema_version;if(!["portal-customs@2026-09-05.v1","portal-tax@2026-09-05.v1","portal-quote@2026-09-05.v1","portal-freightcom-rate@2026-09-05.v1","portal-business@2026-09-05.v1"].includes(String(schema))||!statuses.has(String(raw.status))||!Array.isArray(raw.reason_codes)||raw.reason_codes.some(x=>typeof x!=="string")||dangerous(raw.data))throw new BusinessAccessError("business_execution_contract_invalid");const expected=operation==="customs.query"?"portal-customs@2026-09-05.v1":operation==="customs.tax.estimate"?"portal-tax@2026-09-05.v1":operation==="quote.freightcom_ltl.preview"?"portal-freightcom-rate@2026-09-05.v1":"portal-quote@2026-09-05.v1";if(schema!==expected&&!(schema==="portal-business@2026-09-05.v1"&&["blocked","unavailable"].includes(String(raw.status))&&raw.data===null))throw new BusinessAccessError("business_execution_contract_invalid");const keys=Object.keys(raw).sort().join(",");if((schema==="portal-customs@2026-09-05.v1"||schema==="portal-business@2026-09-05.v1")&&keys!=="data,reason_codes,schema_version,status")throw new BusinessAccessError("business_execution_contract_invalid");if(schema==="portal-tax@2026-09-05.v1"&&(keys!=="data,reason_codes,request_id,schema_version,status"||raw.request_id!==requestId))throw new BusinessAccessError("business_execution_contract_invalid");if(schema==="portal-quote@2026-09-05.v1"&&(keys!=="data,preview_only,reason_codes,request_id,saved,schema_version,sendable,source_refs,source_schema_version,status"||raw.request_id!==requestId||raw.preview_only!==true||raw.saved!==false||raw.sendable!==false))throw new BusinessAccessError("business_execution_contract_invalid");if(schema==="portal-freightcom-rate@2026-09-05.v1"&&(keys!=="bookable,data,reason_codes,request_id,saved,schema_version,sendable,source_refs,status"||raw.request_id!==requestId||raw.saved!==false||raw.sendable!==false||raw.bookable!==false))throw new BusinessAccessError("business_execution_contract_invalid");if(schema==="portal-customs@2026-09-05.v1"&&raw.data!==null&&(typeof raw.data!=="object"||(raw.data as Record<string,unknown>).requestId!==requestId))throw new BusinessAccessError("business_execution_contract_invalid");return raw as unknown as BusinessMachineExecutionResult;}
export function createBusinessMachineHttpHandler(o:BusinessMachineHttpOptions){if(o.mode==="production"&&o.trustedProxyAddresses.length===0)throw new BusinessAccessError("business_proxy_policy_required");const max=o.maxBodyBytes??MAX;if(max<1||max>MAX)throw new BusinessAccessError("business_body_limit_invalid");return{handle(req:IncomingMessage,res:ServerResponse){const path=(req.url??"").split("?",1)[0]!;if(path!=="/access/v2/business/token/exchange"&&!routes.has(path))return false;void(async()=>{const requestId=`req_${randomUUID().replaceAll("-","")}`;try{if(req.method!=="POST"||(req.url??"")!==path)throw new BusinessAccessError("business_request_denied");boundary(req,o);const exchange=path==="/access/v2/business/token/exchange",authorization=exchange?{scheme:"ApiKey" as const,credential:auth(req,"ApiKey")}:callAuth(req);const raw=await body(req,max);if(typeof raw!=="object"||raw===null||Array.isArray(raw))throw new BusinessAccessError("business_body_invalid");const value=raw as Record<string,unknown>;if(exchange){if(Object.keys(value).sort().join(",")!=="requested_operations,schema_version"||value.schema_version!==BUSINESS_EXCHANGE_SCHEMA_VERSION||!Array.isArray(value.requested_operations)||value.requested_operations.some(x=>typeof x!=="string"||!BUSINESS_OPERATIONS.includes(x as BusinessOperation)))throw new BusinessAccessError("business_body_invalid");send(res,200,await o.service.exchange(authorization.credential,value.requested_operations as BusinessOperation[]));return;}if(Object.keys(value).sort().join(",")!=="input,schema_version"||value.schema_version!==BUSINESS_CALL_SCHEMA_VERSION)throw new BusinessAccessError("business_body_invalid");const operation=routes.get(path)!,batch=path.endsWith("/batch");validInput(operation,batch,value.input);if(authorization.scheme==="ApiKey"&&!o.service.authorizeApiKey)throw new BusinessAccessError("business_authentication_failed");const machine=authorization.scheme==="ApiKey"?await o.service.authorizeApiKey!(authorization.credential,operation):await o.service.authorize(authorization.credential,operation);const result=await o.executor.execute({operation,batch,input:value.input,requestId,machine});send(res,200,assertBusinessMachineExecutionResult(result,requestId,operation));}catch(error){const code=error instanceof BusinessAccessError?error.code:"business_unavailable";send(res,code.includes("authentication")?401:code.includes("body")?400:code.includes("unavailable")?503:403,{schema_version:"business-access@2026-09-05.v1",status:code.includes("body")?"needs_input":code.includes("unavailable")?"unavailable":"blocked",data:null,reason_codes:[code],request_id:requestId});}})();return true;}};}

export { send as sendMachineResponse, body as readMachineBody, auth as readMachineAuth, boundary as assertMachineBoundary, validInput as validateBusinessMachineInput };
