import {cargoTotals} from '../../services/quote-native/cargo-lines.ts';
export function createCargoLines(esc){
 let rows=[],enabled=false;
 const fresh=()=>({id:crypto.randomUUID(),quantity:1,packaging_type:'',length_cm:'',width_cm:'',height_cm:'',weight:{mode:'unit_weight',value_kg:''}});
 const reset=()=>{rows=[];enabled=false;};
 const select=(name,value,options)=>`<select name="cargo_${name}">${options.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`;
 const field=(name,label,value)=>`<label class="field"><span>${label}</span><input name="cargo_${name}" value="${esc(value??'')}" inputmode="decimal"></label>`;
 function render(){return `<section class="qdoc-section"><h3>逐组货物</h3><p>混装或多件超长货物须逐组填写。数量、尺寸单位为 cm，重量为 kg。</p><label><input type="checkbox" name="cargo_lines_enabled" ${enabled?'checked':''}>按逐组资料计算总量与计费托数</label>${enabled?rows.map((r,i)=>`<div class="qdoc-fee" data-cargo-row="${i}"><div class="qdoc-row-head"><strong>货物组 ${i+1}</strong><button type="button" class="button" data-action="business-cargo-remove" data-id="${i}">移除</button></div><div class="qdoc-fields">${field('quantity','件数',r.quantity)}<label class="field"><span>包装</span>${select('packaging_type',r.packaging_type,[['','请选择'],['carton','纸箱'],['crate','木箱'],['pallet','实体托盘'],['bag','袋装'],['other','其他']])}</label>${field('length_cm','长 · cm',r.length_cm)}${field('width_cm','宽 · cm',r.width_cm)}${field('height_cm','高 · cm',r.height_cm)}<label class="field"><span>重量口径</span>${select('weight_mode',r.weight.mode,[['unit_weight','每件重量'],['line_total_weight','本组总重量']])}</label>${field('value_kg','重量 · kg',r.weight.value_kg)}</div></div>`).join('')+'<button type="button" class="button" data-action="business-cargo-add">添加货物组</button>':''}</section>`;}
 function read(form){if(!enabled)return null;rows=[...form.querySelectorAll('[data-cargo-row]')].map((el,i)=>{const get=n=>el.querySelector(`[name="cargo_${n}"]`).value.trim();return {id:rows[i].id,quantity:Number(get('quantity')),packaging_type:get('packaging_type'),length_cm:get('length_cm'),width_cm:get('width_cm'),height_cm:get('height_cm'),weight:{mode:get('weight_mode'),value_kg:get('value_kg')}};});return cargoTotals(rows);}
 function update(form){try{const totals=read(form);if(totals)for(const key of ['cbm','weight_kg','piece_count','longest_side_cm']){const input=form.querySelector(`[name="${key}"]`);if(input){input.value=totals[key];input.readOnly=true;}}const packaging=form.querySelector('#packaging_type');if(packaging)packaging.value='mixed';}catch{for(const key of ['cbm','weight_kg','piece_count','longest_side_cm']){const input=form.querySelector(`[name="${key}"]`);if(input){input.value='';input.readOnly=true;}}const packaging=form.querySelector('#packaging_type');if(packaging)packaging.value='mixed';}}
 function extract(items){rows=items.map(r=>({...fresh(),quantity:r.quantity,length_cm:r.length_cm||'',width_cm:r.width_cm||'',height_cm:r.height_cm||'',packaging_type:/木箱|crate/i.test(r.source_span||'')?'crate':/托盘|pallet|skid/i.test(r.source_span||'')?'pallet':/纸箱|carton|box|ctn/i.test(r.source_span||'')?'carton':/袋|bag/i.test(r.source_span||'')?'bag':'',weight:{mode:r.weight_kg?'unit_weight':'line_total_weight',value_kg:r.weight_kg||r.total_weight_kg||''}}));enabled=rows.length>0;}
 function action(button,form){const a=button.dataset.action;if(!a?.startsWith('business-cargo-'))return false;try{if(form)read(form);}catch{/* Keep editable incomplete rows. */}if(a.endsWith('add'))rows.push(fresh());else rows.splice(Number(button.dataset.id),1);return true;}
 function change(event){if(event.target.name!=='cargo_lines_enabled')return false;enabled=event.target.checked;if(enabled&&!rows.length)rows=[fresh()];return true;}
 return {render,read,update,extract,action,change,reset,input:event=>{if(!event.target.closest('[data-cargo-row]'))return false;update(event.target.closest('form'));return true;},lines:()=>structuredClone(rows),enabled:()=>enabled};
}
