// Operate: extend the existing Console. Empty configuration stays empty; draft,
// preview and publication are distinct. Web and CLI call the same resource API.
export function createChannelsUi({api,mutate,esc,head,note,icon,formError,model,rerender}){
 let loaded=null,pending=null,approval=null,error='',contextKey='';
 const services={ocean_fcl:'整柜海运',ocean_lcl:'拼箱海运',final_mile:'尾程派送'},countries={CN:'中国',CA:'加拿大',US:'美国'};
 const current=()=>JSON.stringify([model().session?.identity?.user_id,model().session?.organization_id]);
 function reset(){loaded=null;pending=null;approval=null;error='';contextKey=current();}
 const redraw=()=>rerender();
 function load(id){const key=current()+'|'+(id||'list');if(loaded?.key===key||pending===key)return;approval=null;pending=key;const origin=current();Promise.all([api(id&&id!=='new'?`/admin/channels/${id}`:'/admin/channels'),id&&id!=='new'?api(`/admin/channels/${id}/history`):Promise.resolve(null)]).then(([result,history])=>{if(origin!==current()||pending!==key)return;loaded={key,value:result.data,history:history?.data};pending=null;error='';if(location.hash.startsWith('#channels'))redraw();}).catch(e=>{if(origin!==current()||pending!==key)return;loaded={key,value:null};pending=null;error=e.code==='channel_management_denied'?'当前账号没有管理渠道的权限。':'暂时无法读取渠道配置，请稍后重试。';if(location.hash.startsWith('#channels'))redraw();});}
 const button=(text,action,id='',primary=false)=>`<button class="button ${primary?'primary':''}" type="button" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
 function field(label,name,value='',type='text',readonly=false){return `<div class="field"><label for="channel-${name}">${label}</label><input id="channel-${name}" name="${name}" type="${type}" value="${esc(value)}" required ${readonly?'readonly':''} maxlength="100"></div>`;}
 function select(label,name,options,value){return `<div class="field"><label for="channel-${name}">${label}</label><select id="channel-${name}" name="${name}" required><option value="">请选择</option>${Object.entries(options).map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}
 function previewDetails(){const d=approval.input;if(!d)return '';const release=loaded.history?.releases.find(r=>r.release_id===approval.release_id);return `${release?`<p><strong>回退到发布版本 ${release.version}</strong> · ${esc(new Date(release.published_at).toLocaleString('zh-CN'))}</p>`:`<p>即将发布已保存的草稿，当前版本 ${approval.version}。</p>`}<dl class="channel-preview-details">${[['渠道名称',d.name],['渠道编号',d.code],['始发仓',d.warehouse],['服务类型',services[d.service]],['起运国家',countries[d.origin_country]],['目的国家',countries[d.destination_country]],['结算币种',d.currency],['有效期',`${d.valid_from} 至 ${d.valid_until}`]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;}
 function page(id){if(current()!==contextKey)reset();load(id);const title=head('渠道与仓库','先建立运输渠道，再逐步配置分区、运价与计费规则。',!id?'<button class="button primary" data-go="channels/new">'+icon('plus')+'新建渠道</button>':'<button class="button" data-go="channels">返回渠道列表</button>');
  if(error)return title+note(error,'error')+button('重新读取','channel-reload');if(!loaded||loaded.key!==current()+'|'+(id||'list'))return title+'<p role="status">正在读取渠道配置…</p>';
  if(!id){const items=loaded.value.items;return title+`<div class="channel-layout"><section>${items.length?`<div class="channel-list">${items.map(v=>`<a class="channel-row" href="#channels/${v.channel_id}"><div class="channel-symbol">${icon('truck')}</div><div><h2>${esc(v.input.name)}</h2><p>${esc(v.input.warehouse)} · ${countries[v.input.origin_country]} → ${countries[v.input.destination_country]}</p><span>${services[v.input.service]} · ${esc(v.input.currency)} · ${esc(v.input.code)}</span></div><span class="channel-state">${v.active_release?'已发布渠道信息':'草稿'}</span>${icon('arrow')}</a>`).join('')}</div>`:`<div class="channel-empty">${icon('truck')}<h2>从第一个运输渠道开始</h2><p>填写始发仓、目的地、服务类型和有效期。<br>旧配置不会自动导入，新渠道先保存为草稿。</p><button class="button primary" data-go="channels/new">新建渠道</button></div>`}</section><aside class="channel-guide"><h2>配置顺序</h2><ol><li><strong>渠道与仓库</strong><p>维护路线、服务、币种和有效期。</p></li><li><strong>分区与运价</strong><p>下一阶段接入邮编覆盖、运价和附加费。</p></li><li><strong>试算与发布</strong><p>完整规则就绪后，再验证报价结果。</p></li></ol><a href="#cli">通过 CLI 管理 ${icon('arrow')}</a></aside></div>`;}
  const value=id==='new'?null:loaded.value,data=value?.input||{};return title+`<div class="channel-layout"><div><form class="panel channel-form" data-form="channel-save" data-id="${esc(id)}"><div class="panel-body">${formError}<h2>${value?'编辑渠道草稿':'新建运输渠道'}</h2><div class="field-grid">${field('渠道名称','name',data.name)}${field('渠道编号','code',data.code,'text',!!value)}${field('始发仓名称','warehouse',data.warehouse)}${select('服务类型','service',services,data.service)}${select('起运国家','origin_country',countries,data.origin_country)}${select('目的国家','destination_country',countries,data.destination_country)}${select('结算币种','currency',{CAD:'加元 CAD',USD:'美元 USD',CNY:'人民币 CNY'},data.currency)}<div></div>${field('有效期开始','valid_from',data.valid_from,'date')}${field('有效期结束','valid_until',data.valid_until,'date')}</div><div class="channel-actions"><button class="button primary" type="submit">保存草稿</button>${value?button('预览发布','channel-preview',id):''}</div></div></form>${approval?`<section class="panel channel-confirm" aria-label="确认配置变更"><div class="panel-body"><h2>${approval.kind==='disable'?'确认停用渠道':approval.kind==='rollback'?'确认回退渠道信息':'确认发布渠道信息'}</h2>${approval.kind==='disable'?'<p>停用后将不再有当前发布版本，历史记录继续保留。</p>':previewDetails()}<p>本次只变更渠道信息，运价与计费规则尚未接入。</p><div class="channel-actions">${button('确认'+(approval.kind==='disable'?'停用':approval.kind==='rollback'?'回退':'发布'),'channel-confirm',id,true)}${button('取消','channel-cancel')}</div></div></section>`:''}${value?`<section class="panel channel-history"><div class="panel-body"><h2>发布记录</h2>${loaded.history.releases.length?loaded.history.releases.map(r=>`<div class="channel-release"><div><strong>${esc(r.input.name)}</strong><p>${esc(new Date(r.published_at).toLocaleString('zh-CN'))} · 版本 ${r.version}</p></div>${r.release_id===value.active_release?.release_id?'<span>当前发布</span>':button('预览回退','channel-rollback',r.release_id)}</div>`).join(''):'<p>尚无发布记录。</p>'}</div></section>`:''}</div><aside class="channel-guide"><h2>当前状态</h2><p>${value?.active_release?'已有发布版本。保存草稿不会改变当前发布内容。':'尚未发布，保存后可预览并确认发布。'}</p>${value?.active_release?`<dl><dt>已发布渠道</dt><dd>${esc(value.active_release.input.name)}</dd><dt>有效期</dt><dd>${esc(value.active_release.input.valid_from)} 至 ${esc(value.active_release.input.valid_until)}</dd></dl>${button('停用渠道','channel-disable',id)}`:''}<h3>填写提示</h3><p>渠道编号保存后固定。日期、币种和始发仓由你明确填写，不自动套用旧规则。</p></aside></div>`;
 }
 async function submit(form){if(form.dataset.form!=='channel-save')return false;const id=form.dataset.id,input=Object.fromEntries(new FormData(form));const result=await mutate('/admin/channels'+(id==='new'?'':`/${id}/save`),'POST',id==='new'?input:{expected_version:loaded.value.version,input});reset();location.hash='channels/'+result.data.channel_id;redraw();return true;}
 async function action(b){const a=b.dataset.action;if(!a?.startsWith('channel-'))return false;const id=location.hash.split('/')[1];const form=document.querySelector('form[data-form="channel-save"]');if(form&&loaded?.value?.input&&Object.entries(Object.fromEntries(new FormData(form))).some(([k,v])=>v!==loaded.value.input[k])){const e=new Error('channel_unsaved_changes');e.code='channel_unsaved_changes';throw e;}if(a==='channel-reload'){reset();redraw();return true;}if(a==='channel-cancel'){approval=null;redraw();return true;}if(a==='channel-preview'||a==='channel-rollback'){approval={...(await api(`/admin/channels/${id}/preview`+(a==='channel-rollback'?`?release_id=${encodeURIComponent(b.dataset.id)}`:''))).data,kind:a==='channel-rollback'?'rollback':'publish'};redraw();document.querySelector('.channel-confirm')?.scrollIntoView({behavior:'instant',block:'center'});return true;}if(a==='channel-disable'){approval={kind:'disable',version:loaded.value.version};redraw();return true;}if(a==='channel-confirm'){const body={expected_version:approval.version,...(approval.kind==='disable'?{}:{preview_hash:approval.preview_hash}),...(approval.kind==='rollback'?{release_id:approval.release_id}:{})};await mutate(`/admin/channels/${id}/${approval.kind}`,'POST',body);reset();redraw();return true;}return false;}
 return {page,submit,action,reset};
}
export function createCliAuthorizationUi({api,esc,head,note,model,rerender}){
 let approved='';
 function page(code){if(!/^[A-F0-9]{8}$/u.test(code||''))return head('连接 CLI','')+note('登录请求无效，请从 CLI 重新发起。','error');if(approved===code)return head('CLI 已获准连接','返回终端完成登录，即可继续工作。')+'<p>在终端执行 <code>freightclaw workspace login finish --session-file &lt;原会话文件&gt;</code>。</p><a href="#channels">返回业务管理</a>';
 return head('确认连接 CLI','请核对终端显示的代码，再授权本次登录。')+`<section class="panel cli-authorization"><div class="panel-body"><p>确认代码</p><strong class="cli-user-code">${esc(code)}</strong><p>以 <strong>${esc(model().session.identity.display_name)}</strong> 登录。CLI 可执行此账号已有权限内的工作台操作，会话最多 30 分钟。退出 CLI 不会退出当前网页。</p><p>只有你主动发起的登录请求才应确认。</p><button class="button primary" data-action="cli-authorize" data-id="${esc(code)}">确认连接</button> <a class="button" href="#home">取消</a></div></section>`;}
 async function action(b){if(b.dataset.action!=='cli-authorize')return false;await api('/cli-auth/approve',{method:'POST',body:{user_code:b.dataset.id}});approved=b.dataset.id;rerender();return true;}
 return {page,action};
}
