const labels={customer:'客户',sales:'业务员',operations:'操作员',administrator:'管理员'};
export function createFclUsers({call,write,esc,rerender,notify}){
 let data=null,error='',loading=false,query='',epoch=0;
 const reset=()=>{epoch++;data=null;error='';loading=false;query='';};
 const load=async(more=false)=>{if(loading)return;loading=true;const e=epoch;try{const r=await call('group-list',{query,before:more?data?.next_before:null});if(e!==epoch)return;if(!r.data)throw Error('无法读取人员，请确认管理员权限。');data=more?{...r.data,items:[...data.items,...r.data.items]}:r.data;error='';}catch(err){if(e===epoch)error=err.message||'读取失败，请重试。';}finally{if(e===epoch){loading=false;rerender();}}};
 const render=()=>{if(!data&&!error&&!loading)void load();return `<header class="page-head"><h1>人员与权限</h1></header><p class="muted">新账号默认为客户。业务员负责报价接单，操作员处理分配的节点。</p><section class="panel fcl-order-list"><form class="order-filters" data-fcl-form="users-search"><label class="field">姓名 / 邮箱<input name="query" type="search" value="${esc(query)}" placeholder="查找已登录的账号"></label><button type="submit" class="button primary">查询</button><button type="button" class="button" data-action="fcl-users-refresh">刷新</button><div class="form-error" role="alert" hidden></div></form>${error?`<p role="alert">${esc(error)}</p>`:''}${!data?(error?'':'<p role="status">正在读取人员…</p>'):`<div class="order-table-wrap" tabindex="0" role="region" aria-label="人员权限"><table class="order-table"><thead><tr><th>姓名</th><th>登录邮箱</th><th>当前用户组</th><th>调整用户组</th></tr></thead><tbody>${data.items.map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${esc(p.email)}</td><td>${labels[p.group]}${p.source==='existing'?'<small>沿用已有授权</small>':''}</td><td>${p.group==='administrator'?'固定管理员':`<form data-fcl-form="users-save" data-index="${i}" class="head-actions"><select name="group" aria-label="${esc(p.name)}的用户组">${Object.entries(labels).filter(([key])=>key!=='administrator').map(([key,label])=>`<option value="${key}"${p.group===key?' selected':''}>${label}</option>`).join('')}</select><button class="button" type="submit">保存</button><div class="form-error" role="alert" hidden></div></form>`}</td></tr>`).join('')||'<tr><td colspan="4">没有匹配的账号。请先让对方正常登录一次。</td></tr>'}</tbody></table></div>${data.next_before?'<button type="button" class="button" data-action="fcl-users-more">加载更多</button>':''}`}</section>`;};
 const submit=async form=>{if(form.dataset.fclForm==='users-search'){query=String(new FormData(form).get('query')||'').trim();await load();return true;}if(form.dataset.fclForm!=='users-save')return false;const person=data?.items[Number(form.dataset.index)];if(!person)return true;const group=String(new FormData(form).get('group'));if(group===person.group)return true;if(!window.confirm(`将 ${person.name}（${person.email}）改为${labels[group]}？${group==='customer'?'后台访问将立即停止，历史订单保留。':'只授予该组功能，订单仍按本人受理或分派隔离。'}`))return true;const r=await write('group-save',{user_id:person.user_id,group,expected_version:person.version,confirmed:true});if(!r.data)throw Error('保存未完成，请刷新后重试。');await load();notify('用户组已更新');return true;};
 const action=async button=>{if(!button.dataset.action?.startsWith('fcl-users-'))return false;await load(button.dataset.action==='fcl-users-more');return true;};
 return {render,submit,action,reset};
}
