// A carrier request owns its inputs. No values are taken from the own-rate form.
export function createFreightcomForm({esc, field, input}) {
  const text = (label, name, value = '', attrs = '') => field(label, name, input(name, `required value="${esc(value ?? '')}" ${attrs}`));
  const select = (label, name, value, choices) => field(label, name, `<select id="${name}" name="${name}" required><option value="">请选择并确认</option>${choices.map(([key, title]) => `<option value="${key}" ${value === key ? 'selected' : ''}>${title}</option>`).join('')}</select>`);
  const yesNo = [['yes','需要'],['no','无需']];
  const bool = value => typeof value === 'boolean' ? value ? 'yes' : 'no' : '';
  const name = (key, index) => `fc-${key}${index ? '-' + index : ''}`;
  const time = value => value && Number.isFinite(value.hour) && Number.isFinite(value.minute) ? `${String(value.hour).padStart(2, '0')}:${String(value.minute).padStart(2, '0')}` : '';
  function render(saved = {}) {
    const d = saved.details || {}, origin = d.origin?.address || {}, destination = d.destination?.address || {}, p = d.packaging_properties || {};
    const pallets = p.pallets?.length ? p.pallets : [{}], date = d.expected_ship_date;
    const address = (label, prefix, a) => `<section class="form-section"><h3>${label}</h3><div class="field-grid">${text('详细地址', `${prefix}-address`, a.address_line_1, 'maxlength="300"')}${text('城市', `${prefix}-city`, a.city, 'maxlength="120"')}${text('省份代码', `${prefix}-region`, a.region, 'maxlength="32" placeholder="ON"')}${text('邮编', `${prefix}-postal`, a.postal_code, 'maxlength="12"')}</div></section>`;
    return `${address('发货地', 'fc-origin', origin)}<div class="choice-list"><label class="choice-row"><input type="checkbox" name="origin_residential" ${d.origin?.residential ? 'checked' : ''}>住宅发货地</label><label class="choice-row"><input type="checkbox" name="origin_tailgate" ${d.origin?.tailgate_required ? 'checked' : ''}>提货需要尾板</label></div>${address('住宅收货地', 'fc-destination', destination)}<section class="form-section"><h3>提货与交付条件</h3><div class="field-grid">${text('预计发货日','fc-ship-date', date && [date.year,date.month,date.day].every(Number.isFinite) ? `${date.year}-${String(date.month).padStart(2,'0')}-${String(date.day).padStart(2,'0')}` : '', 'type="date"')}${text('可提货开始','fc-ready-at',time(d.destination?.ready_at),'type="time"')}${text('可提货结束','fc-ready-until',time(d.destination?.ready_until),'type="time"')}${select('卸货方式','fc-unload',bool(d.destination?.tailgate_required),[['no','收货人自行卸货，无需尾板'],['yes','需要尾板卸货']])}${select('送货预约','fc-appointment',bool(p.pallet_service_details?.appointment_delivery),yesNo)}${select('托盘可否叠放','fc-stackable',bool(p.has_stackable_pallets),[['yes','可叠放'],['no','不可叠放']])}</div><label class="choice-row"><input type="checkbox" name="protect_from_freeze" ${p.pallet_service_details?.protect_from_freeze ? 'checked' : ''}>需要防冻</label></section><section class="form-section"><h3>实体托盘明细</h3><p>每行填写一个实际托盘，重量包含包装；不同托盘分别填写。</p><input type="hidden" name="fc-pallet-count" value="${pallets.length}">${pallets.map((pallet, i) => `<fieldset class="carrier-pallet"><legend>托盘 ${i + 1}</legend><div class="field-grid">${[['weight','含包装重量 · lb',pallet.measurements?.weight?.value],['length','长 · in',pallet.measurements?.cuboid?.l],['width','宽 · in',pallet.measurements?.cuboid?.w],['height','高 · in',pallet.measurements?.cuboid?.h]].map(([key,label,v]) => text(label,name(key,i),v,'inputmode="decimal" pattern="[0-9]+([.][0-9]+)?"')).join('')}${text('托盘内件数',name('pieces',i),pallet.num_pieces,'type="number" min="1" step="1"')}${text('货物描述',name('description',i),pallet.description,'maxlength="200"')}${text('货运等级',name('class',i),pallet.freight_class,'maxlength="20" placeholder="例如：70"')}</div>${pallets.length > 1 ? `<button type="button" class="text-button" data-action="business-fc-remove" data-index="${i}">移除这个托盘</button>` : ''}</fieldset>`).join('')}<button type="button" class="button" data-action="business-fc-add" ${pallets.length >= 50 ? 'disabled' : ''}>添加托盘</button></section>`;
  }
  function read(data) {
    const get = key => String(data.get(key) || '').trim();
    const count = Number(get('fc-pallet-count'));
    if (!Number.isInteger(count) || count < 1 || count > 50) throw new Error('carrier_pallet_count_invalid');
    const flag = key => get(key) ? get(key) === 'yes' : null;
    const at = key => { const [hour,minute] = get(key).split(':').map(Number); return {hour,minute}; };
    const address = prefix => ({address_line_1:get(prefix+'-address'),city:get(prefix+'-city'),region:get(prefix+'-region').toUpperCase(),country:'CA',postal_code:get(prefix+'-postal').toUpperCase()});
    const [year,month,day] = get('fc-ship-date').split('-').map(Number);
    return {details:{origin:{address:address('fc-origin'),residential:data.has('origin_residential'),tailgate_required:data.has('origin_tailgate')},destination:{address:address('fc-destination'),residential:true,tailgate_required:flag('fc-unload'),ready_at:at('fc-ready-at'),ready_until:at('fc-ready-until'),signature_requirement:'not-required'},expected_ship_date:{year,month,day},packaging_type:'pallet',packaging_properties:{pallet_type:'ltl',has_stackable_pallets:flag('fc-stackable'),pallets:Array.from({length:count},(_,i)=>({measurements:{weight:{unit:'lb',value:get(name('weight',i))},cuboid:{unit:'in',l:get(name('length',i)),w:get(name('width',i)),h:get(name('height',i))}},description:get(name('description',i)),freight_class:get(name('class',i)),num_pieces:Number(get(name('pieces',i)))})),pallet_service_details:{appointment_delivery:flag('fc-appointment'),protect_from_freeze:data.has('protect_from_freeze')}},shipment_classification:data.has('origin_residential')?'C2C':'B2C'}};
  }
  return {render,read};
}
