import { agentInstallPrompt } from './market.js';

export function createOperationManual(ui) {
  const { esc, icon, link } = ui;
  const chapters = [['start', '快速上手'], ['account', '账号与服务开通'], ['keys', '管理 API Key'], ['rest', 'API 调用'], ['mcp', 'MCP 接入'], ['results', '结果与常见问题'], ['services', '接入新服务']];
  const command = () => `<div class="manual-command"><code>${esc(agentInstallPrompt())}</code><button type="button" class="button primary" data-action="market-copy">${icon('code')}复制指令</button></div>`;
  const code = (text) => `<pre class="code-sample">${esc(text)}</pre>`;
  const next = (id, title) => `<div class="manual-next"><span>下一步</span>${link(title, `guide/${id}`, false, 'arrow')}</div>`;
  const documents = {
    start: () => `<h1>快速上手</h1><p class="manual-lead">选择适合你的使用方式，开始使用 FreightClaw 的物流能力。</p><section><h2>通过 Agent 快速接入</h2><p>把下面这句话复制给 Codex、Claude Code 或其他能读取网页的 Agent。它会读取我们的公开指南，帮助你配置已开通的服务。</p>${command()}<ol><li>复制指令，发送给你的 Agent。</li><li>根据指引，在个人中心获取并保存 API Key。</li><li>完成一次只读调用，核对实际返回结果。</li></ol><div class="manual-tip">已有 Key 时直接复用。多项服务可以使用同一枚 Key，无需按服务重复创建。</div></section><section><h2>直接在网页上使用</h2><p>日常询价、查看报价记录、查询关税与估算税费，可以直接进入业务工作台。使用你的邮箱账号登录，并加入企业即可开始使用已开放的业务。</p><div class="manual-flow"><span>邮箱登录</span>${icon('arrow')}<span>进入业务工作台</span>${icon('arrow')}<span>选择业务</span></div>${link('打开业务工作台', 'workbench', true, 'arrow')}</section><section><h2>通过 CLI 使用</h2><p>下载安装包，使用同一把 API Key 从终端调用已开通的服务。支持 JSON 输入、结构化输出和业务状态退出码。</p>${link('查看 CLI 安装与使用', 'cli', true, 'code')}</section><section><h2>从市场选择能力</h2><p>市场按运费询价、关务税费、货物装载和 Agent 工具分类。每项服务都有用途、返回内容和接入方式说明。</p><p><strong>MCP · REST</strong> 表示同时提供 MCP 工具和 REST 接口；<strong>REST API</strong> 表示通过 HTTP 接口使用，Agent 也可按文档调用。</p>${link('浏览市场', 'market')}</section>${next('account', '账号与服务开通')}`,
    account: () => `<h1>账号与服务开通</h1><p class="manual-lead">人员使用邮箱账号，系统使用 API Key。两种方式对应同一企业的业务权限。</p><section><h2>登录与加入企业</h2><ol><li>点击页面右上角“登录 / 注册”，使用邮箱和密码登录。</li><li>首次注册时按提示完成邮箱验证。</li><li>收到企业邀请后，用对应邮箱登录，在成员页面点击接受邀请。</li></ol><p>忘记密码时使用登录页的找回入口。需要更换企业负责人或成员权限时，由企业管理员处理。</p>${link('查看成员与邀请', 'members')}</section><section><h2>一次申请所需服务</h2><p>进入个人中心的“已开通服务”，点击“申请服务”，选择能力并说明使用场景后提交。</p><p>已有接入应用会自动复用；没有应用时，系统在提交时建立默认接入应用。你不需要先去另一个页面填写应用资料。</p><div class="manual-tip">申请通过和正式开通分别显示。企业连接、来源数据或授权尚未就绪时，会保留具体待处理状态。</div>${link('申请服务', 'apply/new', true)}</section><section><h2>业务人员与开发者</h2><p>业务成员直接进入工作台处理询价与关务；应用负责人在个人中心创建、轮换和撤销 Key。企业管理员负责成员与应用归属，平台人员负责服务准入与开通。</p></section>${next('keys', '管理 API Key')}`,
    keys: () => `<h1>管理 API Key</h1><p class="manual-lead">一枚 Key 使用所选应用已开通的服务，列表集中展示当前状态。</p><section><h2>创建与保存</h2><ol><li>服务开通后，进入个人中心的“API Key”。</li><li>点击“创建 API Key”，填写便于识别的名称，选择有效期。</li><li>复制并保存完整 Key，点击“已保存，完成”。</li></ol><p>页面会自动验证安全的只读样例，并在原页面展示状态与请求编号，不需要换页粘贴 Key。</p>${link('管理 API Key', 'api-keys', true, 'key')}</section><section><h2>使用已有 Key</h2><p>当前 Key 可继续使用。较早创建的业务 Key 如需使用已授权的基础 MCP 工具，由负责人点击“启用基础工具”，原 Key 不变。</p><p>新增业务权限仍需申请并开通。开通后若列表提示“更新服务”，确认更新会轮换为包含当前服务的新 Key，旧 Key 随即失效；保存新值并更新自己的调用程序。普通轮换不增加权限。授权暂停或撤销后，Key 不能绕过这些限制。</p></section><section><h2>轮换与撤销</h2><p>完整 Key 只显示一次，后台无法重新显示旧明文。遗失时使用“轮换”生成新 Key；轮换会立即撤销旧 Key，应同时更新自己的调用程序。</p><p>停止对接时点击“撤销”。不要将 Key 放进聊天、公开文档、截图或代码仓库；在本机或服务端使用凭证管理工具保存。</p></section>${next('rest', 'API 调用')}`,
    rest: () => `<h1>API 调用</h1><p class="manual-lead">按固定接口提交业务资料，认证与服务转发由平台完成。</p><section><h2>接口地址与认证</h2><div class="endpoint-row"><span>HTTPS</span><code>https://www.freightclaw.net</code></div>${code('Authorization: ApiKey ${FREIGHTCLAW_API_KEY}\nContent-Type: application/json')}<p>所有基础工具与业务接口使用同一 API Key。普通 REST 调用可以直接携带 Key，无需自行处理换票。</p><a class="button" href="/console/openapi.json" download="freightclaw-openapi.json">下载 OpenAPI 文档</a></section><section><h2>选择操作与输入</h2><p>从市场进入服务详情，查看操作标识与接口路径。按 OpenAPI 中该操作的 Schema 填写实际资料，不添加企业 ID、操作者、上游地址或其他凭证。</p><p>业务接口的请求体如下，<code>input</code> 需要替换为所选服务规定的资料：</p>${code(JSON.stringify({ schema_version: 'business-call@2026-09-05.v1', input: {} }, null, 2))}<p>金额使用十进制字符串并标明币种，货物的重量、尺寸和体积使用规定单位。输入不完整时按结果提示补充。</p></section><section><h2>保留可追溯结果</h2><p>保存请求编号、业务状态和必要版本引用。调用成功不意味着报价已批准，也不意味着尚未发布的税则可以用于正式申报。</p><a class="text-button" href="/console/skill.md" target="_blank" rel="noopener">查看可供 Agent 读取的完整指南</a></section>${next('mcp', 'MCP 接入')}`,
    mcp: () => `<h1>MCP 接入</h1><p class="manual-lead">连接支持 Streamable HTTP 的 MCP 客户端，使用已经授权且当前开放的物流能力。</p><section><h2>支持的工具</h2><ul><li>货物计算：<code>cargo.calculate</code></li><li>装柜规划：<code>container.plan_summary</code></li><li>Agent 上下文：<code>system.agent_context.get</code></li></ul><p>业务 MCP 还支持关税归类、税费估算、尾程询价、资料提取及 Freightcom 询价。需要平台启用 business-v1；当前可用操作以客户端实际工具列表为准。</p></section><section><h2>推荐：由 Agent 配置</h2>${command()}<p>Agent 会根据当前客户端的配置方式完成接入。已有配置和 Key 优先复用。</p></section><section><h2>手动配置</h2><p>先用 API Key 兑换短期令牌：</p><div class="endpoint-row"><span>POST</span><code>/access/v2/application/mcp/token/exchange</code></div>${code(JSON.stringify({ schema_version: 'application-mcp-exchange@2026-09-06.v1', requested_tool_names: ['cargo.calculate', 'customs.query'] }, null, 2))}<p>将返回的短期令牌配置到 MCP 客户端：</p>${code('URL: https://www.freightclaw.net/mcp\nTransport: Streamable HTTP\nAuthorization: Bearer <access_token>')}<p>短期令牌按接口返回的有效期刷新。长期 API Key 不直接作为 MCP 的 Bearer 令牌。</p></section>${next('results', '结果与常见问题')}`,
    results: () => `<h1>结果与常见问题</h1><p class="manual-lead">按业务状态处理下一步，用请求编号定位问题。</p><section><h2>理解返回状态</h2><div class="manual-statuses">${[['success', '已完成', '本次操作完成，继续核对业务条件、来源和规则版本。'], ['needs_input', '待补充', '补齐接口列出的商品、货物、地址或交付资料。'], ['manual_review', '需要人工复核', '按照具体待核对事项交给业务负责人，不自动批准。'], ['blocked', '已阻止', '检查 Key、确认保存状态、有效期及当前服务权限。'], ['unavailable', '暂不可用', '核对服务连接、数据发布和依赖状态，稍后重试。']].map(([status, title, description]) => `<div><code>${status}</code><strong>${title}</strong><p>${description}</p></div>`).join('')}</div></section><section><h2>已经开通，为什么仍然查不到结果？</h2><p>服务授权与来源数据是两个条件。例如企业已获关务权限，但正式税则快照尚未发布时，接口仍会返回暂不可用。请按返回原因处理。</p></section><section><h2>完整 Key 找不到了</h2><p>完整 Key 不会在列表重复显示。由应用负责人轮换凭证，再更新自己的调用程序。</p></section><section><h2>如何排查一次调用？</h2><p>在个人中心打开“调用记录”，按应用、服务、结果和时间筛选，查看请求编号与耗时。统计按保留窗口计算，不是账单。关务历史从来源读取本人记录；恢复后需重新核对规则日期。</p>${link('打开调用诊断', 'diagnostics')}</section>${next('services', '接入新服务')}`,
    services: () => `<h1>接入新服务</h1><p class="manual-lead">新服务复用平台已有的企业、账号、应用与 Key，保留各自业务系统的权威。</p><section><h2>准备服务合同</h2><ol><li>明确业务操作、实际接口与负责人，区分查询、计算和有副作用的写入。</li><li>提供输入输出 Schema、版本、错误状态和调用示例。</li><li>明确企业隔离、操作权限和来源数据的就绪条件。</li></ol></section><section><h2>接入与验收</h2><p>适配器负责将平台上下文传递给源服务，校验返回结果与版本。写操作需要幂等、预览或审核约束，并在成功前完成写后读回。</p><p>完成权限、跨企业隔离、失败状态和生产连接验证后，再把真实支持的协议与服务说明加入市场。</p><div class="manual-tip">运价、税则和业务记录由源系统维护。平台不复制一套权威业务表，也不让模型替代确定性规则。</div></section><section><h2>继续复用已有 Key</h2><p>新服务按操作授权给原有应用。已有业务 Key 需要加入新增服务时，在同一 Key 列表点击“更新服务”并保存替换后的值；无需另建账号或并行保留两套 Key。内部适配和认证差异由平台处理。</p><a class="button" href="/console/openapi.json" target="_blank" rel="noopener">查看当前接口合同</a></section>`,
  };
  function page(chapter = 'start') {
    const selected = Object.hasOwn(documents, chapter) ? chapter : 'start';
    return `<div class="manual-shell"><aside class="manual-sidebar"><h2>操作手册</h2><nav aria-label="手册目录">${chapters.map(([id, title]) => `<button type="button" data-go="guide/${id}" ${selected === id ? 'aria-current="page"' : ''}>${title}</button>`).join('')}</nav><a href="/console/skill.md" target="_blank" rel="noopener">Agent 读取版 ${icon('arrow')}</a></aside><article class="manual-document">${documents[selected]()}</article></div>`;
  }
  return { page };
}
