// Existing Console visual language; configuration is empty until explicitly saved.
export function createNativeAdminUi({api,mutate,esc,head,note,icon,formError,model,rerender}){
 let loaded=null,pending='',approval=null,error='';
 const names={'customs-data':'关务数据','residential-rates':'私人地址运价',freightcom:'Freightcom 连接'};
 const context=()=>JSON.stringify([model().session?.identity?.user_id,model().session?.organization_id]);
 const reset=()=>{loaded=null;pending='';approval=null;error='';};
 const button=(text,action,primary=false,id='')=>`<button class="button ${primary?'primary':''}" type="button" data-action="native-${action}" data-id="${esc(id)}">${text}</button>`;
 const field=(label,name,value='',type='text',hint='')=>`<div class="field"><label for="native-${name}">${label}</label><input id="native-${name}" name="${name}" type="${type}" value="${esc(value??'')}" required ${type==='number'?'min="0" step="1"':''} maxlength="2000">${hint?`<small>${hint}</small>`:''}</div>`;
 function load(kind){const key=context()+kind;if(loaded?.key===key||pending===key)return;const origin=context();pending=key;api('/admin/'+kind).then(r=>{if(origin!==context()||pending!==key)return;loaded={key,data:r.data};pending='';error='';if(location.hash===`#business-admin/${kind}`)rerender();}).catch(e=>{if(origin!==context()||pending!==key)return;loaded={key,data:null};pending='';error=e.code==='native_management_denied'?'当前账号没有修改业务配置的权限。':'当前企业的业务后台暂时无法读取，请重新加载。';if(location.hash.startsWith('#business-admin'))rerender();});}
 const textArea=(label,name,value,hint)=>`<div class="field"><label for="native-${name}">${label}</label><textarea id="native-${name}" name="${name}" rows="5" required spellcheck="false">${esc(value||'')}</textarea><small>${hint}</small></div>`;
 function rateForm(d){return `<section class="form-section"><h2>运价与有效期</h2><div class="field-grid">${field('运价名称','label',d.label)}${field('始发仓','origin',d.origin)}${field('开始日期','valid_from',d.valid_from,'date')}${field('截止日期','valid_until',d.valid_until,'date')}${field('来源文件或协议编号','evidence_ref',d.evidence_ref)}${field('来源版本','evidence_version',d.evidence_version)}</div><p class="muted">自有运价按美元 USD 维护；Freightcom 按承运商返回的币种显示。</p>${textArea('客户适用条件','customer_terms',d.customer_terms,'明确路边交付、卸货、预约和报价有效条件。')}</section><section class="form-section"><h2>邮编与价格</h2>${textArea('邮编覆盖','zones',d.zones?.map(z=>[z.postal_prefix,z.zone,z.city,z.province].join(',')).join('\n'),'每行：邮编或前三位,分区编号,城市,省份代码。完整邮编优先；重复覆盖会阻止发布。')}${textArea('价格表 · USD','rates',d.rates?.map(r=>[r.zone,r.pallets,r.amount].join(',')).join('\n'),'每行：分区编号,计费托数,基础运价。只使用明确配置的档位，不外推。')}</section><section class="form-section"><h2>计费与货物范围</h2><div class="field-grid">${Object.entries({cbm_per_pallet:'每托体积 · m³',kg_per_pallet:'每托重量 · kg',long_piece_threshold_cm:'超长起点 · cm',long_piece_multiplier:'超长件折托倍数',flexible_packaging_threshold:'柔性包装人工复核起点 · 件',suspicious_min_pallets:'异常超长托数下限',suspicious_multiplier:'异常超长托数倍数',max_weight_kg:'最大总重 · kg',max_cbm:'最大体积 · m³',max_length_cm:'最大长度 · cm'}).map(([key,label])=>field(label,'billing.'+key,d.billing?.[key]??'')).join('')}</div></section><section class="form-section"><h2>附加费</h2><p>每项都需要确认。明确免费时填 0，空白不会被当成免费。</p><div class="field-grid">${Object.entries({fuel_percent:'燃油比例 · %',residential:'住宅费 · USD',liftgate:'尾板费 · USD',pallet_jack:'地牛费 · USD',appointment:'预约费 · USD',detention_free_minutes:'免费等待 · 分钟',detention_half_hour:'每半小时等待费 · USD'}).map(([key,label])=>field(label,'fees.'+key,d.fees?.[key]??'')).join('')}</div></section>`;}
 function facts(kind,input){if(kind==='residential-rates')return `<dl class="channel-preview-details">${[['运价',input.label],['始发仓',input.origin],['币种',input.currency],['有效期',input.valid_from+' 至 '+input.valid_until],['来源',input.evidence_ref+' / '+input.evidence_version],['覆盖',input.zones.length+' 项邮编 · '+input.rates.length+' 档价格'],['客户条件',input.customer_terms]].map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;return `<dl class="channel-preview-details"><div><dt>数据批次</dt><dd>${esc(input.label)}</dd></div><div><dt>核验日期</dt><dd>${esc(input.rule_date)}</dd></div><div><dt>数据量</dt><dd>${input.nomenclature.length} 项税号 · ${input.tariffs.length} 项税率 · ${input.measures.length} 项措施 · ${input.requirements.length} 项单证</dd></div></dl>${input.sources.map(s=>`<p><strong>${esc(s.authority)} · ${esc(s.dataset)}</strong><br>${esc(s.edition)} / ${esc(s.revision)} · ${esc(s.effective_from)} 至 ${esc(s.effective_to||'未指定截止日期')}<br><span class="native-source-url">${esc(s.official_url)}</span></p>`).join('')}`;}
 function page(kind='customs-data'){
  if(!names[kind])kind='customs-data';load(kind);const title=head('业务管理','先配置并核验来源，再发布给网页和 CLI 使用。','<a class="button" href="#channels">渠道与仓库</a>');const tabs=`<nav class="native-tabs" aria-label="业务配置">${Object.entries(names).map(([id,name])=>`<a href="#business-admin/${id}" ${id===kind?'aria-current="page"':''}>${icon(id==='customs-data'?'file':id==='residential-rates'?'truck':'key')}${name}</a>`).join('')}</nav>`;
  if(error)return title+tabs+note(error,'error')+button('重新加载','reload');if(!loaded||loaded.key!==context()+kind)return title+tabs+'<p role="status">正在读取配置…</p>';const value=loaded.data;
  if(kind==='freightcom')return title+tabs+`<div class="channel-layout"><form class="panel" data-form="native-freightcom"><div class="panel-body">${formError}<h2>连接承运商报价</h2><p>${value.credential_present?'已保存凭证。尚未通过实际询价验证当前连接。':'还没有配置凭证，暂时无法读取承运商费率。'}</p><div class="field-grid">${field('连接名称','label',value.label)}${field('Freightcom 正式凭证','credential','','password','保存后不会回显；替换时重新输入。')}</div><label class="choice-row"><input type="checkbox" name="confirmed" required><span>确认用于当前企业的承运商询价</span></label><div class="channel-actions"><button class="button primary">保存连接</button>${value.credential_present?button('停用连接','fc-disable'):''}</div></div></form><aside class="channel-guide"><h2>使用范围</h2><p>仅当前企业使用此连接。网页和 CLI 询价读取同一份配置。</p><p>保存凭证不会发送订舱或邮件。实际费率仍由承运商返回。</p><a href="#quote/private">进入私人地址询价</a></aside></div>`;
  const draft=value.draft||{};const publication=`<section class="native-publication" aria-label="当前发布状态"><strong>${value.active_release?'已发布 · 版本 '+esc(value.active_release.version):'尚未发布'}</strong><span>${value.active_release?esc(value.active_release.input.label):'查询暂不可用。先保存草稿，再核验发布。'}</span></section>`;return title+tabs+publication+`<div class="channel-layout"><div><form class="panel" data-form="native-save" data-kind="${kind}"><div class="panel-body">${formError}${kind==='residential-rates'?rateForm(draft):`<h2>导入关务数据</h2><p>上传已整理的来源数据包，核对税号、税率、贸易措施与单证依据。保存草稿不会立即生效。</p><div class="field"><label for="native-file">选择数据包 · JSON</label><input id="native-file" type="file" name="dataset_file" accept=".json,application/json"><small>最大 16 MB。格式说明见<a href="/console/native-business.md" target="_blank" rel="noopener">关务数据导入说明</a>。</small></div>${draft.label?facts(kind,draft):'<div class="native-empty"><h3>尚无数据批次</h3><p>导入前，关务查询会明确提示“尚未发布数据”。</p></div>'}`}<div class="channel-actions"><button class="button primary" type="submit">保存草稿</button>${value.draft?button('核验并预览发布','preview'):''}</div></div></form>${approval?`<section class="panel channel-confirm" aria-label="确认发布"><div class="panel-body"><h2>${approval.disable?'确认停用':approval.release_id?'确认回退':'确认发布'}</h2>${approval.input?facts(kind,approval.input):'<p>停用后，新查询将提示尚未发布。历史版本继续保留。</p>'}${approval.blockers?.length?note(approval.blockers.join(' '),'error'):''}${approval.input?`<details class="business-details"><summary>逐项核对完整配置与来源</summary><pre class="native-config-preview">${esc(JSON.stringify(approval.input,null,2))}</pre></details><p>请核对来源真实性、适用范围、费用及有效期。数据格式校验无法替代业务复核。</p>`:''}<div class="channel-actions">${approval.disable||approval.can_publish?button('确认'+(approval.disable?'停用':approval.release_id?'回退':'发布'),'confirm',true):''}${button('取消','cancel')}</div></div></section>`:''}<section class="panel channel-history"><div class="panel-body"><h2>发布记录</h2>${value.history.length?value.history.map(r=>`<div class="channel-release"><div><strong>${esc(r.label)}</strong><p>${esc(new Date(r.published_at).toLocaleString('zh-CN'))} · 版本 ${r.version}</p></div>${r.release_id===value.active_release?.release_id?'<span>当前发布</span>':button('预览回退','rollback',false,r.release_id)}</div>`).join(''):'<p>尚无发布记录。</p>'}</div></section></div><aside class="channel-guide"><h2>${names[kind]}</h2><p>${value.active_release?'当前发布：'+esc(value.active_release.input.label):'尚未发布，查询暂不可用。'}</p><p>先保存草稿，再核验预览。确认发布后，网页和 CLI 使用同一版本。</p>${value.active_release?button('停用当前版本','disable'):''}<h3>开始查询</h3><a href="${kind==='customs-data'?'#customs':'#quote/private'}">${kind==='customs-data'?'关务查询':'私人地址询价'} ${icon('arrow')}</a><h3>CLI 操作</h3><p>配置和查询均支持命令行。</p><a href="/console/native-business.md" target="_blank" rel="noopener">查看操作说明</a></aside></div>`;
 }
 function readRates(form){const f=new FormData(form),value=k=>String(f.get(k)||'').trim(),rows=k=>value(k).split(/\r?\n/u).filter(Boolean).map(line=>line.split(',').map(s=>s.trim()));const integers=new Set(['long_piece_multiplier','flexible_packaging_threshold','suspicious_min_pallets','suspicious_multiplier','detention_free_minutes']);const data={currency:'USD',billing:{},fees:{}};for(const [k,v]of f.entries()){if(k.includes('.')){const [group,key]=k.split('.');data[group][key]=integers.has(key)?Number(v):String(v).trim();}else if(!['zones','rates'].includes(k))data[k]=String(v).trim();}data.zones=rows('zones').map(r=>{if(r.length!==4)throw new Error('row');return {postal_prefix:r[0].replaceAll(' ','').toUpperCase(),zone:Number(r[1]),city:r[2],province:r[3].toUpperCase()};});data.rates=rows('rates').map(r=>{if(r.length!==3)throw new Error('row');return {zone:Number(r[0]),pallets:Number(r[1]),amount:r[2]};});return data;}
 const invalid=()=>Object.assign(new Error('native_input_invalid'),{code:'native_input_invalid'});
 async function submit(form){if(!form.dataset.form?.startsWith('native-'))return false;if(form.dataset.form==='native-freightcom'){const f=new FormData(form);await mutate('/admin/freightcom/save','POST',{expected_version:loaded.data.version,label:String(f.get('label')),credential:String(f.get('credential')),confirmation:'use_for_current_organization'});form.reset();reset();rerender();return true;}const kind=form.dataset.kind;let input;try{if(kind==='residential-rates')input=readRates(form);else{const file=new FormData(form).get('dataset_file');if(!file?.size||file.size>16*1024*1024)throw invalid();input=JSON.parse(await file.text());}}catch{throw invalid();}await mutate('/admin/'+kind+'/save','POST',{expected_version:loaded.data.version,input});reset();rerender();return true;}
 async function action(b){const a=b.dataset.action;if(!a?.startsWith('native-'))return false;const kind=location.hash.split('/')[1]||'customs-data';if(a==='native-reload'){reset();rerender();return true;}if(a==='native-cancel'){approval=null;rerender();return true;}const form=document.querySelector('form[data-form="native-save"]');if(kind==='residential-rates'&&form&&loaded?.data?.draft){let same;try{same=JSON.stringify(readRates(form))===JSON.stringify(loaded.data.draft);}catch{same=false;}if(!same){const d=readRates(form),old=loaded.data.draft;same=Object.keys(old).every(k=>JSON.stringify(d[k])===JSON.stringify(old[k]));}if(!same)throw Object.assign(new Error('channel_unsaved_changes'),{code:'channel_unsaved_changes'});}if(a==='native-preview'||a==='native-rollback'){approval=(await api('/admin/'+kind+'/preview'+(a==='native-rollback'?'?release_id='+encodeURIComponent(b.dataset.id):''))).data;rerender();document.querySelector('.channel-confirm')?.scrollIntoView({block:'center'});return true;}if(a==='native-disable'){approval={disable:true,version:loaded.data.version};rerender();return true;}if(a==='native-fc-disable'){await mutate('/admin/freightcom/disable','POST',{expected_version:loaded.data.version});reset();rerender();return true;}if(a==='native-confirm'){await mutate('/admin/'+kind+'/'+(approval.disable?'disable':approval.release_id?'rollback':'publish'),'POST',{expected_version:approval.version,...(approval.disable?{}:{preview_hash:approval.preview_hash,confirmation:'reviewed_sources_and_conditions'}),...(approval.release_id?{release_id:approval.release_id}:{})});reset();rerender();return true;}return false;}
 return {page,submit,action,reset};
}
