import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
import { zoneInputSchema, zoneDataSchema, QUOTE_PORTAL_SCHEMA_VERSION, QUOTE_SOURCE_SCHEMA_VERSION } from '../access-gateway/portal/business/quote-client';
import type { QuoteBusinessClientPort, PortalBusinessClientResult } from '../access-gateway/portal/business/service';
import type { ResidentialRates } from './contracts';
export interface QuoteRelease{version:number;release_id:string;input:ResidentialRates;published_at:string;digest:string}
export function calculateQuote(config:ResidentialRates,input:unknown,script=resolve('services/quote-native/run.py')):Promise<{status:'success'|'needs_input'|'manual_review'|'unavailable';data:unknown;reason_codes:string[]}>{
 return new Promise(resolveResult=>{const child=spawn('python3',[script],{stdio:['pipe','pipe','pipe'],env:{PATH:process.env.PATH??'/usr/bin:/bin',PYTHONIOENCODING:'utf-8',PYTHONDONTWRITEBYTECODE:'1'}});let bytes=0,output='';const fail=()=>resolveResult({status:'unavailable',data:null,reason_codes:['native_quote_runtime_unavailable']});const timer=setTimeout(()=>{child.kill('SIGKILL');fail();},10000);child.stdout.on('data',(b:Buffer)=>{bytes+=b.length;if(bytes>1048576){child.kill('SIGKILL');return;}output+=b.toString('utf8');});child.stderr.resume();child.stdin.on('error',()=>undefined);child.on('error',()=>{clearTimeout(timer);fail();});child.on('close',code=>{clearTimeout(timer);if(code!==0||bytes>1048576)return fail();try{const result=JSON.parse(output) as {status:'success'|'needs_input'|'manual_review'|'unavailable';data:unknown;reason_codes:string[]};if(!['success','needs_input','manual_review','unavailable'].includes(result.status)||!Array.isArray(result.reason_codes))return fail();resolveResult(result);}catch{fail();}});child.stdin.end(JSON.stringify({config,request:input}));});
}
export function createNativeQuoteClient(current:()=>QuoteRelease|null,script?:string):QuoteBusinessClientPort{
 const result=(requestId:string,status:PortalBusinessClientResult['status'],code:string|null,data:unknown=null,refs:unknown[]=[])=>({schema_version:QUOTE_PORTAL_SCHEMA_VERSION,source_schema_version:QUOTE_SOURCE_SCHEMA_VERSION,status,data,reason_codes:code?[code]:[],source_refs:refs,request_id:requestId,preview_only:true,saved:false,sendable:false});
 return {
 async preview({input,requestId}){const p=zoneInputSchema.safeParse(input);if(!p.success)return result(requestId,'needs_input','quote_request_invalid');const release=current();if(!release)return result(requestId,'unavailable','native_quote_not_published');const date=new Date().toISOString().slice(0,10);if(date<release.input.valid_from||date>release.input.valid_until)return result(requestId,'unavailable','native_quote_release_expired');const calculated=await calculateQuote(release.input,p.data,script);if(current()?.release_id!==release.release_id)return result(requestId,'unavailable','native_quote_release_changed');if(calculated.status!=='success')return result(requestId,calculated.status,calculated.reason_codes[0]??'native_quote_failed');const checked=zoneDataSchema.safeParse(calculated.data);if(!checked.success)return result(requestId,'unavailable','native_quote_result_invalid');return result(requestId,'success',null,{...checked.data,match_trace:{...checked.data.match_trace,published_version:release.version}},[{source_id:release.release_id,source_type:'internal_system',system:'freightclaw-native-quote',locator:release.input.evidence_ref,version:release.input.evidence_version,retrieved_at:release.published_at,authority:'authoritative',content_hash:`sha256:${release.digest}`}]);},
 extract:({requestId})=>Promise.resolve(result(requestId,'unavailable','native_extraction_not_configured')),
 };
}
