import { it, expect } from 'vitest';
import { calculateQuote, createNativeQuoteClient } from '../../services/quote-native/client';
import { validateResidentialRates } from '../../services/quote-native/contracts';
import { config, request } from './fixture';
it('calculates native Decimal price with explicit configured pallet rounding and fees',async()=>{const r=await calculateQuote(config,request);expect(r.status).toBe('success');expect(r.data).toMatchObject({billing_pallets:2,base_price:'180.00',fuel:'18.00',total_price:'268.00',accessorials:{residential_fee_usd:'20.00',liftgate_fee_usd:'30.00',appointment_fee_usd:'5.00',detention_fee_usd:'15.00'}});});
it('does not borrow another zone, extrapolate price, or ignore measurements',async()=>{for(const [patch,reason]of [[{postal_code:'V6B 1A1'},'postal_not_covered'],[{cbm:'10'},'pallet_rate_not_configured'],[{longest_side_cm:null},'cargo_measurements_required'],[{weight_kg:'10001'},'cargo_outside_published_limits'],[{province:'BC'},'postal_province_conflict']] as const){expect((await calculateQuote(config,{...request,...patch})).reason_codes).toContain(reason);}});
it('requires explicit rates and separates absent fees from explicit zero',()=>{expect(validateResidentialRates(config)).toEqual([]);expect(validateResidentialRates({...config,fees:{...config.fees,residential:undefined}}).length).toBeGreaterThan(0);expect(validateResidentialRates({...config,zones:[...config.zones,...config.zones]})).toContain('邮编覆盖重复。');});
it('rejects unpublished or expired releases and rereads release after calculation',async()=>{const r={version:1,input:config,release_id:'native-test',published_at:new Date().toISOString(),digest:'a'.repeat(64)};let calls=0;const client=createNativeQuoteClient(()=>++calls===1?r:null);expect((await client.preview({input:request,actor:{type:'user',id:'u'},requestId:'req_native1234'})).reason_codes).toContain('native_quote_release_changed');expect((await createNativeQuoteClient(()=>null).preview({input:request,actor:{type:'user',id:'u'},requestId:'req_native1234'})).status).toBe('unavailable');});

it("rejects sub-cent money instead of producing inconsistent line sums",()=>{expect(validateResidentialRates({...config,fees:{...config.fees,residential:"0.004"}}).length).toBeGreaterThan(0);expect(validateResidentialRates({...config,rates:[{zone:1,pallets:1,amount:"100.005"}]}).length).toBeGreaterThan(0);});
