import {it,expect} from 'vitest';
import {prepareSharedQuote} from '../../services/quote-native/shared-quote';
import {cargoTotals,type CargoLine} from '../../services/quote-native/cargo-lines';
import {freightcomRateRequestSchema} from '../../src/logistics_mcp/adapters/quote/freightcom-rate-adapter';
import {request} from './fixture';
const row:CargoLine={id:'pallet1',quantity:2,packaging_type:'pallet',length_cm:'100',width_cm:'100',height_cm:'100',weight:{mode:'unit_weight',value_kg:'50'}};
function input(r:CargoLine=row){const {lines:_lines,...totals}=cargoTotals([r]);void _lines;return {request:{...request,...totals,explicit_pallet_count:2,address_line:'1 Synthetic Road',city:'Toronto',requires_pallet_jack:false,extensions:{cargo_lines_v1:[r]}},transport:{origin:{address:{address_line_1:'2 Synthetic Road',city:'Toronto',region:'ON',country:'CA'},residential:false,tailgate_required:false},ship_date:'2026-09-10',ready_at:{hour:9,minute:0},ready_until:{hour:16,minute:0},description:'Synthetic cargo',freight_class:'70',protect_from_freeze:false}};}
it('projects physical pallets individually and preserves shared destination, measurements and unloading conditions',()=>{const x=input();Object.assign(x.transport.origin.address,{postal_code:'M1B 5W9'});const r=prepareSharedQuote(x);expect(r.status).toBe('success');expect(freightcomRateRequestSchema.safeParse(r.data).success).toBe(true);expect(r.data?.details.packaging_properties.pallets).toHaveLength(2);expect(r.data?.details.packaging_properties.pallets[1]?.measurements.weight.value).toBe('50');expect(r.data?.details.destination.tailgate_required).toBe(true);});
it('never treats billing pallets or averaged group weights as physical freightcom units',()=>{for(const r of [{...row,packaging_type:'carton' as const},{...row,weight:{mode:'line_total_weight' as const,value_kg:'100'}}]){const x=input(r);Object.assign(x.transport.origin.address,{postal_code:'M1B 5W9'});expect(prepareSharedQuote(x).status).toBe('needs_input');}});
