import Decimal from 'decimal.js';
import { NativeCustomsEngine, type NativeReleaseReader } from './engine';
import { publicationIdentity } from './upstream/worker/query/publication-identity';
import { inputSchema, queryResponseSchema, CUSTOMS_PORTAL_SCHEMA_VERSION } from '../access-gateway/portal/business/customs-client';
import { singleInputSchema, batchInputSchema, singleResponseSchema, batchResponseSchema, TAX_PORTAL_SCHEMA_VERSION, type TaxSourceEstimateResponse } from '../access-gateway/portal/business/tax-client';
import { convertValue, estimateTariffBreakdown } from './upstream/shared/domain/tariff-estimate';
import type { CustomsBusinessClientPort, TaxBusinessClientPort, PortalBusinessClientResult } from '../access-gateway/portal/business/service';
type Request={input:unknown;actor:{type:'user'|'service';id:string};requestId:string};
export function createNativeCustomsClients(reader:NativeReleaseReader):{customsClient:CustomsBusinessClientPort;taxClient:TaxBusinessClientPort}{
 const engine=new NativeCustomsEngine(reader);
 const fail=(version:string,status:PortalBusinessClientResult['status'],code:string,requestId?:string):PortalBusinessClientResult=>({schema_version:version,status,data:null,reason_codes:[code],...(requestId?{request_id:requestId}:{})});
 async function query(request:Request){const p=inputSchema.safeParse(request.input);if(!p.success)return fail(CUSTOMS_PORTAL_SCHEMA_VERSION,'needs_input','customs_request_invalid');const attributes=Object.fromEntries(Object.entries(p.data.attributes).map(([k,v])=>[k,v==='yes'?true:v==='no'?false:v]));const before=reader.current(p.data.ruleDate);const result=await engine.query({...p.data,attributes});if(!result.data||!before)return {...result,schema_version:CUSTOMS_PORTAL_SCHEMA_VERSION};const identity=await publicationIdentity(before.snapshot,before.sources,p.data.ruleDate,'freightclaw-native-customs/1');if(!identity||reader.current(p.data.ruleDate)?.release_id!==before.release_id)return fail(CUSTOMS_PORTAL_SCHEMA_VERSION,'unavailable','native_customs_release_changed');const data={...result.data,...identity,contractVersion:'riskcustoms-query.v2',requestId:request.requestId,delegatedActor:{type:request.actor.type,ref:request.actor.id,applicationId:'freightclaw-native'},dataStatus:{...result.data.dataStatus,...identity,contractVersion:'riskcustoms-query.v2',testData:false}};const checked=queryResponseSchema.safeParse(data);return checked.success?{schema_version:CUSTOMS_PORTAL_SCHEMA_VERSION,status:result.status,data:checked.data,reason_codes:result.reason_codes}:fail(CUSTOMS_PORTAL_SCHEMA_VERSION,'unavailable','native_customs_result_invalid');}
 async function estimate(request:Request):Promise<PortalBusinessClientResult>{
  const parsed=singleInputSchema.safeParse(request.input);if(!parsed.success)return fail(TAX_PORTAL_SCHEMA_VERSION,'needs_input','tax_request_invalid',request.requestId);
  const {ruleDate,...input}=parsed.data;
  if(!input.hsCode||!input.destinationCountry||!input.declaredValue||!input.currency||!input.attributes)return fail(TAX_PORTAL_SCHEMA_VERSION,'needs_input','tax_required_fields_missing',request.requestId);
  const release=reader.current(ruleDate),target=input.destinationCountry==='CA'?'CAD':'USD',convertedCurrency=input.currency!==target,fx=release?.exchange_rates;
  if(convertedCurrency&&(!fx||fx.effective_date>ruleDate||fx.expires_at<=`${ruleDate}T00:00:00.000Z`))return fail(TAX_PORTAL_SCHEMA_VERSION,'needs_input','native_official_exchange_rate_required',request.requestId);
  const r=await query({...request,input:{query:input.hsCode,codeCountry:input.destinationCountry,selectedHs6:input.hsCode.slice(0,6),ruleDate,attributes:{...input.attributes,...(input.attributes.contains_steel_aluminum!==undefined?{contains_steel_aluminum:input.attributes.contains_steel_aluminum?'yes':'no'}:{})}}});
  if(!r.data)return fail(TAX_PORTAL_SCHEMA_VERSION,r.status,r.reason_codes[0]??'native_customs_not_published',request.requestId);
  if(reader.current(ruleDate)?.release_id!==release?.release_id)return fail(TAX_PORTAL_SCHEMA_VERSION,'unavailable','native_customs_release_changed',request.requestId);
  const d=queryResponseSchema.parse(r.data),country=d.results.find(c=>c.country===input.destinationCountry&&c.code===input.hsCode);
  if(!country)return fail(TAX_PORTAL_SCHEMA_VERSION,'manual_review','tax_classification_requires_review',request.requestId);
  const converted=convertValue({name:input.description??input.hsCode,hsCode:input.hsCode,quantity:null,declaredValue:input.declaredValue,currency:input.currency},input.destinationCountry,fx?{usdCny:new Decimal(fx.usd_to_cad).div(fx.cny_to_cad).toFixed(16),cadCny:new Decimal(1).div(fx.cny_to_cad).toFixed(16)}:{});
  const breakdown=estimateTariffBreakdown(country,converted,input.destinationCountry,{ready:d.dataStatus.ready,testData:d.testData});
  const status=breakdown.status==='confirmed'?'success':'manual_review',money=(amount:string|null)=>amount===null?null:{amount,currency:converted.currency as 'USD'|'CAD'};
  const result:TaxSourceEstimateResponse['result']={lineId:input.lineId,status,input,publication:{ruleDate,serviceVersion:d.serviceVersion,publishedAt:d.publishedAt,releaseIds:d.releaseIds,snapshotHash:d.snapshotHash,releaseHash:d.releaseHash,evaluatedAt:d.dataStatus.evaluatedAt!,lastSourceCheckAt:d.dataStatus.lastSourceCheckAt,testData:false},exchangeRate:convertedCurrency&&fx?{sourceAuthorities:[fx.source_authority],sourceUrl:fx.source_url,effectiveDate:fx.effective_date,fetchedAt:fx.fetched_at,selection:fx.effective_date===ruleDate?'same_day':'latest_business_day',fromCurrency:input.currency,toCurrency:target,rate:new Decimal(input.currency==='CNY'?fx.cny_to_cad:input.currency==='USD'?fx.usd_to_cad:'1').div(target==='CAD'?'1':fx.usd_to_cad).toFixed(16)}:null,valueForDuty:money(breakdown.valueForDuty),valueForTax:money(breakdown.valueForTax),confirmedSubtotal:money(breakdown.estimatedAmount),customsPayable:status==='success'?money(breakdown.customsPayable):null,lines:[...breakdown.lines],sources:d.sources,reasonCodes:status==='success'?[]:['tax_requires_review']};
  const checked=singleResponseSchema.safeParse({contractVersion:'riskcustoms-tariff-estimate.v1',requestId:request.requestId,status,delegatedActor:d.delegatedActor,result});return checked.success?{schema_version:TAX_PORTAL_SCHEMA_VERSION,status,data:checked.data,reason_codes:result.reasonCodes,request_id:request.requestId}:fail(TAX_PORTAL_SCHEMA_VERSION,'unavailable','native_tax_result_invalid',request.requestId);
 }
 async function estimateBatch(request:Request):Promise<PortalBusinessClientResult>{const p=batchInputSchema.safeParse(request.input);if(!p.success)return fail(TAX_PORTAL_SCHEMA_VERSION,'needs_input','tax_request_invalid',request.requestId);const results:TaxSourceEstimateResponse['result'][]=[];const release=reader.current(p.data.ruleDate)?.release_id;
  for(const item of p.data.items){const r=await estimate({...request,input:{...item,ruleDate:p.data.ruleDate}});if(r.data){results.push(singleResponseSchema.parse(r.data).result);}else results.push({lineId:item.lineId,status:r.status==='blocked'?'unavailable':r.status,input:item,publication:null,exchangeRate:null,valueForDuty:null,valueForTax:null,confirmedSubtotal:null,customsPayable:null,lines:[],sources:[],reasonCodes:[...r.reason_codes]});}
  if(reader.current(p.data.ruleDate)?.release_id!==release)return fail(TAX_PORTAL_SCHEMA_VERSION,'unavailable','native_customs_release_changed',request.requestId);
  const counts={total:results.length,success:0,needsInput:0,manualReview:0,unavailable:0};for(const r of results)counts[r.status==='needs_input'?'needsInput':r.status==='manual_review'?'manualReview':r.status]++;
  const partialFailure=new Set(results.map(r=>r.status)).size>1,status=counts.success===results.length?'success':partialFailure||counts.manualReview?'manual_review':counts.needsInput===results.length?'needs_input':'unavailable';const data=batchResponseSchema.parse({contractVersion:'riskcustoms-tariff-estimate.v1',requestId:request.requestId,status,partialFailure,counts,results,delegatedActor:{type:request.actor.type,ref:request.actor.id,applicationId:'freightclaw-native'}});return {schema_version:TAX_PORTAL_SCHEMA_VERSION,status,data,reason_codes:status==='success'?[]:['tax_batch_requires_attention'],request_id:request.requestId};
 }
 return {customsClient:{query},taxClient:{estimate,estimateBatch}};
}
