import { z } from 'zod';
const text=z.string().max(50000);
const date=z.iso.date();
const hash=z.string().regex(/^[a-f0-9]{64}$/u);
export const nativeExchangeSchema=z.object({effective_date:z.iso.date(),expires_at:z.iso.datetime(),fetched_at:z.iso.datetime(),source_url:z.url().refine(v=>new URL(v).protocol==='https:'&&!new URL(v).username&&!new URL(v).password),source_authority:z.enum(['CBSA','BoC']),usd_to_cad:z.string().regex(/^[0-9]+(?:\.[0-9]+)?$/u).refine(v=>Number(v)>0),cny_to_cad:z.string().regex(/^[0-9]+(?:\.[0-9]+)?$/u).refine(v=>Number(v)>0)}).strict();
const country=z.enum(['CN','US','CA']);
const tradeCountry=z.enum(['US','CA']);
export const ReleaseFieldsSchema=z.object({
 release_status:z.enum(["staged","reviewed","published","superseded"]),
 release_authority:text,
 release_dataset:text,
 release_edition:text,
 release_revision:text,
 release_languages_json:text,
 release_official_url:text,
 release_published_at:text,
 release_effective_from:date,
 release_effective_to:date.nullable(),
 release_retrieved_at:text,
 release_manifest_sha256:hash,
 release_parser_name:text,
 release_parser_version:text,
 release_supersedes_id:text.nullable(),
}).strict();
export const NomenclatureRowSchema=ReleaseFieldsSchema.extend({
 id:z.number().int(),
 release_id:text,
 artifact_id:text,
 country:country,
 code:text,
 display_code:text,
 code_digits:z.number().int(),
 level:z.number().int(),
 parent_code:text.nullable(),
 is_declarable:z.number().int(),
 description_original:text,
 language:text,
 statistical_unit_json:text,
 effective_from:date,
 effective_to:date.nullable(),
 source_locator:text,
 raw_row_hash:hash,
 concept_id:text.optional(),
 concept_code:text.optional(),
 hs_edition:text.optional(),
 mapping_status:z.enum(["exact_prefix","reviewed"]).optional(),
}).strict();
export const TariffRuleRowSchema=ReleaseFieldsSchema.extend({
 id:text,
 release_id:text,
 artifact_id:text,
 country:country,
 code:text,
 code_match_type:z.enum(["exact","prefix","chapter99_link"]),
 measure_type:text,
 treatment:text,
 origin_country:text.nullable(),
 rate_expression_raw:text,
 rate_components_json:text,
 parse_status:z.enum(["confirmed","review"]),
 condition_text_raw:text,
 conditions_json:text,
 interaction_json:text,
 effective_from:date,
 effective_to:date.nullable(),
 priority:z.number().int(),
 source_locator:text,
 raw_row_hash:hash,
}).strict();
export const TradeMeasureRowSchema=ReleaseFieldsSchema.extend({
 id:text,
 release_id:text,
 artifact_id:text,
 country:tradeCountry,
 measure_type:text,
 origin_country:text,
 code_hint:text.nullable(),
 legal_scope:text,
 case_number:text.nullable(),
 exporter_or_producer:text.nullable(),
 rate_expression_raw:text.nullable(),
 exceptions_json:text,
 match_status:z.enum(["possible","confirmed_by_rule","manual_review"]),
 effective_from:date,
 effective_to:date.nullable(),
 source_locator:text,
 raw_row_hash:hash,
}).strict();
export const RequirementRowSchema=ReleaseFieldsSchema.extend({
 id:text,
 release_id:text,
 artifact_id:text,
 country:country,
 side:z.enum(["cn_export","us_import","ca_import"]),
 label:text,
 document_status:z.enum(["prepare_retain","required_now","conditional","on_request","not_applicable","manual_review"]),
 conditions_json:text,
 reason:text,
 effective_from:date,
 effective_to:date.nullable(),
 source_locator:text,
 raw_row_hash:hash,
}).strict();
export const SourceRowSchema=z.object({
 id:text,
 country:country,
 authority:text,
 dataset:text,
 edition:text,
 revision:text,
 languages_json:text,
 official_url:text,
 published_at:text,
 effective_from:date,
 effective_to:date.nullable(),
 retrieved_at:text,
 manifest_sha256:hash,
 parser_name:text,
 parser_version:text,
 supersedes_id:text.nullable(),
 status:z.enum(["staged","reviewed","published","superseded"]),
}).strict();
export const PublicationSnapshotRowSchema=z.object({
 id:text,
 evaluated_at:text,
 rule_date:date,
 ready:z.number().int(),
 release_ids_json:text,
 approval_ids_json:text,
 reasons_json:text,
 gate_report_sha256:hash,
 last_source_check_at:text.nullable(),
 test_data:z.number().int().nullable().optional(),
}).strict();
export const customsDatasetSchema=z.object({label:z.string().trim().min(1).max(100),rule_date:date,test_data:z.boolean(),exchange_rates:nativeExchangeSchema.optional(),sources:z.array(SourceRowSchema).min(1).max(100),nomenclature:z.array(NomenclatureRowSchema).min(1).max(100000),tariffs:z.array(TariffRuleRowSchema).max(100000),measures:z.array(TradeMeasureRowSchema).max(100000),requirements:z.array(RequirementRowSchema).max(10000)}).strict();
export type CustomsDataset=z.infer<typeof customsDatasetSchema>;
