import {customsBrowseInput,customsBrowseResult} from './catalog';
import {packageImport,packagePublish,packageDisable,packageView,packageList} from './package-contracts';
import {createHash,randomUUID} from 'node:crypto';
import {createReadStream,existsSync,lstatSync,mkdirSync,chmodSync,constants,openSync,readSync,closeSync} from 'node:fs';
import {copyFile,unlink} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import {z} from 'zod';
import {PortalError,type PortalContext} from '../access-gateway/portal/contracts';
import type {PortalService} from '../access-gateway/portal/service';
import type {NativeAdminStore} from '../access-gateway/portal/native-admin';
import {PublicationSnapshotRowSchema,SourceRowSchema} from './contracts';
import {checkPackagePublication} from './package-publication';
import type {NativeCustomsRelease} from './engine';
import {CustomsRepository,type NativeSqlStatement} from './upstream/worker/repositories/customs-sql';
type Package=z.infer<typeof packageView>;
function checksumSync(path:string){const hash=createHash('sha256'),fd=openSync(path,'r'),buffer=Buffer.alloc(1024*1024);try{let n;while((n=readSync(fd,buffer,0,buffer.length,null))>0)hash.update(buffer.subarray(0,n));return hash.digest('hex');}finally{closeSync(fd);}}
function fileIdentity(path:string){const s=lstatSync(path);if(!s.isFile()||s.isSymbolicLink()||existsSync(path+'-wal'))throw new Error('snapshot_changed');return [s.dev,s.ino,s.size,s.mtimeMs,s.ctimeMs].join(':');}
async function checksum(path:string){const hash=createHash('sha256');for await(const chunk of createReadStream(path))hash.update(chunk as Buffer);return hash.digest('hex');}
function inspect(path:string){const db=new DatabaseSync(path,{readOnly:true});try{db.exec('PRAGMA query_only=ON; PRAGMA trusted_schema=OFF');if(db.prepare('PRAGMA quick_check').get()?.quick_check!=='ok')throw new Error('integrity');const tables=['source_release','nomenclature','tariff_rule','trade_measure','regulatory_requirement','publication_snapshot'];const counts:Record<string,number>={};for(const table of tables)counts[table]=Number(db.prepare('SELECT COUNT(*) AS n FROM '+table).get()!.n);const sources=SourceRowSchema.array().max(100).parse(db.prepare('SELECT * FROM source_release ORDER BY id').all());const raw=db.prepare('SELECT * FROM publication_snapshot ORDER BY rule_date DESC,evaluated_at DESC,id DESC LIMIT 1').get();const snapshot=raw?PublicationSnapshotRowSchema.parse(raw):null;const blockers=checkPackagePublication(snapshot?{...snapshot,test_data:snapshot.test_data??null}:null,sources);return {counts,sources,snapshot,blockers};}finally{db.close();}}
export class CustomsPackages{
 private cache=new Map<string,{db:DatabaseSync;release:NativeCustomsRelease;identity:string}>();
 private importing=false;
 readonly directory:string;
 constructor(private store:NativeAdminStore,private portal:Pick<PortalService,'getState'>,private inbox:string){mkdirSync(inbox,{recursive:true,mode:0o700});this.directory=resolve(inbox,'../customs-packages');mkdirSync(this.directory,{recursive:true,mode:0o700});store.db.exec('CREATE TABLE IF NOT EXISTS customs_packages(id TEXT PRIMARY KEY,org TEXT NOT NULL,payload TEXT NOT NULL);CREATE TABLE IF NOT EXISTS customs_package_active(org TEXT PRIMARY KEY,id TEXT);');}
 private scope(ctx:PortalContext){const s=this.portal.getState(ctx).data;if(!ctx.identity.emailVerified||!ctx.organizationId||ctx.identity.platformRole!==null||s?.current_organization?.status!=='active'||!s.memberships.some(m=>m.organizationId===ctx.organizationId&&m.userId===ctx.identity.userId&&m.status==='active'&&['owner','admin'].includes(m.role)))throw new PortalError('native_management_denied');return ctx.organizationId;}
 private active(org:string){return (this.store.db.prepare('SELECT id FROM customs_package_active WHERE org=?').get(org) as {id:string|null}|undefined)?.id??null;}
 list(ctx:PortalContext){const org=this.scope(ctx);return {selected:this.hasSelection(org),active_id:this.active(org),items:this.store.db.prepare('SELECT payload FROM customs_packages WHERE org=? ORDER BY rowid DESC LIMIT 100').all(org).map(r=>packageView.parse(JSON.parse(String(r.payload))))};}
 browse(ctx:PortalContext,input:unknown){const f=customsBrowseInput.parse(input),state=this.list(ctx),row=f.selection==='published'?state.items.find(r=>r.id===state.active_id):state.items[0];const base={selection:f.selection,collection:f.collection,offset:f.offset,limit:f.limit,label:row?.label??null,release_id:row?.id??null,version:0,total:0,rows:[]};if(!row)return customsBrowseResult.parse(base);const tables={nomenclature:'nomenclature',tariffs:'tariff_rule',measures:'trade_measure',requirements:'regulatory_requirement',sources:'source_release'};const searches={nomenclature:['code','description_original'],tariffs:['code','treatment','condition_text_raw'],measures:['code_hint','legal_scope','case_number'],requirements:['label','reason'],sources:['authority','dataset','edition','revision']};const table=tables[f.collection],db=new DatabaseSync(join(this.directory,row.id+'.sqlite'),{readOnly:true});try{db.exec('PRAGMA query_only=ON; PRAGMA trusted_schema=OFF');const where:string[]=[],values:SQLInputValue[]=[];if(f.country!=='all'){where.push('country=?');values.push(f.country);}for(const term of f.query.split(/\s+/u).filter(Boolean)){where.push('('+searches[f.collection].map(k=>`instr(lower(coalesce(${k},'')),lower(?))>0`).join(' OR ')+')');values.push(...searches[f.collection].map(()=>term));}const filter=where.length?' WHERE '+where.join(' AND '):'';const total=Number(db.prepare('SELECT COUNT(*) AS n FROM '+table+filter).get(...values)!.n);const rows=db.prepare('SELECT * FROM '+table+filter+' ORDER BY id LIMIT ? OFFSET ?').all(...values,f.limit,f.offset).map(r=>{if(f.collection==='sources')return r;const source=row.sources.find(s=>s.id===r.release_id);if(!source)throw new PortalError('customs_package_invalid');return {...r,...Object.fromEntries(Object.entries(source).filter(([k])=>k!=='id'&&k!=='country').map(([k,v])=>['release_'+k,v]))};});return customsBrowseResult.parse({...base,total,rows});}finally{db.close();}}
 private commit(ctx:PortalContext,action:string,input:unknown,key:string,fn:(org:string)=>void){const org=this.scope(ctx),db=this.store.db,partition=JSON.stringify([org,ctx.identity.userId,'customs-package',action]),digest=createHash('sha256').update(JSON.stringify(input)).digest('hex');if(!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('idempotency_key_invalid');db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT digest,result FROM native_idempotency WHERE scope=? AND key=?').get(partition,key);if(old){if(old.digest!==digest)throw new PortalError('idempotency_conflict');db.exec('COMMIT');return packageList.parse(JSON.parse(String(old.result)));}fn(org);const result=this.list(ctx);db.prepare('INSERT INTO native_audit VALUES(?,?,?,?,?,?,?)').run(randomUUID(),org,'customs',ctx.identity.userId,action,digest,new Date().toISOString());db.prepare('INSERT INTO native_idempotency VALUES(?,?,?,?)').run(partition,key,digest,JSON.stringify(result));db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
 private replay(ctx:PortalContext,action:string,input:unknown,key:string){const org=this.scope(ctx);if(!/^[A-Za-z0-9._:-]{16,128}$/u.test(key))throw new PortalError('idempotency_key_invalid');const partition=JSON.stringify([org,ctx.identity.userId,'customs-package',action]),digest=createHash('sha256').update(JSON.stringify(input)).digest('hex');const old=this.store.db.prepare('SELECT digest,result FROM native_idempotency WHERE scope=? AND key=?').get(partition,key);if(!old)return null;if(old.digest!==digest)throw new PortalError('idempotency_conflict');return packageList.parse(JSON.parse(String(old.result)));}
 async import(ctx:PortalContext,input:unknown,key:string){
  const d=packageImport.parse(input),replay=this.replay(ctx,'package-import',d,key);if(replay)return replay;
  if(this.importing)throw new PortalError('customs_package_import_busy');this.importing=true;
  let destination:string|undefined,copied=false,retained=false;
  try{
   const source=join(this.inbox,d.filename),stat=lstatSync(source);
   if(!stat.isFile()||stat.isSymbolicLink()||stat.size>4*1024**3||stat.size<512||existsSync(source+'-wal'))throw new PortalError('customs_package_snapshot_required');
   if(await checksum(source)!==d.sha256)throw new PortalError('customs_package_hash_mismatch');
   const id=randomUUID();destination=join(this.directory,id+'.sqlite');await copyFile(source,destination,constants.COPYFILE_EXCL);copied=true;chmodSync(destination,0o400);
   if(await checksum(destination)!==d.sha256)throw new PortalError('customs_package_hash_mismatch');
   let facts:ReturnType<typeof inspect>;try{facts=inspect(destination);}catch{throw new PortalError('customs_package_invalid');}
   const row:Package={id,label:d.label,sha256:d.sha256,created_at:new Date().toISOString(),state:facts.blockers.length?'blocked':'ready',rule_date:facts.snapshot?.rule_date??null,counts:facts.counts,sources:facts.sources,blockers:facts.blockers};
   const result=this.commit(ctx,'package-import',d,key,org=>{this.store.db.prepare('INSERT INTO customs_packages VALUES(?,?,?)').run(id,org,JSON.stringify(row));});retained=result.items.some(item=>item.id===id);return result;
  }finally{try{if(copied&&!retained&&destination)await unlink(destination);}finally{this.importing=false;}}
 }
 async publish(ctx:PortalContext,input:unknown,key:string){const org=this.scope(ctx),d=packagePublish.parse(input),replay=this.replay(ctx,'package-publish',d,key);if(replay)return replay;const row=this.list(ctx).items.find(x=>x.id===d.id);if(!row)throw new PortalError('customs_package_not_found');const path=join(this.directory,row.id+'.sqlite');if(await checksum(path)!==row.sha256||d.sha256!==row.sha256)throw new PortalError('customs_package_hash_mismatch');const facts=inspect(path);if(facts.blockers.length)throw new PortalError('customs_package_not_ready');return this.commit(ctx,'package-publish',d,key,()=>{if(this.active(org)!==d.expected_active)throw new PortalError('version_conflict');this.store.db.prepare('INSERT INTO customs_package_active VALUES(?,?) ON CONFLICT(org) DO UPDATE SET id=excluded.id').run(org,row.id);});}
 disable(ctx:PortalContext,input:unknown,key:string){const d=packageDisable.parse(input);return this.commit(ctx,'package-disable',d,key,org=>{if(this.active(org)!==d.expected_active)throw new PortalError('version_conflict');this.store.db.prepare('UPDATE customs_package_active SET id=NULL WHERE org=?').run(org);});}
 current(org:string,date:string):NativeCustomsRelease|null{try{const id=this.active(org);if(!id)return null;let cached=this.cache.get(id);const path=join(this.directory,id+'.sqlite');if(cached&&fileIdentity(path)!==cached.identity){cached.db.close();this.cache.delete(id);return null;}if(!cached){const stored=this.store.db.prepare('SELECT payload FROM customs_packages WHERE org=? AND id=?').get(org,id);if(!stored)return null;const row=packageView.parse(JSON.parse(String(stored.payload))),identity=fileIdentity(path);if(checksumSync(path)!==row.sha256||fileIdentity(path)!==identity)return null;const facts=inspect(path);if(facts.blockers.length||!facts.snapshot)return null;const db=new DatabaseSync(path,{readOnly:true});db.exec('PRAGMA query_only=ON;PRAGMA trusted_schema=OFF');const prepare=(sql:string):NativeSqlStatement=>{let values:SQLInputValue[]=[];const s:NativeSqlStatement={bind:(...v)=>{values=v as SQLInputValue[];return s;},all:<T>()=>Promise.resolve({results:db.prepare(sql).all(...values) as T[]}),first:<T>()=>Promise.resolve(db.prepare(sql).get(...values) as T|undefined??null)};return s;};const ids=z.array(z.string()).parse(JSON.parse(facts.snapshot.release_ids_json));cached={db,identity,release:{release_id:id,repository:new CustomsRepository({prepare}),sources:facts.sources.filter(s=>ids.includes(s.id)),snapshot:{...facts.snapshot,test_data:facts.snapshot.test_data??null},nomenclature:[],tariffs:[],measures:[],requirements:[]}};this.cache.set(id,cached);}return cached.release.snapshot.rule_date<=date?cached.release:null;}catch{return null;}}
 hasSelection(org:string){return this.store.db.prepare('SELECT id FROM customs_package_active WHERE org=?').get(org)!==undefined;}
 close(){for(const c of this.cache.values())c.db.close();this.cache.clear();}
}
